/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/campfire/nimcache/campfire_font.o /Users/pakchoi/Workspace/campfire/src/campfire/nimcache/campfire_font.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <stdlib.h>
#undef linux
#undef near
typedef struct FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg;
typedef struct TY_Ye8PLO8qqXk1tek2VP9c0UQ TY_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct Surface_sOGmuBWrSv9c4mZ0oaW1R1w Surface_sOGmuBWrSv9c4mZ0oaW1R1w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_Xo4YhcsfLAmbGDNu1Obfcw TY_Xo4YhcsfLAmbGDNu1Obfcw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg;
typedef struct BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g;
typedef struct Palette_D3H7z9cPmFr0tk2z8jKdcYg Palette_D3H7z9cPmFr0tk2z8jKdcYg;
struct TY_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef TY_Ye8PLO8qqXk1tek2VP9c0UQ TY_Q7mQxFMGnOjMzRwKNAb8rQ[256];
struct  FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg  {
TY_Q7mQxFMGnOjMzRwKNAb8rQ rects;
Surface_sOGmuBWrSv9c4mZ0oaW1R1w* surface;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY_Xo4YhcsfLAmbGDNu1Obfcw {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI32 Components_Leys49afTMjxiW9cmcGy4a9bw;
typedef N_CDECL_PTR(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, TY_9br0blXFlJAjbk9cGDwi8EgA) (void* pixels, int width, int height, int depth, int pitch, NU32 Rmask, NU32 Gmask, NU32 Bmask, NU32 Amask);
typedef N_CDECL_PTR(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, TY_OlsILfsIzW9b2h6RP9cRx1pQ) (Surface_sOGmuBWrSv9c4mZ0oaW1R1w* src, PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* fmt, int flags);
struct  Surface_sOGmuBWrSv9c4mZ0oaW1R1w  {
NU32 flags;
PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lock_data;
TY_Ye8PLO8qqXk1tek2VP9c0UQ clip_rect;
BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g* map;
int refcount;
};
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef NU8 TY_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct  PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg  {
NU32 format;
Palette_D3H7z9cPmFr0tk2z8jKdcYg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
TY_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* next;
};
struct  BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g  {
char dummy;
};
struct  Palette_D3H7z9cPmFr0tk2z8jKdcYg  {
int ncolors;
TY_Xo4YhcsfLAmbGDNu1Obfcw* colors;
NU32 version;
int refcount;
};
N_NIMCALL(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*, new_x0QNNzMOATMX9cEhw7StnVg)(void);
static N_NIMCALL(void, Marker_TY_e3Yr09b8Ck89byTnzx9aiiVoQ)(void* p, NI op);
N_NIMCALL(NIM_BOOL, eqeq__fEIyLrqUzJ9aTtBmneQeG7w)(TY_Xo4YhcsfLAmbGDNu1Obfcw x, TY_Xo4YhcsfLAmbGDNu1Obfcw y);
N_NIMCALL(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*, setFont_qz60kzqcdWerfTPIoRaBqQ)(Surface_sOGmuBWrSv9c4mZ0oaW1R1w* canvas, NimStringDesc* filename, NimStringDesc* chars);
N_CDECL(unsigned char*, stbi_load)(NCSTRING filename, int* x, int* y, Components_Leys49afTMjxiW9cmcGy4a9bw* comp, Components_Leys49afTMjxiW9cmcGy4a9bw req_comp);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_X2ffYU2WngxpLAobRvvlFg_;
extern TNimType NTI_Ye8PLO8qqXk1tek2VP9c0UQ_;
TNimType NTI_Q7mQxFMGnOjMzRwKNAb8rQ_;
extern TNimType NTI_RHOlqbW8lSkSefXk1XWVIw_;
TNimType NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_;
extern TY_9br0blXFlJAjbk9cGDwi8EgA Dl_223058_;
extern TY_OlsILfsIzW9b2h6RP9cRx1pQ Dl_223168_;
extern TY_09bvyvHFtWbkzL5AHgf0bKw Dl_223654_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_sApgjWmgjI8GxczXDtC9aHg_3, "error loading font: ", 20);
NIM_CONST TY_Ye8PLO8qqXk1tek2VP9c0UQ TM_sApgjWmgjI8GxczXDtC9aHg_5 = {((int) 0),
((int) 0),
((int) 0),
((int) 0)}
;
static N_NIMCALL(void, Marker_TY_e3Yr09b8Ck89byTnzx9aiiVoQ)(void* p, NI op) {
	FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg* a;
	NI T1_;
	a = (FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 256; T1_++) {
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*, setFont_qz60kzqcdWerfTPIoRaBqQ)(Surface_sOGmuBWrSv9c4mZ0oaW1R1w* canvas, NimStringDesc* filename, NimStringDesc* chars) {
	FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg* result;
	FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg* font;
	int w;
	int h;
	Components_Leys49afTMjxiW9cmcGy4a9bw components;
	unsigned char* raw_pixels;
	NU8* pixels;
	Surface_sOGmuBWrSv9c4mZ0oaW1R1w* surface;
	NI TM_sApgjWmgjI8GxczXDtC9aHg_4;
	NIM_BOOL newChar;
	TY_Xo4YhcsfLAmbGDNu1Obfcw blankColor;
	TY_Ye8PLO8qqXk1tek2VP9c0UQ currentRect;
	NI i;
	NI32 stride;
	NI TM_sApgjWmgjI8GxczXDtC9aHg_6;
	nimfr_("setFont", "font.nim")
{	result = (FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*)0;
	nimln_(10, "font.nim");
	font = new_x0QNNzMOATMX9cEhw7StnVg();
	w = (int)0;
	h = (int)0;
	components = (Components_Leys49afTMjxiW9cmcGy4a9bw)0;
	nimln_(13, "font.nim");
	raw_pixels = stbi_load(filename->data, (&w), (&h), (&components), ((Components_Leys49afTMjxiW9cmcGy4a9bw) 4));
	nimln_(14, "font.nim");
	{
		if (!(raw_pixels == NIM_NIL)) goto LA3_;
		nimln_(15, "font.nim");
		printf("%s%s\012", ((NimStringDesc*) &TM_sApgjWmgjI8GxczXDtC9aHg_3)? (((NimStringDesc*) &TM_sApgjWmgjI8GxczXDtC9aHg_3))->data:"nil", filename? (filename)->data:"nil");
		fflush(stdout);
		nimln_(16, "font.nim");
		exit(((NI) 1));
	}
	LA3_: ;
	nimln_(17, "font.nim");
	pixels = ((NU8*) (raw_pixels));
	nimln_(20, "font.nim");
	TM_sApgjWmgjI8GxczXDtC9aHg_4 = mulInt(w, ((NI32) 4));
	if (TM_sApgjWmgjI8GxczXDtC9aHg_4 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_4 > 2147483647) raiseOverflow();
	surface = Dl_223058_(((void*) (pixels)), w, h, ((int) 32), (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_4), ((NU32) IL64(4278190080)), ((NU32) 16711680), ((NU32) 65280), ((NU32) 255));
	nimln_(21, "font.nim");
	(*font).surface = Dl_223168_(surface, (*canvas).format, ((int) 0));
	nimln_(22, "font.nim");
	{
		NCSTRING T9_;
		NimStringDesc* T10_;
		if (!((*font).surface == NIM_NIL)) goto LA7_;
		nimln_(23, "font.nim");
		T9_ = (NCSTRING)0;
		T9_ = Dl_223654_();
		T10_ = (NimStringDesc*)0;
		T10_ = cstrToNimstr(T9_);
		printf("%s\012", T10_? (T10_)->data:"nil");
		fflush(stdout);
		nimln_(24, "font.nim");
		exit(((NI) 1));
	}
	LA7_: ;
	nimln_(26, "font.nim");
	newChar = NIM_FALSE;
	nimln_(27, "font.nim");
	blankColor.Field0 = pixels[(((NI) 0))- 0];
	blankColor.Field1 = pixels[(((NI) 1))- 0];
	blankColor.Field2 = pixels[(((NI) 2))- 0];
	blankColor.Field3 = pixels[(((NI) 3))- 0];
	nimln_(28, "font.nim");
	currentRect = TM_sApgjWmgjI8GxczXDtC9aHg_5;
	nimln_(29, "font.nim");
	i = ((NI) 0);
	nimln_(30, "font.nim");
	TM_sApgjWmgjI8GxczXDtC9aHg_6 = mulInt(w, ((NI32) 4));
	if (TM_sApgjWmgjI8GxczXDtC9aHg_6 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_6 > 2147483647) raiseOverflow();
	stride = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_6);
	{
		NI32 x;
		NI32 colontmp_;
		NI TM_sApgjWmgjI8GxczXDtC9aHg_7;
		NI res;
		x = (NI32)0;
		colontmp_ = (NI32)0;
		nimln_(31, "font.nim");
		TM_sApgjWmgjI8GxczXDtC9aHg_7 = subInt(w, ((NI32) 1));
		if (TM_sApgjWmgjI8GxczXDtC9aHg_7 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_7 > 2147483647) raiseOverflow();
		colontmp_ = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_7);
		nimln_(1955, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1956, "system.nim");
			while (1) {
				TY_Xo4YhcsfLAmbGDNu1Obfcw color;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_8;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_9;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_10;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_11;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_12;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_13;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_14;
				NI TM_sApgjWmgjI8GxczXDtC9aHg_37;
				if (!(res <= ((NI) (colontmp_)))) goto LA13;
				nimln_(1957, "system.nim");
				x = ((NI32)chckRange(res, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
				nimln_(32, "font.nim");
				TM_sApgjWmgjI8GxczXDtC9aHg_8 = mulInt(x, ((NI32) 4));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_8 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_8 > 2147483647) raiseOverflow();
				if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_8)) > (NU)(IL64(4294967294))) raiseIndexError();
				color.Field0 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_8))- 0];
				TM_sApgjWmgjI8GxczXDtC9aHg_9 = mulInt(x, ((NI32) 4));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_9 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_9 > 2147483647) raiseOverflow();
				TM_sApgjWmgjI8GxczXDtC9aHg_10 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_9), ((NI32) 1));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_10 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_10 > 2147483647) raiseOverflow();
				if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_10)) > (NU)(IL64(4294967294))) raiseIndexError();
				color.Field1 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_10))- 0];
				TM_sApgjWmgjI8GxczXDtC9aHg_11 = mulInt(x, ((NI32) 4));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_11 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_11 > 2147483647) raiseOverflow();
				TM_sApgjWmgjI8GxczXDtC9aHg_12 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_11), ((NI32) 2));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_12 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_12 > 2147483647) raiseOverflow();
				if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_12)) > (NU)(IL64(4294967294))) raiseIndexError();
				color.Field2 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_12))- 0];
				TM_sApgjWmgjI8GxczXDtC9aHg_13 = mulInt(x, ((NI32) 4));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_13 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_13 > 2147483647) raiseOverflow();
				TM_sApgjWmgjI8GxczXDtC9aHg_14 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_13), ((NI32) 3));
				if (TM_sApgjWmgjI8GxczXDtC9aHg_14 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_14 > 2147483647) raiseOverflow();
				if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_14)) > (NU)(IL64(4294967294))) raiseIndexError();
				color.Field3 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_14))- 0];
				nimln_(33, "font.nim");
				{
					NIM_BOOL T16_;
					NI TM_sApgjWmgjI8GxczXDtC9aHg_15;
					NI TM_sApgjWmgjI8GxczXDtC9aHg_36;
					T16_ = (NIM_BOOL)0;
					T16_ = eqeq__fEIyLrqUzJ9aTtBmneQeG7w(color, blankColor);
					if (!T16_) goto LA17_;
					nimln_(34, "font.nim");
					TM_sApgjWmgjI8GxczXDtC9aHg_15 = subInt(x, currentRect.Field0);
					if (TM_sApgjWmgjI8GxczXDtC9aHg_15 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_15 > 2147483647) raiseOverflow();
					currentRect.Field2 = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_15);
					nimln_(35, "font.nim");
					{
						NI TM_sApgjWmgjI8GxczXDtC9aHg_16;
						NI TM_sApgjWmgjI8GxczXDtC9aHg_35;
						nimln_(363, "system.nim");
						nimln_(35, "font.nim");
						if (!!((currentRect.Field2 == ((NI32) 0)))) goto LA21_;
						nimln_(37, "font.nim");
						TM_sApgjWmgjI8GxczXDtC9aHg_16 = subInt(h, ((NI32) 1));
						if (TM_sApgjWmgjI8GxczXDtC9aHg_16 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_16 > 2147483647) raiseOverflow();
						currentRect.Field3 = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_16);
						{
							NI32 y;
							NI32 colontmp__2;
							NI TM_sApgjWmgjI8GxczXDtC9aHg_17;
							NI res_2;
							y = (NI32)0;
							colontmp__2 = (NI32)0;
							nimln_(38, "font.nim");
							TM_sApgjWmgjI8GxczXDtC9aHg_17 = subInt(h, ((NI32) 1));
							if (TM_sApgjWmgjI8GxczXDtC9aHg_17 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_17 > 2147483647) raiseOverflow();
							colontmp__2 = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_17);
							nimln_(1955, "system.nim");
							res_2 = ((NI) 0);
							{
								nimln_(1956, "system.nim");
								while (1) {
									TY_Xo4YhcsfLAmbGDNu1Obfcw color_2;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_18;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_19;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_20;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_21;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_22;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_23;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_24;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_25;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_26;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_27;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_28;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_29;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_30;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_31;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_32;
									NI TM_sApgjWmgjI8GxczXDtC9aHg_34;
									if (!(res_2 <= ((NI) (colontmp__2)))) goto LA25;
									nimln_(1957, "system.nim");
									y = ((NI32)chckRange(res_2, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
									nimln_(39, "font.nim");
									TM_sApgjWmgjI8GxczXDtC9aHg_18 = mulInt(y, stride);
									if (TM_sApgjWmgjI8GxczXDtC9aHg_18 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_18 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_19 = mulInt(x, ((NI32) 4));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_19 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_19 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_20 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_18), (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_19));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_20 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_20 > 2147483647) raiseOverflow();
									if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_20)) > (NU)(IL64(4294967294))) raiseIndexError();
									color_2.Field0 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_20))- 0];
									TM_sApgjWmgjI8GxczXDtC9aHg_21 = mulInt(y, stride);
									if (TM_sApgjWmgjI8GxczXDtC9aHg_21 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_21 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_22 = mulInt(x, ((NI32) 4));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_22 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_22 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_23 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_21), (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_22));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_23 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_23 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_24 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_23), ((NI32) 1));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_24 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_24 > 2147483647) raiseOverflow();
									if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_24)) > (NU)(IL64(4294967294))) raiseIndexError();
									color_2.Field1 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_24))- 0];
									TM_sApgjWmgjI8GxczXDtC9aHg_25 = mulInt(y, stride);
									if (TM_sApgjWmgjI8GxczXDtC9aHg_25 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_25 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_26 = mulInt(x, ((NI32) 4));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_26 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_26 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_27 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_25), (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_26));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_27 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_27 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_28 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_27), ((NI32) 2));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_28 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_28 > 2147483647) raiseOverflow();
									if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_28)) > (NU)(IL64(4294967294))) raiseIndexError();
									color_2.Field2 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_28))- 0];
									TM_sApgjWmgjI8GxczXDtC9aHg_29 = mulInt(y, stride);
									if (TM_sApgjWmgjI8GxczXDtC9aHg_29 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_29 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_30 = mulInt(x, ((NI32) 4));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_30 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_30 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_31 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_29), (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_30));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_31 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_31 > 2147483647) raiseOverflow();
									TM_sApgjWmgjI8GxczXDtC9aHg_32 = addInt((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_31), ((NI32) 3));
									if (TM_sApgjWmgjI8GxczXDtC9aHg_32 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_32 > 2147483647) raiseOverflow();
									if ((NU)((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_32)) > (NU)(IL64(4294967294))) raiseIndexError();
									color_2.Field3 = pixels[((NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_32))- 0];
									nimln_(40, "font.nim");
									{
										NIM_BOOL T28_;
										NI TM_sApgjWmgjI8GxczXDtC9aHg_33;
										T28_ = (NIM_BOOL)0;
										T28_ = eqeq__fEIyLrqUzJ9aTtBmneQeG7w(color_2, blankColor);
										if (!T28_) goto LA29_;
										nimln_(41, "font.nim");
										TM_sApgjWmgjI8GxczXDtC9aHg_33 = subInt(y, ((NI32) 2));
										if (TM_sApgjWmgjI8GxczXDtC9aHg_33 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_33 > 2147483647) raiseOverflow();
										currentRect.Field3 = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_33);
									}
									LA29_: ;
									nimln_(1976, "system.nim");
									TM_sApgjWmgjI8GxczXDtC9aHg_34 = addInt(res_2, ((NI) 1));
									res_2 = (NI)(TM_sApgjWmgjI8GxczXDtC9aHg_34);
								} LA25: ;
							}
						}
						if ((NU)(i) > (NU)(chars->Sup.len)) raiseIndexError();
						if ((NU)(((NU) (((NU8)(chars->data[i]))))) > (NU)(255)) raiseIndexError();
						nimln_(42, "font.nim");
						(*font).rects[(((NU) (((NU8)(chars->data[i])))))- 0] = currentRect;
						nimln_(43, "font.nim");
						TM_sApgjWmgjI8GxczXDtC9aHg_35 = addInt(i, ((NI) 1));
						i = (NI)(TM_sApgjWmgjI8GxczXDtC9aHg_35);
					}
					LA21_: ;
					nimln_(44, "font.nim");
					newChar = NIM_TRUE;
					nimln_(45, "font.nim");
					TM_sApgjWmgjI8GxczXDtC9aHg_36 = addInt(x, ((NI32) 1));
					if (TM_sApgjWmgjI8GxczXDtC9aHg_36 < (-2147483647 -1) || TM_sApgjWmgjI8GxczXDtC9aHg_36 > 2147483647) raiseOverflow();
					currentRect.Field0 = (NI32)(TM_sApgjWmgjI8GxczXDtC9aHg_36);
				}
				LA17_: ;
				nimln_(1976, "system.nim");
				TM_sApgjWmgjI8GxczXDtC9aHg_37 = addInt(res, ((NI) 1));
				res = (NI)(TM_sApgjWmgjI8GxczXDtC9aHg_37);
			} LA13: ;
		}
	}
	nimln_(46, "font.nim");
	result = font;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, campfire_fontInit000)(void) {
	nimfr_("font", "font.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, campfire_fontDatInit000)(void) {
static TNimNode* TM_sApgjWmgjI8GxczXDtC9aHg_2[2];
static TNimNode TM_sApgjWmgjI8GxczXDtC9aHg_0[3];
NTI_X2ffYU2WngxpLAobRvvlFg_.size = sizeof(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg);
NTI_X2ffYU2WngxpLAobRvvlFg_.kind = 18;
NTI_X2ffYU2WngxpLAobRvvlFg_.base = 0;
NTI_X2ffYU2WngxpLAobRvvlFg_.flags = 3;
TM_sApgjWmgjI8GxczXDtC9aHg_2[0] = &TM_sApgjWmgjI8GxczXDtC9aHg_0[1];
NTI_Q7mQxFMGnOjMzRwKNAb8rQ_.size = sizeof(TY_Q7mQxFMGnOjMzRwKNAb8rQ);
NTI_Q7mQxFMGnOjMzRwKNAb8rQ_.kind = 16;
NTI_Q7mQxFMGnOjMzRwKNAb8rQ_.base = (&NTI_Ye8PLO8qqXk1tek2VP9c0UQ_);
NTI_Q7mQxFMGnOjMzRwKNAb8rQ_.flags = 3;
TM_sApgjWmgjI8GxczXDtC9aHg_0[1].kind = 1;
TM_sApgjWmgjI8GxczXDtC9aHg_0[1].offset = offsetof(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg, rects);
TM_sApgjWmgjI8GxczXDtC9aHg_0[1].typ = (&NTI_Q7mQxFMGnOjMzRwKNAb8rQ_);
TM_sApgjWmgjI8GxczXDtC9aHg_0[1].name = "rects";
TM_sApgjWmgjI8GxczXDtC9aHg_2[1] = &TM_sApgjWmgjI8GxczXDtC9aHg_0[2];
TM_sApgjWmgjI8GxczXDtC9aHg_0[2].kind = 1;
TM_sApgjWmgjI8GxczXDtC9aHg_0[2].offset = offsetof(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg, surface);
TM_sApgjWmgjI8GxczXDtC9aHg_0[2].typ = (&NTI_RHOlqbW8lSkSefXk1XWVIw_);
TM_sApgjWmgjI8GxczXDtC9aHg_0[2].name = "surface";
TM_sApgjWmgjI8GxczXDtC9aHg_0[0].len = 2; TM_sApgjWmgjI8GxczXDtC9aHg_0[0].kind = 2; TM_sApgjWmgjI8GxczXDtC9aHg_0[0].sons = &TM_sApgjWmgjI8GxczXDtC9aHg_2[0];
NTI_X2ffYU2WngxpLAobRvvlFg_.node = &TM_sApgjWmgjI8GxczXDtC9aHg_0[0];
NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_.size = sizeof(FontcolonObjectType__X2ffYU2WngxpLAobRvvlFg*);
NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_.kind = 22;
NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_.base = (&NTI_X2ffYU2WngxpLAobRvvlFg_);
NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_.flags = 2;
NTI_e3Yr09b8Ck89byTnzx9aiiVoQ_.marker = Marker_TY_e3Yr09b8Ck89byTnzx9aiiVoQ;
}

