/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_campfire.o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_campfire.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A;
typedef struct Vec_T08FD1ghD81Hoqk9cM9a5N4A Vec_T08FD1ghD81Hoqk9cM9a5N4A;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Vec_9aKb06UE086D5CCUfGRTkCw Vec_9aKb06UE086D5CCUfGRTkCw;
typedef NU8 SFX_lPA9cQWlW0RG6IpnRnuFv5g;
typedef NF32 TY_4YxcnnI8do9a6vmNKtzdSKw[2];
struct  Vec_T08FD1ghD81Hoqk9cM9a5N4A  {
TY_4YxcnnI8do9a6vmNKtzdSKw arr;
};
typedef NU8 ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} TY_IIomJ6ptE6vfJ5zRbATgkQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NF dt, void* ClE_0);
void* ClE_0;
} TY_YnJwmpNCHh9afvH3Cv9bk0Rw;
typedef N_CLOSURE_PTR(void, TM_2CkjNj9cO59cCX7t2zevnZmA_3) (void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_2CkjNj9cO59cCX7t2zevnZmA_4) (NF dt, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_2CkjNj9cO59cCX7t2zevnZmA_5) (void* ClE_0);
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef NI32 TY_9aCDQwgHopxUvI9buP3ce7ZQ[2];
struct  Vec_9aKb06UE086D5CCUfGRTkCw  {
TY_9aCDQwgHopxUvI9buP3ce7ZQ arr;
};
struct  ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A  {
  TNimObject Sup;
NIM_BOOL killed;
NimStringDesc* name;
NimStringDesc* description;
Vec_9aKb06UE086D5CCUfGRTkCw pos;
Vec_9aKb06UE086D5CCUfGRTkCw size;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NI, toInt_d3OptVtzsM1IEM5cwK2EHw)(SFX_lPA9cQWlW0RG6IpnRnuFv5g sfx);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, draw_UGlpL9b9caj9bn0SSy5A8e4vw)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self);
N_NIMCALL(void, update_4QzR2e1z1IzuOZ850HUicg)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self, NF dt);
N_NIMCALL(void, dummyInit_KSKGKZkTn9bt9cJmXNRSsgng)(void);
N_NIMCALL(void, menuInit_KSKGKZkTn9bt9cJmXNRSsgng_2)(void);
N_NIMCALL(void, menuUpdate_VfLtXkQfGUatA5x1oPAHng)(NF dt);
N_NIMCALL(NIM_BOOL, btnp_vAhXhoyi9b4RSzw9ccwl0VmA_2)(ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw b);
N_NIMCALL(void, menuDraw_KSKGKZkTn9bt9cJmXNRSsgng_3)(void);
N_NIMCALL(void, introInit_KSKGKZkTn9bt9cJmXNRSsgng_4)(void);
N_NIMCALL(void, introUpdate_VfLtXkQfGUatA5x1oPAHng_2)(NF dt);
N_NIMCALL(void, introDraw_KSKGKZkTn9bt9cJmXNRSsgng_5)(void);
N_NIMCALL(void, init_4jBLkr0JgNSc41m8Elh6DQ)(NimStringDesc* title);
N_NIMCALL(void, run_1m6MJtlnOHKy9aVIupw5t9ag)(TY_IIomJ6ptE6vfJ5zRbATgkQ init, TY_YnJwmpNCHh9afvH3Cv9bk0Rw update, TY_IIomJ6ptE6vfJ5zRbATgkQ draw);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_quatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_quatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_joystickInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_joystickDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gamecontrollerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gamecontrollerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecfgInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecfgDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_ringbufferInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_ringbufferDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_controllerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_controllerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_stb_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_stb_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_fontInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_fontDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_colorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_colorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_stb_image_writeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_stb_image_writeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_audioInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_audioDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_mixerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_mixerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_bootstrapInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_bootstrapDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_utilInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_utilDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_poolInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_poolDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_tweenInit000)(void);
NIM_EXTERNC N_NOINLINE(void, campfire_tweenDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, campfireDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
Vec_T08FD1ghD81Hoqk9cM9a5N4A camera_J4p5Kwq6BrWrOjcvli62Ew;
STRING_LITERAL(TM_2CkjNj9cO59cCX7t2zevnZmA_2, "Campfire", 8);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NI, toInt_d3OptVtzsM1IEM5cwK2EHw)(SFX_lPA9cQWlW0RG6IpnRnuFv5g sfx) {
	NI result;
	nimfr_("toInt", "campfire.nim")
{	result = (NI)0;
	nimln_(34, "campfire.nim");
	result = ((NI) (sfx));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, draw_UGlpL9b9caj9bn0SSy5A8e4vw)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self) {
	nimfr_("draw", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, update_4QzR2e1z1IzuOZ850HUicg)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self, NF dt) {
	nimfr_("update", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, dummyInit_KSKGKZkTn9bt9cJmXNRSsgng)(void) {
	nimfr_("dummyInit", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, menuInit_KSKGKZkTn9bt9cJmXNRSsgng_2)(void) {
	nimfr_("menuInit", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, menuUpdate_VfLtXkQfGUatA5x1oPAHng)(NF dt) {
	nimfr_("menuUpdate", "campfire.nim")
	nimln_(77, "campfire.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = btnp_vAhXhoyi9b4RSzw9ccwl0VmA_2(((ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw) 12));
		if (!T3_) goto LA4_;
	}
	LA4_: ;
	popFrame();
}

N_NIMCALL(void, menuDraw_KSKGKZkTn9bt9cJmXNRSsgng_3)(void) {
	nimfr_("menuDraw", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, introInit_KSKGKZkTn9bt9cJmXNRSsgng_4)(void) {
	nimfr_("introInit", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, introUpdate_VfLtXkQfGUatA5x1oPAHng_2)(NF dt) {
	nimfr_("introUpdate", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, introDraw_KSKGKZkTn9bt9cJmXNRSsgng_5)(void) {
	nimfr_("introDraw", "campfire.nim")
	popFrame();
}

N_NIMCALL(void, draw_9b6sZ6okN0zEGCbC08xXqlA)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self) {
	nimfr_("draw", "campfire.nim")
	nimln_(62, "campfire.nim");
	draw_UGlpL9b9caj9bn0SSy5A8e4vw(self);
	popFrame();
}

N_NIMCALL(void, update_P6srsNp1b49aCMcvgGJAwqw)(ObjectcolonObjectType__VdrLaBSjglH9cf9bVObNgN2A* self, NF dt) {
	nimfr_("update", "campfire.nim")
	nimln_(65, "campfire.nim");
	update_4QzR2e1z1IzuOZ850HUicg(self, dt);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_jsonDatInit000();
	glm_vecDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_quatDatInit000();
	glm_glmDatInit000();
	stdlib_unsignedDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_joystickDatInit000();
	sdl2_gamecontrollerDatInit000();
	stdlib_basic2dDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	stdlib_parsecfgDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	campfire_ringbufferDatInit000();
	campfire_controllerDatInit000();
	campfire_stb_imageDatInit000();
	campfire_fontDatInit000();
	campfire_colorDatInit000();
	campfire_stb_image_writeDatInit000();
	sdl2_audioDatInit000();
	sdl2_mixerDatInit000();
	campfire_bootstrapDatInit000();
	campfire_utilDatInit000();
	campfire_poolDatInit000();
	campfire_tweenDatInit000();
	campfireDatInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_jsonInit000();
	glm_vecInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_quatInit000();
	glm_glmInit000();
	stdlib_unsignedInit000();
	sdl2_sdl2Init000();
	sdl2_joystickInit000();
	sdl2_gamecontrollerInit000();
	stdlib_basic2dInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
	stdlib_parsecfgInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	campfire_ringbufferInit000();
	campfire_controllerInit000();
	campfire_stb_imageInit000();
	campfire_fontInit000();
	campfire_colorInit000();
	campfire_stb_image_writeInit000();
	sdl2_audioInit000();
	sdl2_mixerInit000();
	campfire_bootstrapInit000();
	campfire_utilInit000();
	campfire_poolInit000();
	campfire_tweenInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	TY_IIomJ6ptE6vfJ5zRbATgkQ T1_;
	TY_YnJwmpNCHh9afvH3Cv9bk0Rw T2_;
	TY_IIomJ6ptE6vfJ5zRbATgkQ T3_;
	nimfr_("campfire", "campfire.nim")
	nimln_(1606, "bootstrap.nim");
	init_4jBLkr0JgNSc41m8Elh6DQ(((NimStringDesc*) &TM_2CkjNj9cO59cCX7t2zevnZmA_2));
	nimln_(94, "campfire.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_2CkjNj9cO59cCX7t2zevnZmA_3) (introInit_KSKGKZkTn9bt9cJmXNRSsgng_4)); T1_.ClE_0 = NIM_NIL;
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = ((TM_2CkjNj9cO59cCX7t2zevnZmA_4) (introUpdate_VfLtXkQfGUatA5x1oPAHng_2)); T2_.ClE_0 = NIM_NIL;
	memset((void*)(&T3_), 0, sizeof(T3_));
	T3_.ClP_0 = ((TM_2CkjNj9cO59cCX7t2zevnZmA_5) (introDraw_KSKGKZkTn9bt9cJmXNRSsgng_5)); T3_.ClE_0 = NIM_NIL;
	run_1m6MJtlnOHKy9aVIupw5t9ag(T1_, T2_, T3_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, campfireDatInit000)(void) {
}

