/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_ringbuffer.o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_ringbuffer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA;
typedef struct TY_aLjCOs9bu5l2rz6ENM6m6Sg TY_aLjCOs9bu5l2rz6ENM6m6Sg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_6H5Oh5UUvVCLiakt9aTwtUQ TY_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct TGenericSeq TGenericSeq;
struct  RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA  {
TY_aLjCOs9bu5l2rz6ENM6m6Sg* data;
NI head;
NI tail;
NI size;
NI length;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct TY_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct TY_aLjCOs9bu5l2rz6ENM6m6Sg {
  TGenericSeq Sup;
  TY_6H5Oh5UUvVCLiakt9aTwtUQ* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_aLjCOs9bu5l2rz6ENM6m6Sg)(void* p, NI op);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(TY_aLjCOs9bu5l2rz6ENM6m6Sg*, newSeq_nLMziKm9cViNbARlJzpu51g)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
TNimType NTI_wnnQHpIWXa9b6Xz6VbAk7GA_;
extern TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;
TNimType NTI_aLjCOs9bu5l2rz6ENM6m6Sg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
static N_NIMCALL(void, Marker_TY_aLjCOs9bu5l2rz6ENM6m6Sg)(void* p, NI op) {
	TY_aLjCOs9bu5l2rz6ENM6m6Sg* a;
	NI T1_;
	a = (TY_aLjCOs9bu5l2rz6ENM6m6Sg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, add_6RaR6XBYKwDtE9cRY3qlMXA)(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA* b, TY_6H5Oh5UUvVCLiakt9aTwtUQ** data, NI dataLen_0) {
	NI TM_h3KVvwU36jOJb1EB9bj9a4HA_6;
	NI TM_h3KVvwU36jOJb1EB9bj9a4HA_7;
	NI TM_h3KVvwU36jOJb1EB9bj9a4HA_8;
	NI TM_h3KVvwU36jOJb1EB9bj9a4HA_9;
	NI TM_h3KVvwU36jOJb1EB9bj9a4HA_10;
	nimfr_("add", "ringbuffer.nim")
	{
		TY_6H5Oh5UUvVCLiakt9aTwtUQ* item;
		NI i;
		item = (TY_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
		nimln_(2052, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2053, "system.nim");
			while (1) {
				NI TM_h3KVvwU36jOJb1EB9bj9a4HA_3;
				NI TM_h3KVvwU36jOJb1EB9bj9a4HA_4;
				NI TM_h3KVvwU36jOJb1EB9bj9a4HA_5;
				if (!(i < dataLen_0)) goto LA3;
				nimln_(2054, "system.nim");
				if ((NU)(i) >= (NU)(dataLen_0)) raiseIndexError();
				item = data[i];
				nimln_(17, "ringbuffer.nim");
				TM_h3KVvwU36jOJb1EB9bj9a4HA_3 = addInt((*b).tail, ((NI) 1));
				TM_h3KVvwU36jOJb1EB9bj9a4HA_4 = modInt((NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_3), (*b).length);
				(*b).tail = (NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_4);
				if ((NU)((*b).tail) >= (NU)((*b).data->Sup.len)) raiseIndexError();
				nimln_(22, "ringbuffer.nim");
				genericSeqAssign((&(*b).data->data[(*b).tail]), item, (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_));
				nimln_(2055, "system.nim");
				TM_h3KVvwU36jOJb1EB9bj9a4HA_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_5);
			} LA3: ;
		}
	}
	nimln_(23, "ringbuffer.nim");
	TM_h3KVvwU36jOJb1EB9bj9a4HA_6 = addInt((*b).size, dataLen_0);
	(*b).size = (((NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_6) <= (*b).length) ? (NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_6) : (*b).length);
	nimln_(14, "ringbuffer.nim");
	TM_h3KVvwU36jOJb1EB9bj9a4HA_7 = addInt((*b).length, (*b).tail);
	TM_h3KVvwU36jOJb1EB9bj9a4HA_8 = subInt((NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_7), (*b).size);
	TM_h3KVvwU36jOJb1EB9bj9a4HA_9 = addInt((NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_8), ((NI) 1));
	TM_h3KVvwU36jOJb1EB9bj9a4HA_10 = modInt((NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_9), (*b).length);
	(*b).head = (NI)(TM_h3KVvwU36jOJb1EB9bj9a4HA_10);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, newRingBuffer_iYfQqgIyzbFO2ipJ0TDNVg)(NI length, RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA* Result) {
	TY_aLjCOs9bu5l2rz6ENM6m6Sg* s;
	RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA T1_;
	nimfr_("newRingBuffer", "ringbuffer.nim")
	nimln_(10, "ringbuffer.nim");
	s = newSeq_nLMziKm9cViNbARlJzpu51g(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	memset((void*)(&T1_), 0, sizeof(T1_));
	memset((void*)(&T1_), 0, sizeof(T1_));
	genericSeqAssign((&T1_.data), s, (&NTI_aLjCOs9bu5l2rz6ENM6m6Sg_));
	T1_.head = ((NI) 0);
	T1_.tail = ((NI) -1);
	T1_.size = ((NI) 0);
	T1_.length = length;
	genericShallowAssign((void*)Result, (void*)(&T1_), (&NTI_wnnQHpIWXa9b6Xz6VbAk7GA_));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, campfire_ringbufferInit000)(void) {
	nimfr_("ringbuffer", "ringbuffer.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, campfire_ringbufferDatInit000)(void) {
static TNimNode* TM_h3KVvwU36jOJb1EB9bj9a4HA_2[5];
static TNimNode TM_h3KVvwU36jOJb1EB9bj9a4HA_0[6];
NTI_wnnQHpIWXa9b6Xz6VbAk7GA_.size = sizeof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA);
NTI_wnnQHpIWXa9b6Xz6VbAk7GA_.kind = 18;
NTI_wnnQHpIWXa9b6Xz6VbAk7GA_.base = 0;
NTI_wnnQHpIWXa9b6Xz6VbAk7GA_.flags = 2;
TM_h3KVvwU36jOJb1EB9bj9a4HA_2[0] = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[1];
NTI_aLjCOs9bu5l2rz6ENM6m6Sg_.size = sizeof(TY_aLjCOs9bu5l2rz6ENM6m6Sg*);
NTI_aLjCOs9bu5l2rz6ENM6m6Sg_.kind = 24;
NTI_aLjCOs9bu5l2rz6ENM6m6Sg_.base = (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_);
NTI_aLjCOs9bu5l2rz6ENM6m6Sg_.flags = 2;
NTI_aLjCOs9bu5l2rz6ENM6m6Sg_.marker = Marker_TY_aLjCOs9bu5l2rz6ENM6m6Sg;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[1].kind = 1;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[1].offset = offsetof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA, data);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[1].typ = (&NTI_aLjCOs9bu5l2rz6ENM6m6Sg_);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[1].name = "data";
TM_h3KVvwU36jOJb1EB9bj9a4HA_2[1] = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[2];
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[2].kind = 1;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[2].offset = offsetof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA, head);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[2].name = "head";
TM_h3KVvwU36jOJb1EB9bj9a4HA_2[2] = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[3];
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[3].kind = 1;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[3].offset = offsetof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA, tail);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[3].name = "tail";
TM_h3KVvwU36jOJb1EB9bj9a4HA_2[3] = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[4];
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[4].kind = 1;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[4].offset = offsetof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA, size);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[4].name = "size";
TM_h3KVvwU36jOJb1EB9bj9a4HA_2[4] = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[5];
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[5].kind = 1;
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[5].offset = offsetof(RingBuffer_wnnQHpIWXa9b6Xz6VbAk7GA, length);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[5].name = "length";
TM_h3KVvwU36jOJb1EB9bj9a4HA_0[0].len = 5; TM_h3KVvwU36jOJb1EB9bj9a4HA_0[0].kind = 2; TM_h3KVvwU36jOJb1EB9bj9a4HA_0[0].sons = &TM_h3KVvwU36jOJb1EB9bj9a4HA_2[0];
NTI_wnnQHpIWXa9b6Xz6VbAk7GA_.node = &TM_h3KVvwU36jOJb1EB9bj9a4HA_0[0];
}

