/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_controller.o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_controller.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef linux
#undef near
typedef struct ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct GameController_KRdxeqFDO2z3WbJLpR7qIg GameController_KRdxeqFDO2z3WbJLpR7qIg;
typedef struct TY_wpFMp8IwxV6MlaM4GANJ0Q TY_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct Exception Exception;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef NU8 ControllerKind_J9cYoK9bPlWC1Hj7sdFDk9cFg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
typedef TY_wpFMp8IwxV6MlaM4GANJ0Q TY_zpS0Qb49aJLWYnCo4n46eAg[4];
typedef NI TY_OqM3FrVpsiA9a1LH5XbnAIw[14];
struct  ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w  {
  TNimObject Sup;
ControllerKind_J9cYoK9bPlWC1Hj7sdFDk9cFg kind;
NimStringDesc* name;
GameController_KRdxeqFDO2z3WbJLpR7qIg* sdlController;
NI sdlControllerId;
TY_zpS0Qb49aJLWYnCo4n46eAg axes;
TY_OqM3FrVpsiA9a1LH5XbnAIw buttons;
};
typedef N_CDECL_PTR(GameController_KRdxeqFDO2z3WbJLpR7qIg*, TY_IHNFlIJDV37XriNmIWB1nw) (int joystickIndex);
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_CDECL_PTR(NCSTRING, TY_rIwlhvvOXczOrwIzXd1KnA) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController);
typedef NU8 ControllerButton_7EF6e9aXc9abkoANid59ci5tA;
typedef NU8 ControllerAxis_a33IpZ53FG3zpky9bfcfq3g;
typedef NU8 ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw;
typedef NU8 ControllerAxis_zSj0TALsUEDba1FC1Pn3gw;
struct  GameController_KRdxeqFDO2z3WbJLpR7qIg  {
char dummy;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*, new_be9cY7fFYDUfh4pA79cdM2eQ)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_N9bO9cVkdqM4s6W9aPsgKJbBQ)(void* p, NI op);
N_NIMCALL(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*, newController_zFP59cqPpRdvaPVtvhiXDhA)(int sdlControllerId);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(void, update_rdWh5QYle5UmonQpoZsXcg)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, postUpdate_rdWh5QYle5UmonQpoZsXcg_2)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self);
N_NIMCALL(NIM_BOOL, btn_6VIV8UZ7TN4aLMjpCkYBSA)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button);
N_NIMCALL(NIM_BOOL, btnp_6VIV8UZ7TN4aLMjpCkYBSA_2)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button);
N_NIMCALL(void, setButtonState_MZawWKKaP8kRVXRdsfqjCw)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button, NIM_BOOL down);
N_NIMCALL(void, setAxisValue_UcdJQc09a6sWkKfzWHLlibg)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis, NF value);
N_NIMCALL(NF, axis_Qh7pwr9bPClO9aWYcMe3qWfQ)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis);
N_NIMCALL(NIM_BOOL, axisp_5NaUWxb6XvMkn23JBsPvcw)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis, NF value);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_pm8VizNHR9aRKzdqYOz0j2w_;
TNimType NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_2qAhgUCQIMGHXUQkjxokFQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_wpFMp8IwxV6MlaM4GANJ0Q_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_zpS0Qb49aJLWYnCo4n46eAg_;
TNimType NTI_OqM3FrVpsiA9a1LH5XbnAIw_;
TNimType NTI_N9bO9cVkdqM4s6W9aPsgKJbBQ_;
extern TY_IHNFlIJDV37XriNmIWB1nw Dl_322216_;
extern TNimType NTI_oUKtBcKRdK6usj8RWrlp6A_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TY_rIwlhvvOXczOrwIzXd1KnA Dl_322219_;
STRING_LITERAL(TM_IQov3yTFOAAOeSNcm1r9coQ_7, "error opening game controller: ", 31);
STRING_LITERAL(TM_IQov3yTFOAAOeSNcm1r9coQ_8, "KEYBOARD", 8);
STRING_LITERAL(TM_IQov3yTFOAAOeSNcm1r9coQ_9, "added game controller: ", 23);
STRING_LITERAL(TM_IQov3yTFOAAOeSNcm1r9coQ_10, ": ", 2);
static N_NIMCALL(void, Marker_TY_N9bO9cVkdqM4s6W9aPsgKJbBQ)(void* p, NI op) {
	ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* a;
	NI T1_;
	NI T2_;
	a = (ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*)p;
	nimGCvisit((void*)(*a).name, op);
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 4; T1_++) {
	}
	T2_ = (NI)0;
	for (T2_ = 0; T2_ < 14; T2_++) {
	}
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(281, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(363, "system.nim");
		nimln_(281, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(282, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(363, "system.nim");
		nimln_(282, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*, newController_zFP59cqPpRdvaPVtvhiXDhA)(int sdlControllerId) {
	ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* result;
	NimStringDesc* T14_;
	nimfr_("newController", "controller.nim")
	result = (ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*)0;
	nimln_(39, "controller.nim");
	result = new_be9cY7fFYDUfh4pA79cdM2eQ();
	nimln_(40, "controller.nim");
	(*result).sdlControllerId = ((NI) (sdlControllerId));
	nimln_(41, "controller.nim");
	{
		NCSTRING T11_;
		if (!(((NI32) -1) < sdlControllerId)) goto LA3_;
		nimln_(42, "controller.nim");
		(*result).sdlController = Dl_322216_(sdlControllerId);
		nimln_(43, "controller.nim");
		{
			Exception* e;
			NimStringDesc* T9_;
			NimStringDesc* T10_;
			if (!((*result).sdlController == NIM_NIL)) goto LA7_;
			e = (Exception*)0;
			nimln_(2634, "system.nim");
			e = (Exception*) newObj((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
			(*e).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
			nimln_(44, "controller.nim");
			T9_ = (NimStringDesc*)0;
			T10_ = (NimStringDesc*)0;
			T10_ = nimIntToStr(((NI) (sdlControllerId)));
			T9_ = rawNewString(T10_->Sup.len + 31);
appendString(T9_, ((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_7));
appendString(T9_, T10_);
			asgnRefNoCycle((void**) (&(*e).message), T9_);
			nimln_(2629, "system.nim");
			asgnRef((void**) (&(*e).parent), NIM_NIL);
			nimln_(44, "controller.nim");
			raiseException((Exception*)e, "Exception");
		}
		LA7_: ;
		nimln_(45, "controller.nim");
		(*result).kind = ((ControllerKind_J9cYoK9bPlWC1Hj7sdFDk9cFg) 1);
		nimln_(46, "controller.nim");
		T11_ = (NCSTRING)0;
		T11_ = Dl_322219_((*result).sdlController);
		asgnRefNoCycle((void**) (&(*result).name), cstrToNimstr(T11_));
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T13_;
		nimln_(48, "controller.nim");
		(*result).kind = ((ControllerKind_J9cYoK9bPlWC1Hj7sdFDk9cFg) 0);
		nimln_(49, "controller.nim");
		T13_ = (NimStringDesc*)0;
		T13_ = (*result).name; (*result).name = copyStringRC1(((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_8));
		if (T13_) nimGCunrefNoCycle(T13_);
	}
	LA1_: ;
	nimln_(50, "controller.nim");
	T14_ = (NimStringDesc*)0;
	T14_ = nimIntToStr(((NI) (sdlControllerId)));
	printf("%s%s%s%s%s%s\012", ((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_9)? (((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_9))->data:"nil", T14_? (T14_)->data:"nil", ((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_10)? (((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_10))->data:"nil", reprEnum((NI)(*result).kind, (&NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_))? (reprEnum((NI)(*result).kind, (&NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_)))->data:"nil", ((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_10)? (((NimStringDesc*) &TM_IQov3yTFOAAOeSNcm1r9coQ_10))->data:"nil", (*result).name? ((*result).name)->data:"nil");
	fflush(stdout);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, update_rdWh5QYle5UmonQpoZsXcg)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self) {
	nimfr_("update", "controller.nim")
	{
		ControllerButton_7EF6e9aXc9abkoANid59ci5tA i;
		NI res;
		i = (ControllerButton_7EF6e9aXc9abkoANid59ci5tA)0;
		nimln_(1955, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_IQov3yTFOAAOeSNcm1r9coQ_12;
				if (!(res <= ((NI) 13))) goto LA3;
				nimln_(1957, "system.nim");
				i = ((ControllerButton_7EF6e9aXc9abkoANid59ci5tA)chckRange(res, ((ControllerButton_7EF6e9aXc9abkoANid59ci5tA) 0), ((ControllerButton_7EF6e9aXc9abkoANid59ci5tA) 13)));
				nimln_(54, "controller.nim");
				{
					NI TM_IQov3yTFOAAOeSNcm1r9coQ_11;
					if (!(((NI) 1) <= (*self).buttons[(i)- 0])) goto LA6_;
					nimln_(55, "controller.nim");
					TM_IQov3yTFOAAOeSNcm1r9coQ_11 = addInt((*self).buttons[(i)- 0], ((NI) 1));
					(*self).buttons[(i)- 0] = (NI)(TM_IQov3yTFOAAOeSNcm1r9coQ_11);
				}
				LA6_: ;
				nimln_(56, "controller.nim");
				{
					if (!(((NI) 48) < (*self).buttons[(i)- 0])) goto LA10_;
					nimln_(57, "controller.nim");
					(*self).buttons[(i)- 0] = ((NI) 1);
				}
				LA10_: ;
				nimln_(1976, "system.nim");
				TM_IQov3yTFOAAOeSNcm1r9coQ_12 = addInt(res, ((NI) 1));
				res = (NI)(TM_IQov3yTFOAAOeSNcm1r9coQ_12);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, postUpdate_rdWh5QYle5UmonQpoZsXcg_2)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self) {
	nimfr_("postUpdate", "controller.nim")
	{
		ControllerAxis_a33IpZ53FG3zpky9bfcfq3g i;
		NI res;
		i = (ControllerAxis_a33IpZ53FG3zpky9bfcfq3g)0;
		nimln_(1955, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_IQov3yTFOAAOeSNcm1r9coQ_13;
				if (!(res <= ((NI) 3))) goto LA3;
				nimln_(1957, "system.nim");
				i = ((ControllerAxis_a33IpZ53FG3zpky9bfcfq3g)chckRange(res, ((ControllerAxis_a33IpZ53FG3zpky9bfcfq3g) 0), ((ControllerAxis_a33IpZ53FG3zpky9bfcfq3g) 3)));
				nimln_(61, "controller.nim");
				(*self).axes[(i)- 0].Field1 = (*self).axes[(i)- 0].Field0;
				nimln_(1976, "system.nim");
				TM_IQov3yTFOAAOeSNcm1r9coQ_13 = addInt(res, ((NI) 1));
				res = (NI)(TM_IQov3yTFOAAOeSNcm1r9coQ_13);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NIM_BOOL, btn_6VIV8UZ7TN4aLMjpCkYBSA)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button) {
	NIM_BOOL result;
	nimfr_("btn", "controller.nim")
{	result = (NIM_BOOL)0;
	nimln_(64, "controller.nim");
	result = (((NI) 0) < (*self).buttons[(button)- 0]);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, btnp_6VIV8UZ7TN4aLMjpCkYBSA_2)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button) {
	NIM_BOOL result;
	nimfr_("btnp", "controller.nim")
{	result = (NIM_BOOL)0;
	nimln_(67, "controller.nim");
	result = ((*self).buttons[(button)- 0] == ((NI) 2));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, setButtonState_MZawWKKaP8kRVXRdsfqjCw)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw button, NIM_BOOL down) {
	nimfr_("setButtonState", "controller.nim")
{	nimln_(73, "controller.nim");
	{
		if (!(((ControllerButton_DiEs4cHEZVQoTKo0j5CX9bw) 13) < button)) goto LA3_;
		nimln_(74, "controller.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(75, "controller.nim");
	{
		if (!down) goto LA7_;
		(*self).buttons[(button)- 0] = ((NI) 1);
	}
	goto LA5_;
	LA7_: ;
	{
		(*self).buttons[(button)- 0] = ((NI) 0);
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, setAxisValue_UcdJQc09a6sWkKfzWHLlibg)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis, NF value) {
	nimfr_("setAxisValue", "controller.nim")
{	nimln_(78, "controller.nim");
	{
		if (!(((ControllerAxis_zSj0TALsUEDba1FC1Pn3gw) 3) < axis)) goto LA3_;
		nimln_(79, "controller.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(80, "controller.nim");
	(*self).axes[(axis)- 0].Field0 = value;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(NF, axis_Qh7pwr9bPClO9aWYcMe3qWfQ)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis) {
	NF result;
	nimfr_("axis", "controller.nim")
{	result = (NF)0;
	nimln_(86, "controller.nim");
	result = (*self).axes[(axis)- 0].Field0;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, axisp_5NaUWxb6XvMkn23JBsPvcw)(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w* self, ControllerAxis_zSj0TALsUEDba1FC1Pn3gw axis, NF value) {
	NIM_BOOL result;
	nimfr_("axisp", "controller.nim")
{	result = (NIM_BOOL)0;
	nimln_(92, "controller.nim");
	{
		NIM_BOOL T5_;
		if (!(value == -1.0000000000000000e+00)) goto LA3_;
		nimln_(93, "controller.nim");
		T5_ = (NIM_BOOL)0;
		T5_ = ((*self).axes[(axis)- 0].Field0 < -5.0000000000000000e-01);
		if (!(T5_)) goto LA6_;
		T5_ = !(((*self).axes[(axis)- 0].Field1 < -5.0000000000000000e-01));
		LA6_: ;
		result = T5_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T10_;
		nimln_(94, "controller.nim");
		if (!(value == 1.0000000000000000e+00)) goto LA8_;
		nimln_(95, "controller.nim");
		T10_ = (NIM_BOOL)0;
		T10_ = (5.0000000000000000e-01 < (*self).axes[(axis)- 0].Field0);
		if (!(T10_)) goto LA11_;
		T10_ = !(((*self).axes[(axis)- 0].Field1 < -5.0000000000000000e-01));
		LA11_: ;
		result = T10_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	{
		NIM_BOOL T15_;
		nimln_(96, "controller.nim");
		if (!(value == 0.0)) goto LA13_;
		nimln_(97, "controller.nim");
		T15_ = (NIM_BOOL)0;
		T15_ = (((*self).axes[(axis)- 0].Field0 < 0? -((*self).axes[(axis)- 0].Field0) : ((*self).axes[(axis)- 0].Field0)) < 5.0000000000000000e-01);
		if (!(T15_)) goto LA16_;
		T15_ = !((((*self).axes[(axis)- 0].Field1 < 0? -((*self).axes[(axis)- 0].Field1) : ((*self).axes[(axis)- 0].Field1)) < 5.0000000000000000e-01));
		LA16_: ;
		result = T15_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA13_: ;
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, campfire_controllerInit000)(void) {
	nimfr_("controller", "controller.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, campfire_controllerDatInit000)(void) {
static TNimNode* TM_IQov3yTFOAAOeSNcm1r9coQ_2[6];
static TNimNode* TM_IQov3yTFOAAOeSNcm1r9coQ_3[2];
NI TM_IQov3yTFOAAOeSNcm1r9coQ_5;
static char* NIM_CONST TM_IQov3yTFOAAOeSNcm1r9coQ_4[2] = {
"Keyboard", 
"Gamepad"};
static TNimNode* TM_IQov3yTFOAAOeSNcm1r9coQ_6[2];
static TNimNode TM_IQov3yTFOAAOeSNcm1r9coQ_0[13];
NTI_pm8VizNHR9aRKzdqYOz0j2w_.size = sizeof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w);
NTI_pm8VizNHR9aRKzdqYOz0j2w_.kind = 17;
NTI_pm8VizNHR9aRKzdqYOz0j2w_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_IQov3yTFOAAOeSNcm1r9coQ_2[0] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[1];
NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_.size = sizeof(ControllerKind_J9cYoK9bPlWC1Hj7sdFDk9cFg);
NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_.kind = 14;
NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_.base = 0;
NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_.flags = 3;
for (TM_IQov3yTFOAAOeSNcm1r9coQ_5 = 0; TM_IQov3yTFOAAOeSNcm1r9coQ_5 < 2; TM_IQov3yTFOAAOeSNcm1r9coQ_5++) {
TM_IQov3yTFOAAOeSNcm1r9coQ_0[TM_IQov3yTFOAAOeSNcm1r9coQ_5+2].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[TM_IQov3yTFOAAOeSNcm1r9coQ_5+2].offset = TM_IQov3yTFOAAOeSNcm1r9coQ_5;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[TM_IQov3yTFOAAOeSNcm1r9coQ_5+2].name = TM_IQov3yTFOAAOeSNcm1r9coQ_4[TM_IQov3yTFOAAOeSNcm1r9coQ_5];
TM_IQov3yTFOAAOeSNcm1r9coQ_3[TM_IQov3yTFOAAOeSNcm1r9coQ_5] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[TM_IQov3yTFOAAOeSNcm1r9coQ_5+2];
}
TM_IQov3yTFOAAOeSNcm1r9coQ_0[4].len = 2; TM_IQov3yTFOAAOeSNcm1r9coQ_0[4].kind = 2; TM_IQov3yTFOAAOeSNcm1r9coQ_0[4].sons = &TM_IQov3yTFOAAOeSNcm1r9coQ_3[0];
NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_.node = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[4];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[1].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[1].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, kind);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[1].typ = (&NTI_J9cYoK9bPlWC1Hj7sdFDk9cFg_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[1].name = "kind";
TM_IQov3yTFOAAOeSNcm1r9coQ_2[1] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[5];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[5].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[5].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, name);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[5].name = "name";
TM_IQov3yTFOAAOeSNcm1r9coQ_2[2] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[6];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[6].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[6].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, sdlController);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[6].typ = (&NTI_2qAhgUCQIMGHXUQkjxokFQ_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[6].name = "sdlController";
TM_IQov3yTFOAAOeSNcm1r9coQ_2[3] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[7];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[7].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[7].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, sdlControllerId);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[7].name = "sdlControllerId";
TM_IQov3yTFOAAOeSNcm1r9coQ_2[4] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[8];
NTI_wpFMp8IwxV6MlaM4GANJ0Q_.size = sizeof(TY_wpFMp8IwxV6MlaM4GANJ0Q);
NTI_wpFMp8IwxV6MlaM4GANJ0Q_.kind = 18;
NTI_wpFMp8IwxV6MlaM4GANJ0Q_.base = 0;
NTI_wpFMp8IwxV6MlaM4GANJ0Q_.flags = 3;
TM_IQov3yTFOAAOeSNcm1r9coQ_6[0] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[10];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[10].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[10].offset = offsetof(TY_wpFMp8IwxV6MlaM4GANJ0Q, Field0);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[10].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[10].name = "Field0";
TM_IQov3yTFOAAOeSNcm1r9coQ_6[1] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[11];
TM_IQov3yTFOAAOeSNcm1r9coQ_0[11].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[11].offset = offsetof(TY_wpFMp8IwxV6MlaM4GANJ0Q, Field1);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[11].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[11].name = "Field1";
TM_IQov3yTFOAAOeSNcm1r9coQ_0[9].len = 2; TM_IQov3yTFOAAOeSNcm1r9coQ_0[9].kind = 2; TM_IQov3yTFOAAOeSNcm1r9coQ_0[9].sons = &TM_IQov3yTFOAAOeSNcm1r9coQ_6[0];
NTI_wpFMp8IwxV6MlaM4GANJ0Q_.node = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[9];
NTI_zpS0Qb49aJLWYnCo4n46eAg_.size = sizeof(TY_zpS0Qb49aJLWYnCo4n46eAg);
NTI_zpS0Qb49aJLWYnCo4n46eAg_.kind = 16;
NTI_zpS0Qb49aJLWYnCo4n46eAg_.base = (&NTI_wpFMp8IwxV6MlaM4GANJ0Q_);
NTI_zpS0Qb49aJLWYnCo4n46eAg_.flags = 3;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[8].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[8].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, axes);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[8].typ = (&NTI_zpS0Qb49aJLWYnCo4n46eAg_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[8].name = "axes";
TM_IQov3yTFOAAOeSNcm1r9coQ_2[5] = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[12];
NTI_OqM3FrVpsiA9a1LH5XbnAIw_.size = sizeof(TY_OqM3FrVpsiA9a1LH5XbnAIw);
NTI_OqM3FrVpsiA9a1LH5XbnAIw_.kind = 16;
NTI_OqM3FrVpsiA9a1LH5XbnAIw_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_OqM3FrVpsiA9a1LH5XbnAIw_.flags = 3;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[12].kind = 1;
TM_IQov3yTFOAAOeSNcm1r9coQ_0[12].offset = offsetof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w, buttons);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[12].typ = (&NTI_OqM3FrVpsiA9a1LH5XbnAIw_);
TM_IQov3yTFOAAOeSNcm1r9coQ_0[12].name = "buttons";
TM_IQov3yTFOAAOeSNcm1r9coQ_0[0].len = 6; TM_IQov3yTFOAAOeSNcm1r9coQ_0[0].kind = 2; TM_IQov3yTFOAAOeSNcm1r9coQ_0[0].sons = &TM_IQov3yTFOAAOeSNcm1r9coQ_2[0];
NTI_pm8VizNHR9aRKzdqYOz0j2w_.node = &TM_IQov3yTFOAAOeSNcm1r9coQ_0[0];
NTI_N9bO9cVkdqM4s6W9aPsgKJbBQ_.size = sizeof(ControllercolonObjectType__pm8VizNHR9aRKzdqYOz0j2w*);
NTI_N9bO9cVkdqM4s6W9aPsgKJbBQ_.kind = 22;
NTI_N9bO9cVkdqM4s6W9aPsgKJbBQ_.base = (&NTI_pm8VizNHR9aRKzdqYOz0j2w_);
NTI_N9bO9cVkdqM4s6W9aPsgKJbBQ_.marker = Marker_TY_N9bO9cVkdqM4s6W9aPsgKJbBQ;
}

