/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_color.o /Users/pakchoi/Workspace/campfire/src/nimcache/campfire_color.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct TY_Xo4YhcsfLAmbGDNu1Obfcw TY_Xo4YhcsfLAmbGDNu1Obfcw;
struct TY_Xo4YhcsfLAmbGDNu1Obfcw {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
typedef TY_Xo4YhcsfLAmbGDNu1Obfcw TY_2IUQuySOlH0hC4vSqVvrJg[16];
N_NIMCALL(TY_Xo4YhcsfLAmbGDNu1Obfcw, makeColor_4FHGhuWrenBI7EaNvV2Brg)(NI r, NI g, NI b, NI a);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_2IUQuySOlH0hC4vSqVvrJg colors_2Oca9aI5r9ca1marM7Bqzjvw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(TY_Xo4YhcsfLAmbGDNu1Obfcw, makeColor_4FHGhuWrenBI7EaNvV2Brg)(NI r, NI g, NI b, NI a) {
	TY_Xo4YhcsfLAmbGDNu1Obfcw result;
	nimfr_("makeColor", "color.nim")
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(4, "color.nim");
	result.Field0 = ((NU8) (r));
	result.Field1 = ((NU8) (g));
	result.Field2 = ((NU8) (b));
	result.Field3 = ((NU8) (a));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, campfire_colorInit000)(void) {
	nimfr_("color", "color.nim")
	nimln_(6, "color.nim");
	nimln_(7, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[0] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 255));
	nimln_(8, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[1] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 157), ((NI) 157), ((NI) 157), ((NI) 255));
	nimln_(9, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[2] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 255), ((NI) 255), ((NI) 255), ((NI) 255));
	nimln_(10, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[3] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 190), ((NI) 38), ((NI) 51), ((NI) 255));
	nimln_(11, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[4] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 224), ((NI) 111), ((NI) 139), ((NI) 255));
	nimln_(12, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[5] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 73), ((NI) 60), ((NI) 43), ((NI) 255));
	nimln_(13, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[6] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 164), ((NI) 100), ((NI) 34), ((NI) 255));
	nimln_(14, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[7] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 235), ((NI) 137), ((NI) 49), ((NI) 255));
	nimln_(15, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[8] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 247), ((NI) 226), ((NI) 107), ((NI) 255));
	nimln_(16, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[9] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 47), ((NI) 72), ((NI) 78), ((NI) 255));
	nimln_(17, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[10] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 68), ((NI) 137), ((NI) 26), ((NI) 255));
	nimln_(18, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[11] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 163), ((NI) 206), ((NI) 39), ((NI) 255));
	nimln_(19, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[12] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 27), ((NI) 38), ((NI) 50), ((NI) 255));
	nimln_(20, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[13] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 0), ((NI) 87), ((NI) 132), ((NI) 255));
	nimln_(21, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[14] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 49), ((NI) 162), ((NI) 242), ((NI) 255));
	nimln_(22, "color.nim");
	colors_2Oca9aI5r9ca1marM7Bqzjvw[15] = makeColor_4FHGhuWrenBI7EaNvV2Brg(((NI) 178), ((NI) 220), ((NI) 239), ((NI) 255));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, campfire_colorDatInit000)(void) {
}

