/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/glm_vec.o /Users/pakchoi/Workspace/campfire/src/nimcache/glm_vec.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Vec_nc2ATn3mNKEC36f9a1o6BCw Vec_nc2ATn3mNKEC36f9a1o6BCw;
typedef struct Vec_8lp09c9aJ6sSqRDc8uUVfyuA Vec_8lp09c9aJ6sSqRDc8uUVfyuA;
typedef struct Vec_T08FD1ghD81Hoqk9cM9a5N4A Vec_T08FD1ghD81Hoqk9cM9a5N4A;
typedef struct Vec_ajluWiFZ8tTU9b0kwuUOFAQ Vec_ajluWiFZ8tTU9b0kwuUOFAQ;
typedef struct Vec_S5njPDIR1N39afJ9a6EQzdbA Vec_S5njPDIR1N39afJ9a6EQzdbA;
typedef struct Vec_qy9aZB04gHVo2Fdc9cBiC1lQ Vec_qy9aZB04gHVo2Fdc9cBiC1lQ;
typedef struct Vec_qoh4I3S7szDtqndE7w821A Vec_qoh4I3S7szDtqndE7w821A;
typedef struct Vec_1NKXb6ubeY6FA7tob82PEQ Vec_1NKXb6ubeY6FA7tob82PEQ;
typedef struct Vec_9aKb06UE086D5CCUfGRTkCw Vec_9aKb06UE086D5CCUfGRTkCw;
typedef struct Vec_9aAA0mkLUcOpqzQWa0X35lQ Vec_9aAA0mkLUcOpqzQWa0X35lQ;
typedef struct Vec_iIbuLPPEYFaqJVU7HL38lg Vec_iIbuLPPEYFaqJVU7HL38lg;
typedef struct Vec_xvhdgGTJojI5JMPWZZjAUA Vec_xvhdgGTJojI5JMPWZZjAUA;
typedef struct Vec_cO7UTx7dC4Be7bYZfqim4A Vec_cO7UTx7dC4Be7bYZfqim4A;
typedef struct Vec_9aztRZVEL2VMPS9atezTlYcA Vec_9aztRZVEL2VMPS9atezTlYcA;
typedef struct Vec_BqKjkNSpfyUs9bcQiwYWOiA Vec_BqKjkNSpfyUs9bcQiwYWOiA;
typedef struct Vec_e9cK0Tq83JFPJqJIfZRZyhA Vec_e9cK0Tq83JFPJqJIfZRZyhA;
typedef struct Vec_ogSyGSIJGmYX79bYY4VdDjw Vec_ogSyGSIJGmYX79bYY4VdDjw;
typedef struct Vec_JPtIiVa2O8jVD51dPzuPOg Vec_JPtIiVa2O8jVD51dPzuPOg;
typedef struct Vec_WQ9bEBJLif1zK31OfAoIxvg Vec_WQ9bEBJLif1zK31OfAoIxvg;
typedef struct Vec_3egAWLIGVBOuRqLSHvHuUA Vec_3egAWLIGVBOuRqLSHvHuUA;
typedef struct Vec_3DDkv6KTVqOpdZoQMMqqgA Vec_3DDkv6KTVqOpdZoQMMqqgA;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF32 TY_9aTCwbdg1cSQimdVd0OEKVw[4];
struct  Vec_nc2ATn3mNKEC36f9a1o6BCw  {
TY_9aTCwbdg1cSQimdVd0OEKVw arr;
};
typedef NF32 TY_mXNbtvWKAiZn9bWV4uCjiKg[3];
struct  Vec_8lp09c9aJ6sSqRDc8uUVfyuA  {
TY_mXNbtvWKAiZn9bWV4uCjiKg arr;
};
typedef NF32 TY_4YxcnnI8do9a6vmNKtzdSKw[2];
struct  Vec_T08FD1ghD81Hoqk9cM9a5N4A  {
TY_4YxcnnI8do9a6vmNKtzdSKw arr;
};
typedef NF TY_jOGfJgrdxgfAJsLC7WNNEw[4];
struct  Vec_ajluWiFZ8tTU9b0kwuUOFAQ  {
TY_jOGfJgrdxgfAJsLC7WNNEw arr;
};
typedef NF TY_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
struct  Vec_S5njPDIR1N39afJ9a6EQzdbA  {
TY_9ce69c9a1NzlPVqY9aKHS79b5IQ arr;
};
typedef NF TY_Tgy9b6R4KdSrcLohzVAUl8w[2];
struct  Vec_qy9aZB04gHVo2Fdc9cBiC1lQ  {
TY_Tgy9b6R4KdSrcLohzVAUl8w arr;
};
typedef NI32 TY_7pxmxukJp9aDJpjDIdzM2gw[4];
struct  Vec_qoh4I3S7szDtqndE7w821A  {
TY_7pxmxukJp9aDJpjDIdzM2gw arr;
};
typedef NI32 TY_0v3OTtI03bagPhcjf9byD9bA[3];
struct  Vec_1NKXb6ubeY6FA7tob82PEQ  {
TY_0v3OTtI03bagPhcjf9byD9bA arr;
};
typedef NI32 TY_9aCDQwgHopxUvI9buP3ce7ZQ[2];
struct  Vec_9aKb06UE086D5CCUfGRTkCw  {
TY_9aCDQwgHopxUvI9buP3ce7ZQ arr;
};
typedef NI64 TY_H75eOnX1DhNAJQlsu1XRUQ[4];
struct  Vec_9aAA0mkLUcOpqzQWa0X35lQ  {
TY_H75eOnX1DhNAJQlsu1XRUQ arr;
};
typedef NI64 TY_c1FRN1mZ4GK3unahWR0Nyg[3];
struct  Vec_iIbuLPPEYFaqJVU7HL38lg  {
TY_c1FRN1mZ4GK3unahWR0Nyg arr;
};
typedef NI64 TY_EawPLnQhPqWwYm5GdCoh8A[2];
struct  Vec_xvhdgGTJojI5JMPWZZjAUA  {
TY_EawPLnQhPqWwYm5GdCoh8A arr;
};
typedef NU32 TY_FleBT9cC2nxhgiXmSYYnEKA[4];
struct  Vec_cO7UTx7dC4Be7bYZfqim4A  {
TY_FleBT9cC2nxhgiXmSYYnEKA arr;
};
typedef NU32 TY_gTZlS3AoaORR9c8ta0HwzwQ[3];
struct  Vec_9aztRZVEL2VMPS9atezTlYcA  {
TY_gTZlS3AoaORR9c8ta0HwzwQ arr;
};
typedef NU32 TY_JlnxiR65D9cjJpwi6uBZRtA[2];
struct  Vec_BqKjkNSpfyUs9bcQiwYWOiA  {
TY_JlnxiR65D9cjJpwi6uBZRtA arr;
};
typedef NU64 TY_WOK9agWVIFrysHjlc69b06uA[4];
struct  Vec_e9cK0Tq83JFPJqJIfZRZyhA  {
TY_WOK9agWVIFrysHjlc69b06uA arr;
};
typedef NU64 TY_9aCQ9bMIqvRssXzylDx47Csg[3];
struct  Vec_ogSyGSIJGmYX79bYY4VdDjw  {
TY_9aCQ9bMIqvRssXzylDx47Csg arr;
};
typedef NU64 TY_NzKR9bw29cLPrd712Xt6Liiw[2];
struct  Vec_JPtIiVa2O8jVD51dPzuPOg  {
TY_NzKR9bw29cLPrd712Xt6Liiw arr;
};
typedef NIM_BOOL TY_XyV9b4LviDmOhnxKqnZG2Rg[4];
struct  Vec_WQ9bEBJLif1zK31OfAoIxvg  {
TY_XyV9b4LviDmOhnxKqnZG2Rg arr;
};
typedef NIM_BOOL TY_xSxqoPo7Fj4uIDcWiYyWDg[3];
struct  Vec_3egAWLIGVBOuRqLSHvHuUA  {
TY_xSxqoPo7Fj4uIDcWiYyWDg arr;
};
typedef NIM_BOOL TY_Gl9aAKPegYDOYkxLtedgz8w[2];
struct  Vec_3DDkv6KTVqOpdZoQMMqqgA  {
TY_Gl9aAKPegYDOYkxLtedgz8w arr;
};
N_NIMCALL(NimStringDesc*, spaces_iOxQV89aDy30Iwxtiy0Ox3g)(NI num);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, growingIndices_9bVN9bVIkj5bKH9c9c8fUPpMQg)(NI* indices, NI indicesLen_0);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, continuousIndices_9bVN9bVIkj5bKH9c9c8fUPpMQg_2)(NI* indices, NI indicesLen_0);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_AaOb1efTPrDJJ9aKeFHEEGwvec)(NF32 x, NF32 y, NF32 z, NF32 w);
static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_ITdPzFAfjQ2t9c6sbu9bSPiQvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_l49bIJsW4znHbNVu9cWYhQvAvec)(NF32 x, Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, x_zDAAwBD1pE9bMOlggGBZrqAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v);
static N_INLINE(NF32, y_zDAAwBD1pE9bMOlggGBZrqA_2vec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_tWJoRgTOvCdib459c9bLGPiAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A a, Vec_T08FD1ghD81Hoqk9cM9a5N4A b);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_vU3MyYZGxYO6Amp2SBffoAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 z, NF32 w);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_vzWI77mO9ar9aaBPt3Tr5rPwvec)(NF32 x, Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 w);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_cyZbJYKxLGJZ9blcCHg6F2gvec)(NF32 x, NF32 y, Vec_T08FD1ghD81Hoqk9cM9a5N4A v);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_Khepf4d4yzJM7kPke7ANKgvec)(NF32 x);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_bV33b6rSAdvcVnmP1zcMwQvec)(NF32 x, NF32 y, NF32 z);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_NYW534GxniLO9bJqYxxpmzgvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 z);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_Dv4TrjtdikkF9cFfcAhqf0Avec)(NF32 x, Vec_T08FD1ghD81Hoqk9cM9a5N4A v);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_o9cnKbmHtoD9cX358Njdry0Qvec)(NF32 x);
static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_bFH2VqQFdPukth3adfquxAvec)(NF32 x, NF32 y);
static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_TIW76y9cHjQuPEz9bE78Uglwvec)(NF32 x);
static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_TjdOKcRkin72vGwAIL9cxtQvec)(TY_9aTCwbdg1cSQimdVd0OEKVw a);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_SCOt9bvN5yHI9c551LYoeAvAvec)(TY_mXNbtvWKAiZn9bWV4uCjiKg a);
static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_iYY8nGAxCDd6HN9aNlvpmugvec)(TY_4YxcnnI8do9a6vmNKtzdSKw a);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_sDUnYkRwC2Xp9c9cl1DVimlAvec)(NF x, NF y, NF z, NF w);
static N_INLINE(NF, x_NpfOyWKi6CLtEhMWqkmyuQvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(NF, y_NpfOyWKi6CLtEhMWqkmyuQ_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(NF, z_NpfOyWKi6CLtEhMWqkmyuQ_3vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_iba43GbOddIV9cfpsmLmkOQvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, NF w);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_8s9bhmCa1wTfJuEjaBtskVAvec)(NF x, Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(NF, x_6EIz8NT1pb4kvVGUAxuB5Qvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v);
static N_INLINE(NF, y_6EIz8NT1pb4kvVGUAxuB5Q_2vec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_6oTAdrLRLyFdtnA8a43AFQvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ a, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ b);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_bvHwbWJsrhsHw9c9ckzMpmOgvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF z, NF w);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_kPwRwj66TdDoMp9bLGRd2Xwvec)(NF x, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF w);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_ubfs1KKV5Avgcz3cMB89b7Qvec)(NF x, NF y, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v);
static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_B88KGA6RXe7bcCjHv6cuZwvec)(NF x);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_ttKlGVy9ccAyQnjUSeKaLlAvec)(NF x, NF y, NF z);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_jOvX55ePQ6hYtNMnaPxjSQvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF z);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_l78qgNlE5JqtGC23qXk9aXQvec)(NF x, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_Z8CAV18F7TJpju4rhYgsGQvec)(NF x);
static N_INLINE(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ, vec2d_Ai8R9cfJd6oFQs9b4Sm0xuggvec)(NF x, NF y);
static N_INLINE(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ, vec2d_1yEH1G0DugRdybqO6hUPFQvec)(NF x);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_X6X5LukS9aIiwrjghuzjuXAvec)(NI32 x, NI32 y, NI32 z, NI32 w);
static N_INLINE(NI32, x_9abzu6AHoUHvgfo6kuWMirwvec)(Vec_1NKXb6ubeY6FA7tob82PEQ v);
static N_INLINE(NI32, y_9abzu6AHoUHvgfo6kuWMirw_2vec)(Vec_1NKXb6ubeY6FA7tob82PEQ v);
static N_INLINE(NI32, z_9abzu6AHoUHvgfo6kuWMirw_3vec)(Vec_1NKXb6ubeY6FA7tob82PEQ v);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_CVQV8M9a3oPfD2HXtAPOegAvec)(Vec_1NKXb6ubeY6FA7tob82PEQ v, NI32 w);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_N9chL8qiyGW9au9b6Dd1kZU8Qvec)(NI32 x, Vec_1NKXb6ubeY6FA7tob82PEQ v);
static N_INLINE(NI32, x_granXNW4Q9bETey6wYbJ9czwvec)(Vec_9aKb06UE086D5CCUfGRTkCw v);
static N_INLINE(NI32, y_granXNW4Q9bETey6wYbJ9czw_2vec)(Vec_9aKb06UE086D5CCUfGRTkCw v);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_2vwXJLsoe0Pn8cgPwt1r1Avec)(Vec_9aKb06UE086D5CCUfGRTkCw a, Vec_9aKb06UE086D5CCUfGRTkCw b);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_WCHDuUozRS9bnBHO4NccroAvec)(Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 z, NI32 w);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_lzxGnsjqFlTOyJY3Jvi9byAvec)(NI32 x, Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 w);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_6E0z2oi3O0TPpAEEp6cfgwvec)(NI32 x, NI32 y, Vec_9aKb06UE086D5CCUfGRTkCw v);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_rxCLDgjdv9c6hQnd3Jrz9cOAvec)(NI32 x);
static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_wieUAPz85YKb2uA5QSPC0Avec)(NI32 x, NI32 y, NI32 z);
static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_kaW0ejb6ttcEyeP8PdvHmwvec)(Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 z);
static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_wCyztboNbIy1S0BFYBxqhgvec)(NI32 x, Vec_9aKb06UE086D5CCUfGRTkCw v);
static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_focre0WM1e8tb9aLqDI9bPPgvec)(NI32 x);
static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_I7t0dID7Vdxmhyv4KFBlZAvec)(NI32 x, NI32 y);
static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_etsrHeuexMmJjbA4LBcr1Avec)(NI32 x);
static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_S5Nm9ayKelhGyoY9c9bAHunvAvec)(TY_7pxmxukJp9aDJpjDIdzM2gw a);
static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_zEnl3I1aW1KKJrNM0z9cRZgvec)(TY_0v3OTtI03bagPhcjf9byD9bA a);
static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_JiPWCM1bTIdjBfFfJlxtfQvec)(TY_9aCDQwgHopxUvI9buP3ce7ZQ a);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_YhEDdvhDE3kJdtR2QIg1RQvec)(NI64 x, NI64 y, NI64 z, NI64 w);
static N_INLINE(NI64, x_q1teFDm9byIkhYlelQKQnXgvec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v);
static N_INLINE(NI64, y_q1teFDm9byIkhYlelQKQnXg_2vec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v);
static N_INLINE(NI64, z_q1teFDm9byIkhYlelQKQnXg_3vec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_x9cbBuGnpdR8cb9brbibxU9aAvec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v, NI64 w);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_TTH5hM0JlnZIJR9cXaiL8MAvec)(NI64 x, Vec_iIbuLPPEYFaqJVU7HL38lg* v);
static N_INLINE(NI64, x_UNLP2bIcV49bVQP7rqRrPNwvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v);
static N_INLINE(NI64, y_UNLP2bIcV49bVQP7rqRrPNw_2vec)(Vec_xvhdgGTJojI5JMPWZZjAUA v);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_P9bjd9a9bP4k0nYI0VuUSwfqQvec)(Vec_xvhdgGTJojI5JMPWZZjAUA a, Vec_xvhdgGTJojI5JMPWZZjAUA b);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_RPJjI9aOFdCK7NULT9bWN0eQvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 z, NI64 w);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_aVBKSA4OoP9aDfQS8QrglKQvec)(NI64 x, Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 w);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_AT01ZZFeTfOXecaBLSsmVwvec)(NI64 x, NI64 y, Vec_xvhdgGTJojI5JMPWZZjAUA v);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_ZwAtJlu9c71EPotrsrf8DQgvec)(NI64 x);
static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_z1Nr9aR4CiBIDeigtktwgFAvec)(NI64 x, NI64 y, NI64 z);
static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_4vRAl8qbmW80G8sVu69aDXgvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 z);
static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_F1xM3Epey9b8TNIYAFi9cwjQvec)(NI64 x, Vec_xvhdgGTJojI5JMPWZZjAUA v);
static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_IH1IP3SWejU3lXJRkZYVegvec)(NI64 x);
static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_Q9bqjFwhGOb9ao2xKr1uyluAvec)(NI64 x, NI64 y);
static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_s6rEBDvBdKwr5nFgrexf1Avec)(NI64 x);
static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_YKZC49cuUmCYUj6JYi5VbjQvec)(TY_H75eOnX1DhNAJQlsu1XRUQ a);
static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_EEehEk9adil9aQUwK03Whr5wvec)(TY_c1FRN1mZ4GK3unahWR0Nyg a);
static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_sFC3D6sNc8XjOl9bhxvu9cCwvec)(TY_EawPLnQhPqWwYm5GdCoh8A a);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_rtgpg3HEX4J7tZ3SCOyEcwvec)(NU32 x, NU32 y, NU32 z, NU32 w);
static N_INLINE(NU32, x_MnLL7WHAMLuZH25EuK8yswvec)(Vec_9aztRZVEL2VMPS9atezTlYcA v);
static N_INLINE(NU32, y_MnLL7WHAMLuZH25EuK8ysw_2vec)(Vec_9aztRZVEL2VMPS9atezTlYcA v);
static N_INLINE(NU32, z_MnLL7WHAMLuZH25EuK8ysw_3vec)(Vec_9aztRZVEL2VMPS9atezTlYcA v);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_jRlDePLsD9bmeBkH8U7F9bawvec)(Vec_9aztRZVEL2VMPS9atezTlYcA v, NU32 w);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_dtUOpBvc31I4vrliR9aNPUAvec)(NU32 x, Vec_9aztRZVEL2VMPS9atezTlYcA v);
static N_INLINE(NU32, x_CGzhTgz7EE4N8yRTH9cUB0wvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v);
static N_INLINE(NU32, y_CGzhTgz7EE4N8yRTH9cUB0w_2vec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_soFOY1FlOue8eFEp0bBE3Qvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA a, Vec_BqKjkNSpfyUs9bcQiwYWOiA b);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_tEWtZH5m8AJW86bWi4RAaQvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 z, NU32 w);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_B34I9c9aiXP9cSmSH9axfaRgMgvec)(NU32 x, Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 w);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_GXY3SbgHzWbDm6nJbtJDNQvec)(NU32 x, NU32 y, Vec_BqKjkNSpfyUs9bcQiwYWOiA v);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_p3I9bmmDOb9beJfFZR4tAVQQvec)(NU32 x);
static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_AtEKxaA9aBANHq26Oik7O9cgvec)(NU32 x, NU32 y, NU32 z);
static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_OGFxDeHVdCRhetacjSVAVwvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 z);
static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_s9bbJ6wlwFQaRp9aaahy2DPQvec)(NU32 x, Vec_BqKjkNSpfyUs9bcQiwYWOiA v);
static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_0iMHZIqTmE9brxzSf8fYEvgvec)(NU32 x);
static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_FzkGFeyd5u1oeVxLG4Y6Ogvec)(NU32 x, NU32 y);
static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_FuvuACF9avqhdvfe4LuG7qAvec)(NU32 x);
static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_UCDoYRNrLZThX9bKa7AD4Ogvec)(TY_FleBT9cC2nxhgiXmSYYnEKA a);
static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_afcqvUW7BspOn5R7R9co8zQvec)(TY_gTZlS3AoaORR9c8ta0HwzwQ a);
static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_GvTec6R3XAFCn0M4tnwhRwvec)(TY_JlnxiR65D9cjJpwi6uBZRtA a);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_GrWeL1VrS0wkhdYzUnCs1Avec)(NU64 x, NU64 y, NU64 z, NU64 w);
static N_INLINE(NU64, x_ovZf9cj7A2dymlhCrF5nKxAvec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v);
static N_INLINE(NU64, y_ovZf9cj7A2dymlhCrF5nKxA_2vec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v);
static N_INLINE(NU64, z_ovZf9cj7A2dymlhCrF5nKxA_3vec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_9auq9aen9bA2Akw5mYVBwuRhwvec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v, NU64 w);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_6BuDSclx3TBRpan2jd9cKxAvec)(NU64 x, Vec_ogSyGSIJGmYX79bYY4VdDjw* v);
static N_INLINE(NU64, x_HDhVLIY7kmaqFz9cWT9aBVGQvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v);
static N_INLINE(NU64, y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec)(Vec_JPtIiVa2O8jVD51dPzuPOg v);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_e9cpxvMqLgx1PjvIOAUwQuAvec)(Vec_JPtIiVa2O8jVD51dPzuPOg a, Vec_JPtIiVa2O8jVD51dPzuPOg b);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_1xnLhnvXf7YzQWXFe19aLlAvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 z, NU64 w);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_Q9cUS8rjCt4TbePrZM5AkRwvec)(NU64 x, Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 w);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_rlPoLQzvH8lqKdBKyBo30wvec)(NU64 x, NU64 y, Vec_JPtIiVa2O8jVD51dPzuPOg v);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_VFQDdEdkyE2Ecjn9aDO2rugvec)(NU64 x);
static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_Qjgk6TY9cpgaSEMiSOgfxNwvec)(NU64 x, NU64 y, NU64 z);
static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_6j7xupwSOrMWkBlCYEj6Owvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 z);
static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_BWagk1sqCc1Mh43F9blBLxgvec)(NU64 x, Vec_JPtIiVa2O8jVD51dPzuPOg v);
static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_siYglA2MTQt75bwXU1CSOAvec)(NU64 x);
static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_oTkU0M7OoQJSXtokmxvwoQvec)(NU64 x, NU64 y);
static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_j3Jv9czpafI5FYPEN46UFPQvec)(NU64 x);
static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_deX9cXdEInysVazUG6tlv9awvec)(TY_WOK9agWVIFrysHjlc69b06uA a);
static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_M9a7B6s2jAlVh9alyjmi9bZnAvec)(TY_9aCQ9bMIqvRssXzylDx47Csg a);
static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_QlOBaFPMLwcGn4aU5KIi0gvec)(TY_NzKR9bw29cLPrd712Xt6Liiw a);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_eC3NRano6LmxeGc9bEHttyQvec)(NIM_BOOL x, NIM_BOOL y, NIM_BOOL z, NIM_BOOL w);
static N_INLINE(NIM_BOOL, x_41MVP0fO9c9cWxIKdOGILL5Qvec)(Vec_3egAWLIGVBOuRqLSHvHuUA v);
static N_INLINE(NIM_BOOL, y_41MVP0fO9c9cWxIKdOGILL5Q_2vec)(Vec_3egAWLIGVBOuRqLSHvHuUA v);
static N_INLINE(NIM_BOOL, z_41MVP0fO9c9cWxIKdOGILL5Q_3vec)(Vec_3egAWLIGVBOuRqLSHvHuUA v);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_cAUYR3WvsM6G9bT4gQFmDYAvec)(Vec_3egAWLIGVBOuRqLSHvHuUA v, NIM_BOOL w);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_ES6I31oR4faQe9cMM9cUzEYQvec)(NIM_BOOL x, Vec_3egAWLIGVBOuRqLSHvHuUA v);
static N_INLINE(NIM_BOOL, x_DGogPNLU3nmf1QondUB6oQvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v);
static N_INLINE(NIM_BOOL, y_DGogPNLU3nmf1QondUB6oQ_2vec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_eGkH2fTmDAteSNeKx3roTAvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA a, Vec_3DDkv6KTVqOpdZoQMMqqgA b);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_YXff29b74XNZ7xgcVlVzTSwvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL z, NIM_BOOL w);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_26jyt8ZEdgYhV9bt1gWUr9cAvec)(NIM_BOOL x, Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL w);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_29ciMA0W8ns3OfsvITEVOfwvec)(NIM_BOOL x, NIM_BOOL y, Vec_3DDkv6KTVqOpdZoQMMqqgA v);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_CVo9crZhQOqNimy9bR89c7x9cQvec)(NIM_BOOL x);
static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_ZhZCszT9bF21pQlyMf0Tqvwvec)(NIM_BOOL x, NIM_BOOL y, NIM_BOOL z);
static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_Cy3jVB9bxAozg1SCUB8gAyAvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL z);
static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_Y4oob9bbvZNzA2RI4R6wqVwvec)(NIM_BOOL x, Vec_3DDkv6KTVqOpdZoQMMqqgA v);
static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_y16emBQXy745iX68kLDN3wvec)(NIM_BOOL x);
static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_qbTGINqGkVnMoWxivPhACwvec)(NIM_BOOL x, NIM_BOOL y);
static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_aUfhOHDLQxUNs2uFLhJiIQvec)(NIM_BOOL x);
static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_tNHH7LoJ6s19bPtRHT8PNDQvec)(TY_XyV9b4LviDmOhnxKqnZG2Rg a);
static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_E0uD7V1geqlZLPQeJ8NJdgvec)(TY_xSxqoPo7Fj4uIDcWiYyWDg a);
static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_AYUGljxyJsuioieqcIi3IAvec)(TY_Gl9aAKPegYDOYkxLtedgz8w a);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__J7vWjOv59bjwwYcDHMIUtEg_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, yzx_QNKRCIoL02fVO14FHlc10Qvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, zxy_QNKRCIoL02fVO14FHlc10Q_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, minus__btEXTJnnMEuPmjWOn1TWIAvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, Vec_S5njPDIR1N39afJ9a6EQzdbA* u);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, star__btEXTJnnMEuPmjWOn1TWIA_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, Vec_S5njPDIR1N39afJ9a6EQzdbA* u);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_2eASAg1PfVZtHyF9c9buDWsg_3, "len(a) == L string modified while iterating over it", 51);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, spaces_iOxQV89aDy30Iwxtiy0Ox3g)(NI num) {
	NimStringDesc* result;
	nimfr_("spaces", "vec.nim")
	result = (NimStringDesc*)0;
	nimln_(57, "vec.nim");
	result = mnewString(((NI)chckRange(num, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NIM_CHAR* c;
		NI i;
		NI L;
		c = (NIM_CHAR*)0;
		nimln_(3607, "system.nim");
		i = ((NI) 0);
		nimln_(3608, "system.nim");
		nimln_(58, "vec.nim");
		L = (result ? result->Sup.len : 0);
		{
			nimln_(3609, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_2;
				if (!(i < L)) goto LA3;
				nimln_(3610, "system.nim");
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				c = (&result->data[i]);
				nimln_(59, "vec.nim");
				(*c) = 32;
				nimln_(3611, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_2 = addInt(i, ((NI) 1));
				i = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_2);
				nimln_(3612, "system.nim");
				{
					nimln_(58, "vec.nim");
					if (!!(((result ? result->Sup.len : 0) == L))) goto LA6_;
					nimln_(3612, "system.nim");
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_2eASAg1PfVZtHyF9c9buDWsg_3));
				}
				LA6_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NIM_BOOL, growingIndices_9bVN9bVIkj5bKH9c9c8fUPpMQg)(NI* indices, NI indicesLen_0) {
	NIM_BOOL result;
	nimfr_("growingIndices", "vec.nim")
{	result = (NIM_BOOL)0;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(181, "vec.nim");
		colontmp_ = (indicesLen_0-1);
		nimln_(1955, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_5;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1957, "system.nim");
				i = res;
				nimln_(182, "vec.nim");
				{
					NI TM_2eASAg1PfVZtHyF9c9buDWsg_4;
					if ((NU)(i) >= (NU)(indicesLen_0)) raiseIndexError();
					TM_2eASAg1PfVZtHyF9c9buDWsg_4 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_4)) >= (NU)(indicesLen_0)) raiseIndexError();
					if (!(indices[i] <= indices[(NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_4)])) goto LA6_;
					nimln_(183, "vec.nim");
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(1976, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_5);
			} LA3: ;
		}
	}
	nimln_(184, "vec.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, continuousIndices_9bVN9bVIkj5bKH9c9c8fUPpMQg_2)(NI* indices, NI indicesLen_0) {
	NIM_BOOL result;
	nimfr_("continuousIndices", "vec.nim")
{	result = (NIM_BOOL)0;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(187, "vec.nim");
		colontmp_ = (indicesLen_0-1);
		nimln_(1955, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_8;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1957, "system.nim");
				i = res;
				nimln_(188, "vec.nim");
				{
					NI TM_2eASAg1PfVZtHyF9c9buDWsg_6;
					NI TM_2eASAg1PfVZtHyF9c9buDWsg_7;
					nimln_(363, "system.nim");
					nimln_(188, "vec.nim");
					TM_2eASAg1PfVZtHyF9c9buDWsg_6 = subInt(i, ((NI) 1));
					if ((NU)((NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_6)) >= (NU)(indicesLen_0)) raiseIndexError();
					if ((NU)(i) >= (NU)(indicesLen_0)) raiseIndexError();
					TM_2eASAg1PfVZtHyF9c9buDWsg_7 = subInt(indices[i], ((NI) 1));
					if (!!((indices[(NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_6)] == (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_7)))) goto LA6_;
					nimln_(189, "vec.nim");
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(1976, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_8);
			} LA3: ;
		}
	}
	nimln_(190, "vec.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_AaOb1efTPrDJJ9aKeFHEEGwvec)(NF32 x, NF32 y, NF32 z, NF32 w) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(514, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("x", "vec.nim")
	result = (NF32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("y", "vec.nim")
	result = (NF32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("z", "vec.nim")
	result = (NF32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_ITdPzFAfjQ2t9c6sbu9bSPiQvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(515, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_Xbi8c1XUPkUTWFDNj5l5oQvec(v);
	T1_.arr[1] = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(v);
	T1_.arr[2] = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_l49bIJsW4znHbNVu9cWYhQvAvec)(NF32 x, Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(516, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_Xbi8c1XUPkUTWFDNj5l5oQvec(v);
	T1_.arr[2] = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(v);
	T1_.arr[3] = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF32, x_zDAAwBD1pE9bMOlggGBZrqAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v) {
	NF32 result;
	nimfr_("x", "vec.nim")
	result = (NF32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, y_zDAAwBD1pE9bMOlggGBZrqA_2vec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v) {
	NF32 result;
	nimfr_("y", "vec.nim")
	result = (NF32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_tWJoRgTOvCdib459c9bLGPiAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A a, Vec_T08FD1ghD81Hoqk9cM9a5N4A b) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(517, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_zDAAwBD1pE9bMOlggGBZrqAvec(a);
	T1_.arr[1] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(a);
	T1_.arr[2] = x_zDAAwBD1pE9bMOlggGBZrqAvec(b);
	T1_.arr[3] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_vU3MyYZGxYO6Amp2SBffoAvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 z, NF32 w) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(518, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_zDAAwBD1pE9bMOlggGBZrqAvec(v);
	T1_.arr[1] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_vzWI77mO9ar9aaBPt3Tr5rPwvec)(NF32 x, Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 w) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(519, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_zDAAwBD1pE9bMOlggGBZrqAvec(v);
	T1_.arr[2] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_cyZbJYKxLGJZ9blcCHg6F2gvec)(NF32 x, NF32 y, Vec_T08FD1ghD81Hoqk9cM9a5N4A v) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(520, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_zDAAwBD1pE9bMOlggGBZrqAvec(v);
	T1_.arr[3] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_Khepf4d4yzJM7kPke7ANKgvec)(NF32 x) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(521, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_bV33b6rSAdvcVnmP1zcMwQvec)(NF32 x, NF32 y, NF32 z) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(523, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_NYW534GxniLO9bJqYxxpmzgvec)(Vec_T08FD1ghD81Hoqk9cM9a5N4A v, NF32 z) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(524, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_zDAAwBD1pE9bMOlggGBZrqAvec(v);
	T1_.arr[1] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_Dv4TrjtdikkF9cFfcAhqf0Avec)(NF32 x, Vec_T08FD1ghD81Hoqk9cM9a5N4A v) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(525, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_zDAAwBD1pE9bMOlggGBZrqAvec(v);
	T1_.arr[2] = y_zDAAwBD1pE9bMOlggGBZrqA_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_o9cnKbmHtoD9cX358Njdry0Qvec)(NF32 x) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(526, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_bFH2VqQFdPukth3adfquxAvec)(NF32 x, NF32 y) {
	Vec_T08FD1ghD81Hoqk9cM9a5N4A result;
	Vec_T08FD1ghD81Hoqk9cM9a5N4A T1_;
	nimfr_("vec2f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(528, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_TIW76y9cHjQuPEz9bE78Uglwvec)(NF32 x) {
	Vec_T08FD1ghD81Hoqk9cM9a5N4A result;
	Vec_T08FD1ghD81Hoqk9cM9a5N4A T1_;
	nimfr_("vec2f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(529, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4f_TjdOKcRkin72vGwAIL9cxtQvec)(TY_9aTCwbdg1cSQimdVd0OEKVw a) {
	Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(531, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3f_SCOt9bvN5yHI9c551LYoeAvAvec)(TY_mXNbtvWKAiZn9bWV4uCjiKg a) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(532, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_T08FD1ghD81Hoqk9cM9a5N4A, vec2f_iYY8nGAxCDd6HN9aNlvpmugvec)(TY_4YxcnnI8do9a6vmNKtzdSKw a) {
	Vec_T08FD1ghD81Hoqk9cM9a5N4A result;
	Vec_T08FD1ghD81Hoqk9cM9a5N4A T1_;
	nimfr_("vec2f", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(533, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_sDUnYkRwC2Xp9c9cl1DVimlAvec)(NF x, NF y, NF z, NF w) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(535, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF, x_NpfOyWKi6CLtEhMWqkmyuQvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("x", "vec.nim")
	result = (NF)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF, y_NpfOyWKi6CLtEhMWqkmyuQ_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("y", "vec.nim")
	result = (NF)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF, z_NpfOyWKi6CLtEhMWqkmyuQ_3vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("z", "vec.nim")
	result = (NF)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_iba43GbOddIV9cfpsmLmkOQvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, NF w) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(536, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_NpfOyWKi6CLtEhMWqkmyuQvec(v);
	T1_.arr[1] = y_NpfOyWKi6CLtEhMWqkmyuQ_2vec(v);
	T1_.arr[2] = z_NpfOyWKi6CLtEhMWqkmyuQ_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_8s9bhmCa1wTfJuEjaBtskVAvec)(NF x, Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(537, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_NpfOyWKi6CLtEhMWqkmyuQvec(v);
	T1_.arr[2] = y_NpfOyWKi6CLtEhMWqkmyuQ_2vec(v);
	T1_.arr[3] = z_NpfOyWKi6CLtEhMWqkmyuQ_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF, x_6EIz8NT1pb4kvVGUAxuB5Qvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v) {
	NF result;
	nimfr_("x", "vec.nim")
	result = (NF)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF, y_6EIz8NT1pb4kvVGUAxuB5Q_2vec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v) {
	NF result;
	nimfr_("y", "vec.nim")
	result = (NF)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_6oTAdrLRLyFdtnA8a43AFQvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ a, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ b) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(538, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(a);
	T1_.arr[1] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(a);
	T1_.arr[2] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(b);
	T1_.arr[3] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_bvHwbWJsrhsHw9c9ckzMpmOgvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF z, NF w) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(539, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(v);
	T1_.arr[1] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_kPwRwj66TdDoMp9bLGRd2Xwvec)(NF x, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF w) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(540, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(v);
	T1_.arr[2] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_ubfs1KKV5Avgcz3cMB89b7Qvec)(NF x, NF y, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(541, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(v);
	T1_.arr[3] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ajluWiFZ8tTU9b0kwuUOFAQ, vec4d_B88KGA6RXe7bcCjHv6cuZwvec)(NF x) {
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	nimfr_("vec4d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(542, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_ttKlGVy9ccAyQnjUSeKaLlAvec)(NF x, NF y, NF z) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("vec3d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(544, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_jOvX55ePQ6hYtNMnaPxjSQvec)(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v, NF z) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("vec3d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(545, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(v);
	T1_.arr[1] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_l78qgNlE5JqtGC23qXk9aXQvec)(NF x, Vec_qy9aZB04gHVo2Fdc9cBiC1lQ v) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("vec3d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(546, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_6EIz8NT1pb4kvVGUAxuB5Qvec(v);
	T1_.arr[2] = y_6EIz8NT1pb4kvVGUAxuB5Q_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, vec3d_Z8CAV18F7TJpju4rhYgsGQvec)(NF x) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("vec3d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(547, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ, vec2d_Ai8R9cfJd6oFQs9b4Sm0xuggvec)(NF x, NF y) {
	Vec_qy9aZB04gHVo2Fdc9cBiC1lQ result;
	Vec_qy9aZB04gHVo2Fdc9cBiC1lQ T1_;
	nimfr_("vec2d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(549, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qy9aZB04gHVo2Fdc9cBiC1lQ, vec2d_1yEH1G0DugRdybqO6hUPFQvec)(NF x) {
	Vec_qy9aZB04gHVo2Fdc9cBiC1lQ result;
	Vec_qy9aZB04gHVo2Fdc9cBiC1lQ T1_;
	nimfr_("vec2d", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(550, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_X6X5LukS9aIiwrjghuzjuXAvec)(NI32 x, NI32 y, NI32 z, NI32 w) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(553, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI32, x_9abzu6AHoUHvgfo6kuWMirwvec)(Vec_1NKXb6ubeY6FA7tob82PEQ v) {
	NI32 result;
	nimfr_("x", "vec.nim")
	result = (NI32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI32, y_9abzu6AHoUHvgfo6kuWMirw_2vec)(Vec_1NKXb6ubeY6FA7tob82PEQ v) {
	NI32 result;
	nimfr_("y", "vec.nim")
	result = (NI32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI32, z_9abzu6AHoUHvgfo6kuWMirw_3vec)(Vec_1NKXb6ubeY6FA7tob82PEQ v) {
	NI32 result;
	nimfr_("z", "vec.nim")
	result = (NI32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_CVQV8M9a3oPfD2HXtAPOegAvec)(Vec_1NKXb6ubeY6FA7tob82PEQ v, NI32 w) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(554, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_9abzu6AHoUHvgfo6kuWMirwvec(v);
	T1_.arr[1] = y_9abzu6AHoUHvgfo6kuWMirw_2vec(v);
	T1_.arr[2] = z_9abzu6AHoUHvgfo6kuWMirw_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_N9chL8qiyGW9au9b6Dd1kZU8Qvec)(NI32 x, Vec_1NKXb6ubeY6FA7tob82PEQ v) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(555, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_9abzu6AHoUHvgfo6kuWMirwvec(v);
	T1_.arr[2] = y_9abzu6AHoUHvgfo6kuWMirw_2vec(v);
	T1_.arr[3] = z_9abzu6AHoUHvgfo6kuWMirw_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI32, x_granXNW4Q9bETey6wYbJ9czwvec)(Vec_9aKb06UE086D5CCUfGRTkCw v) {
	NI32 result;
	nimfr_("x", "vec.nim")
	result = (NI32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI32, y_granXNW4Q9bETey6wYbJ9czw_2vec)(Vec_9aKb06UE086D5CCUfGRTkCw v) {
	NI32 result;
	nimfr_("y", "vec.nim")
	result = (NI32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_2vwXJLsoe0Pn8cgPwt1r1Avec)(Vec_9aKb06UE086D5CCUfGRTkCw a, Vec_9aKb06UE086D5CCUfGRTkCw b) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(556, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_granXNW4Q9bETey6wYbJ9czwvec(a);
	T1_.arr[1] = y_granXNW4Q9bETey6wYbJ9czw_2vec(a);
	T1_.arr[2] = x_granXNW4Q9bETey6wYbJ9czwvec(b);
	T1_.arr[3] = y_granXNW4Q9bETey6wYbJ9czw_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_WCHDuUozRS9bnBHO4NccroAvec)(Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 z, NI32 w) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(557, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_granXNW4Q9bETey6wYbJ9czwvec(v);
	T1_.arr[1] = y_granXNW4Q9bETey6wYbJ9czw_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_lzxGnsjqFlTOyJY3Jvi9byAvec)(NI32 x, Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 w) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(558, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_granXNW4Q9bETey6wYbJ9czwvec(v);
	T1_.arr[2] = y_granXNW4Q9bETey6wYbJ9czw_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_6E0z2oi3O0TPpAEEp6cfgwvec)(NI32 x, NI32 y, Vec_9aKb06UE086D5CCUfGRTkCw v) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(559, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_granXNW4Q9bETey6wYbJ9czwvec(v);
	T1_.arr[3] = y_granXNW4Q9bETey6wYbJ9czw_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_rxCLDgjdv9c6hQnd3Jrz9cOAvec)(NI32 x) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(560, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_wieUAPz85YKb2uA5QSPC0Avec)(NI32 x, NI32 y, NI32 z) {
	Vec_1NKXb6ubeY6FA7tob82PEQ result;
	Vec_1NKXb6ubeY6FA7tob82PEQ T1_;
	nimfr_("vec3i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(562, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_kaW0ejb6ttcEyeP8PdvHmwvec)(Vec_9aKb06UE086D5CCUfGRTkCw v, NI32 z) {
	Vec_1NKXb6ubeY6FA7tob82PEQ result;
	Vec_1NKXb6ubeY6FA7tob82PEQ T1_;
	nimfr_("vec3i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(563, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_granXNW4Q9bETey6wYbJ9czwvec(v);
	T1_.arr[1] = y_granXNW4Q9bETey6wYbJ9czw_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_wCyztboNbIy1S0BFYBxqhgvec)(NI32 x, Vec_9aKb06UE086D5CCUfGRTkCw v) {
	Vec_1NKXb6ubeY6FA7tob82PEQ result;
	Vec_1NKXb6ubeY6FA7tob82PEQ T1_;
	nimfr_("vec3i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(564, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_granXNW4Q9bETey6wYbJ9czwvec(v);
	T1_.arr[2] = y_granXNW4Q9bETey6wYbJ9czw_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_focre0WM1e8tb9aLqDI9bPPgvec)(NI32 x) {
	Vec_1NKXb6ubeY6FA7tob82PEQ result;
	Vec_1NKXb6ubeY6FA7tob82PEQ T1_;
	nimfr_("vec3i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(565, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_I7t0dID7Vdxmhyv4KFBlZAvec)(NI32 x, NI32 y) {
	Vec_9aKb06UE086D5CCUfGRTkCw result;
	Vec_9aKb06UE086D5CCUfGRTkCw T1_;
	nimfr_("vec2i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(567, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_etsrHeuexMmJjbA4LBcr1Avec)(NI32 x) {
	Vec_9aKb06UE086D5CCUfGRTkCw result;
	Vec_9aKb06UE086D5CCUfGRTkCw T1_;
	nimfr_("vec2i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(568, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_qoh4I3S7szDtqndE7w821A, vec4i_S5Nm9ayKelhGyoY9c9bAHunvAvec)(TY_7pxmxukJp9aDJpjDIdzM2gw a) {
	Vec_qoh4I3S7szDtqndE7w821A result;
	Vec_qoh4I3S7szDtqndE7w821A T1_;
	nimfr_("vec4i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(570, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_1NKXb6ubeY6FA7tob82PEQ, vec3i_zEnl3I1aW1KKJrNM0z9cRZgvec)(TY_0v3OTtI03bagPhcjf9byD9bA a) {
	Vec_1NKXb6ubeY6FA7tob82PEQ result;
	Vec_1NKXb6ubeY6FA7tob82PEQ T1_;
	nimfr_("vec3i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(571, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aKb06UE086D5CCUfGRTkCw, vec2i_JiPWCM1bTIdjBfFfJlxtfQvec)(TY_9aCDQwgHopxUvI9buP3ce7ZQ a) {
	Vec_9aKb06UE086D5CCUfGRTkCw result;
	Vec_9aKb06UE086D5CCUfGRTkCw T1_;
	nimfr_("vec2i", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(572, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_YhEDdvhDE3kJdtR2QIg1RQvec)(NI64 x, NI64 y, NI64 z, NI64 w) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(574, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI64, x_q1teFDm9byIkhYlelQKQnXgvec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v) {
	NI64 result;
	nimfr_("x", "vec.nim")
	result = (NI64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI64, y_q1teFDm9byIkhYlelQKQnXg_2vec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v) {
	NI64 result;
	nimfr_("y", "vec.nim")
	result = (NI64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI64, z_q1teFDm9byIkhYlelQKQnXg_3vec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v) {
	NI64 result;
	nimfr_("z", "vec.nim")
	result = (NI64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_x9cbBuGnpdR8cb9brbibxU9aAvec)(Vec_iIbuLPPEYFaqJVU7HL38lg* v, NI64 w) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(575, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_q1teFDm9byIkhYlelQKQnXgvec(v);
	T1_.arr[1] = y_q1teFDm9byIkhYlelQKQnXg_2vec(v);
	T1_.arr[2] = z_q1teFDm9byIkhYlelQKQnXg_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_TTH5hM0JlnZIJR9cXaiL8MAvec)(NI64 x, Vec_iIbuLPPEYFaqJVU7HL38lg* v) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(576, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_q1teFDm9byIkhYlelQKQnXgvec(v);
	T1_.arr[2] = y_q1teFDm9byIkhYlelQKQnXg_2vec(v);
	T1_.arr[3] = z_q1teFDm9byIkhYlelQKQnXg_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI64, x_UNLP2bIcV49bVQP7rqRrPNwvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v) {
	NI64 result;
	nimfr_("x", "vec.nim")
	result = (NI64)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NI64, y_UNLP2bIcV49bVQP7rqRrPNw_2vec)(Vec_xvhdgGTJojI5JMPWZZjAUA v) {
	NI64 result;
	nimfr_("y", "vec.nim")
	result = (NI64)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_P9bjd9a9bP4k0nYI0VuUSwfqQvec)(Vec_xvhdgGTJojI5JMPWZZjAUA a, Vec_xvhdgGTJojI5JMPWZZjAUA b) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(577, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_UNLP2bIcV49bVQP7rqRrPNwvec(a);
	T1_.arr[1] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(a);
	T1_.arr[2] = x_UNLP2bIcV49bVQP7rqRrPNwvec(b);
	T1_.arr[3] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_RPJjI9aOFdCK7NULT9bWN0eQvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 z, NI64 w) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(578, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_UNLP2bIcV49bVQP7rqRrPNwvec(v);
	T1_.arr[1] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_aVBKSA4OoP9aDfQS8QrglKQvec)(NI64 x, Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 w) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(579, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_UNLP2bIcV49bVQP7rqRrPNwvec(v);
	T1_.arr[2] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_AT01ZZFeTfOXecaBLSsmVwvec)(NI64 x, NI64 y, Vec_xvhdgGTJojI5JMPWZZjAUA v) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(580, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_UNLP2bIcV49bVQP7rqRrPNwvec(v);
	T1_.arr[3] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_ZwAtJlu9c71EPotrsrf8DQgvec)(NI64 x) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(581, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_z1Nr9aR4CiBIDeigtktwgFAvec)(NI64 x, NI64 y, NI64 z) {
	Vec_iIbuLPPEYFaqJVU7HL38lg result;
	Vec_iIbuLPPEYFaqJVU7HL38lg T1_;
	nimfr_("vec3l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(583, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_4vRAl8qbmW80G8sVu69aDXgvec)(Vec_xvhdgGTJojI5JMPWZZjAUA v, NI64 z) {
	Vec_iIbuLPPEYFaqJVU7HL38lg result;
	Vec_iIbuLPPEYFaqJVU7HL38lg T1_;
	nimfr_("vec3l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(584, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_UNLP2bIcV49bVQP7rqRrPNwvec(v);
	T1_.arr[1] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_F1xM3Epey9b8TNIYAFi9cwjQvec)(NI64 x, Vec_xvhdgGTJojI5JMPWZZjAUA v) {
	Vec_iIbuLPPEYFaqJVU7HL38lg result;
	Vec_iIbuLPPEYFaqJVU7HL38lg T1_;
	nimfr_("vec3l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(585, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_UNLP2bIcV49bVQP7rqRrPNwvec(v);
	T1_.arr[2] = y_UNLP2bIcV49bVQP7rqRrPNw_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_IH1IP3SWejU3lXJRkZYVegvec)(NI64 x) {
	Vec_iIbuLPPEYFaqJVU7HL38lg result;
	Vec_iIbuLPPEYFaqJVU7HL38lg T1_;
	nimfr_("vec3l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(586, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_Q9bqjFwhGOb9ao2xKr1uyluAvec)(NI64 x, NI64 y) {
	Vec_xvhdgGTJojI5JMPWZZjAUA result;
	Vec_xvhdgGTJojI5JMPWZZjAUA T1_;
	nimfr_("vec2l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(588, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_s6rEBDvBdKwr5nFgrexf1Avec)(NI64 x) {
	Vec_xvhdgGTJojI5JMPWZZjAUA result;
	Vec_xvhdgGTJojI5JMPWZZjAUA T1_;
	nimfr_("vec2l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(589, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aAA0mkLUcOpqzQWa0X35lQ, vec4l_YKZC49cuUmCYUj6JYi5VbjQvec)(TY_H75eOnX1DhNAJQlsu1XRUQ a) {
	Vec_9aAA0mkLUcOpqzQWa0X35lQ result;
	Vec_9aAA0mkLUcOpqzQWa0X35lQ T1_;
	nimfr_("vec4l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(591, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_iIbuLPPEYFaqJVU7HL38lg, vec3l_EEehEk9adil9aQUwK03Whr5wvec)(TY_c1FRN1mZ4GK3unahWR0Nyg a) {
	Vec_iIbuLPPEYFaqJVU7HL38lg result;
	Vec_iIbuLPPEYFaqJVU7HL38lg T1_;
	nimfr_("vec3l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(592, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_xvhdgGTJojI5JMPWZZjAUA, vec2l_sFC3D6sNc8XjOl9bhxvu9cCwvec)(TY_EawPLnQhPqWwYm5GdCoh8A a) {
	Vec_xvhdgGTJojI5JMPWZZjAUA result;
	Vec_xvhdgGTJojI5JMPWZZjAUA T1_;
	nimfr_("vec2l", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(593, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_rtgpg3HEX4J7tZ3SCOyEcwvec)(NU32 x, NU32 y, NU32 z, NU32 w) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(596, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NU32, x_MnLL7WHAMLuZH25EuK8yswvec)(Vec_9aztRZVEL2VMPS9atezTlYcA v) {
	NU32 result;
	nimfr_("x", "vec.nim")
	result = (NU32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU32, y_MnLL7WHAMLuZH25EuK8ysw_2vec)(Vec_9aztRZVEL2VMPS9atezTlYcA v) {
	NU32 result;
	nimfr_("y", "vec.nim")
	result = (NU32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU32, z_MnLL7WHAMLuZH25EuK8ysw_3vec)(Vec_9aztRZVEL2VMPS9atezTlYcA v) {
	NU32 result;
	nimfr_("z", "vec.nim")
	result = (NU32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_jRlDePLsD9bmeBkH8U7F9bawvec)(Vec_9aztRZVEL2VMPS9atezTlYcA v, NU32 w) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(597, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_MnLL7WHAMLuZH25EuK8yswvec(v);
	T1_.arr[1] = y_MnLL7WHAMLuZH25EuK8ysw_2vec(v);
	T1_.arr[2] = z_MnLL7WHAMLuZH25EuK8ysw_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_dtUOpBvc31I4vrliR9aNPUAvec)(NU32 x, Vec_9aztRZVEL2VMPS9atezTlYcA v) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(598, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_MnLL7WHAMLuZH25EuK8yswvec(v);
	T1_.arr[2] = y_MnLL7WHAMLuZH25EuK8ysw_2vec(v);
	T1_.arr[3] = z_MnLL7WHAMLuZH25EuK8ysw_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NU32, x_CGzhTgz7EE4N8yRTH9cUB0wvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v) {
	NU32 result;
	nimfr_("x", "vec.nim")
	result = (NU32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU32, y_CGzhTgz7EE4N8yRTH9cUB0w_2vec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v) {
	NU32 result;
	nimfr_("y", "vec.nim")
	result = (NU32)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_soFOY1FlOue8eFEp0bBE3Qvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA a, Vec_BqKjkNSpfyUs9bcQiwYWOiA b) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(599, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(a);
	T1_.arr[1] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(a);
	T1_.arr[2] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(b);
	T1_.arr[3] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_tEWtZH5m8AJW86bWi4RAaQvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 z, NU32 w) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(600, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(v);
	T1_.arr[1] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_B34I9c9aiXP9cSmSH9axfaRgMgvec)(NU32 x, Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 w) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(601, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(v);
	T1_.arr[2] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_GXY3SbgHzWbDm6nJbtJDNQvec)(NU32 x, NU32 y, Vec_BqKjkNSpfyUs9bcQiwYWOiA v) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(602, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(v);
	T1_.arr[3] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_p3I9bmmDOb9beJfFZR4tAVQQvec)(NU32 x) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(603, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_AtEKxaA9aBANHq26Oik7O9cgvec)(NU32 x, NU32 y, NU32 z) {
	Vec_9aztRZVEL2VMPS9atezTlYcA result;
	Vec_9aztRZVEL2VMPS9atezTlYcA T1_;
	nimfr_("vec3ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(605, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_OGFxDeHVdCRhetacjSVAVwvec)(Vec_BqKjkNSpfyUs9bcQiwYWOiA v, NU32 z) {
	Vec_9aztRZVEL2VMPS9atezTlYcA result;
	Vec_9aztRZVEL2VMPS9atezTlYcA T1_;
	nimfr_("vec3ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(606, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(v);
	T1_.arr[1] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_s9bbJ6wlwFQaRp9aaahy2DPQvec)(NU32 x, Vec_BqKjkNSpfyUs9bcQiwYWOiA v) {
	Vec_9aztRZVEL2VMPS9atezTlYcA result;
	Vec_9aztRZVEL2VMPS9atezTlYcA T1_;
	nimfr_("vec3ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(607, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_CGzhTgz7EE4N8yRTH9cUB0wvec(v);
	T1_.arr[2] = y_CGzhTgz7EE4N8yRTH9cUB0w_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_0iMHZIqTmE9brxzSf8fYEvgvec)(NU32 x) {
	Vec_9aztRZVEL2VMPS9atezTlYcA result;
	Vec_9aztRZVEL2VMPS9atezTlYcA T1_;
	nimfr_("vec3ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(608, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_FzkGFeyd5u1oeVxLG4Y6Ogvec)(NU32 x, NU32 y) {
	Vec_BqKjkNSpfyUs9bcQiwYWOiA result;
	Vec_BqKjkNSpfyUs9bcQiwYWOiA T1_;
	nimfr_("vec2ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(610, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_FuvuACF9avqhdvfe4LuG7qAvec)(NU32 x) {
	Vec_BqKjkNSpfyUs9bcQiwYWOiA result;
	Vec_BqKjkNSpfyUs9bcQiwYWOiA T1_;
	nimfr_("vec2ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(611, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_cO7UTx7dC4Be7bYZfqim4A, vec4ui_UCDoYRNrLZThX9bKa7AD4Ogvec)(TY_FleBT9cC2nxhgiXmSYYnEKA a) {
	Vec_cO7UTx7dC4Be7bYZfqim4A result;
	Vec_cO7UTx7dC4Be7bYZfqim4A T1_;
	nimfr_("vec4ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(613, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_9aztRZVEL2VMPS9atezTlYcA, vec3ui_afcqvUW7BspOn5R7R9co8zQvec)(TY_gTZlS3AoaORR9c8ta0HwzwQ a) {
	Vec_9aztRZVEL2VMPS9atezTlYcA result;
	Vec_9aztRZVEL2VMPS9atezTlYcA T1_;
	nimfr_("vec3ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(614, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_BqKjkNSpfyUs9bcQiwYWOiA, vec2ui_GvTec6R3XAFCn0M4tnwhRwvec)(TY_JlnxiR65D9cjJpwi6uBZRtA a) {
	Vec_BqKjkNSpfyUs9bcQiwYWOiA result;
	Vec_BqKjkNSpfyUs9bcQiwYWOiA T1_;
	nimfr_("vec2ui", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(615, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_GrWeL1VrS0wkhdYzUnCs1Avec)(NU64 x, NU64 y, NU64 z, NU64 w) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(617, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NU64, x_ovZf9cj7A2dymlhCrF5nKxAvec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v) {
	NU64 result;
	nimfr_("x", "vec.nim")
	result = (NU64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU64, y_ovZf9cj7A2dymlhCrF5nKxA_2vec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v) {
	NU64 result;
	nimfr_("y", "vec.nim")
	result = (NU64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU64, z_ovZf9cj7A2dymlhCrF5nKxA_3vec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v) {
	NU64 result;
	nimfr_("z", "vec.nim")
	result = (NU64)0;
	nimln_(259, "vec.nim");
	result = (*v).arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_9auq9aen9bA2Akw5mYVBwuRhwvec)(Vec_ogSyGSIJGmYX79bYY4VdDjw* v, NU64 w) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(618, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_ovZf9cj7A2dymlhCrF5nKxAvec(v);
	T1_.arr[1] = y_ovZf9cj7A2dymlhCrF5nKxA_2vec(v);
	T1_.arr[2] = z_ovZf9cj7A2dymlhCrF5nKxA_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_6BuDSclx3TBRpan2jd9cKxAvec)(NU64 x, Vec_ogSyGSIJGmYX79bYY4VdDjw* v) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(619, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_ovZf9cj7A2dymlhCrF5nKxAvec(v);
	T1_.arr[2] = y_ovZf9cj7A2dymlhCrF5nKxA_2vec(v);
	T1_.arr[3] = z_ovZf9cj7A2dymlhCrF5nKxA_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NU64, x_HDhVLIY7kmaqFz9cWT9aBVGQvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v) {
	NU64 result;
	nimfr_("x", "vec.nim")
	result = (NU64)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NU64, y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec)(Vec_JPtIiVa2O8jVD51dPzuPOg v) {
	NU64 result;
	nimfr_("y", "vec.nim")
	result = (NU64)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_e9cpxvMqLgx1PjvIOAUwQuAvec)(Vec_JPtIiVa2O8jVD51dPzuPOg a, Vec_JPtIiVa2O8jVD51dPzuPOg b) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(620, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(a);
	T1_.arr[1] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(a);
	T1_.arr[2] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(b);
	T1_.arr[3] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_1xnLhnvXf7YzQWXFe19aLlAvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 z, NU64 w) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(621, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(v);
	T1_.arr[1] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_Q9cUS8rjCt4TbePrZM5AkRwvec)(NU64 x, Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 w) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(622, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(v);
	T1_.arr[2] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_rlPoLQzvH8lqKdBKyBo30wvec)(NU64 x, NU64 y, Vec_JPtIiVa2O8jVD51dPzuPOg v) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(623, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(v);
	T1_.arr[3] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_VFQDdEdkyE2Ecjn9aDO2rugvec)(NU64 x) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(624, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_Qjgk6TY9cpgaSEMiSOgfxNwvec)(NU64 x, NU64 y, NU64 z) {
	Vec_ogSyGSIJGmYX79bYY4VdDjw result;
	Vec_ogSyGSIJGmYX79bYY4VdDjw T1_;
	nimfr_("vec3ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(626, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_6j7xupwSOrMWkBlCYEj6Owvec)(Vec_JPtIiVa2O8jVD51dPzuPOg v, NU64 z) {
	Vec_ogSyGSIJGmYX79bYY4VdDjw result;
	Vec_ogSyGSIJGmYX79bYY4VdDjw T1_;
	nimfr_("vec3ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(627, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(v);
	T1_.arr[1] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_BWagk1sqCc1Mh43F9blBLxgvec)(NU64 x, Vec_JPtIiVa2O8jVD51dPzuPOg v) {
	Vec_ogSyGSIJGmYX79bYY4VdDjw result;
	Vec_ogSyGSIJGmYX79bYY4VdDjw T1_;
	nimfr_("vec3ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(628, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_HDhVLIY7kmaqFz9cWT9aBVGQvec(v);
	T1_.arr[2] = y_HDhVLIY7kmaqFz9cWT9aBVGQ_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_siYglA2MTQt75bwXU1CSOAvec)(NU64 x) {
	Vec_ogSyGSIJGmYX79bYY4VdDjw result;
	Vec_ogSyGSIJGmYX79bYY4VdDjw T1_;
	nimfr_("vec3ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(629, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_oTkU0M7OoQJSXtokmxvwoQvec)(NU64 x, NU64 y) {
	Vec_JPtIiVa2O8jVD51dPzuPOg result;
	Vec_JPtIiVa2O8jVD51dPzuPOg T1_;
	nimfr_("vec2ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(631, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_j3Jv9czpafI5FYPEN46UFPQvec)(NU64 x) {
	Vec_JPtIiVa2O8jVD51dPzuPOg result;
	Vec_JPtIiVa2O8jVD51dPzuPOg T1_;
	nimfr_("vec2ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(632, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_e9cK0Tq83JFPJqJIfZRZyhA, vec4ul_deX9cXdEInysVazUG6tlv9awvec)(TY_WOK9agWVIFrysHjlc69b06uA a) {
	Vec_e9cK0Tq83JFPJqJIfZRZyhA result;
	Vec_e9cK0Tq83JFPJqJIfZRZyhA T1_;
	nimfr_("vec4ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(634, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_ogSyGSIJGmYX79bYY4VdDjw, vec3ul_M9a7B6s2jAlVh9alyjmi9bZnAvec)(TY_9aCQ9bMIqvRssXzylDx47Csg a) {
	Vec_ogSyGSIJGmYX79bYY4VdDjw result;
	Vec_ogSyGSIJGmYX79bYY4VdDjw T1_;
	nimfr_("vec3ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(635, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_JPtIiVa2O8jVD51dPzuPOg, vec2ul_QlOBaFPMLwcGn4aU5KIi0gvec)(TY_NzKR9bw29cLPrd712Xt6Liiw a) {
	Vec_JPtIiVa2O8jVD51dPzuPOg result;
	Vec_JPtIiVa2O8jVD51dPzuPOg T1_;
	nimfr_("vec2ul", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(636, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_eC3NRano6LmxeGc9bEHttyQvec)(NIM_BOOL x, NIM_BOOL y, NIM_BOOL z, NIM_BOOL w) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(639, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, x_41MVP0fO9c9cWxIKdOGILL5Qvec)(Vec_3egAWLIGVBOuRqLSHvHuUA v) {
	NIM_BOOL result;
	nimfr_("x", "vec.nim")
	result = (NIM_BOOL)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, y_41MVP0fO9c9cWxIKdOGILL5Q_2vec)(Vec_3egAWLIGVBOuRqLSHvHuUA v) {
	NIM_BOOL result;
	nimfr_("y", "vec.nim")
	result = (NIM_BOOL)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, z_41MVP0fO9c9cWxIKdOGILL5Q_3vec)(Vec_3egAWLIGVBOuRqLSHvHuUA v) {
	NIM_BOOL result;
	nimfr_("z", "vec.nim")
	result = (NIM_BOOL)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_cAUYR3WvsM6G9bT4gQFmDYAvec)(Vec_3egAWLIGVBOuRqLSHvHuUA v, NIM_BOOL w) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(640, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_41MVP0fO9c9cWxIKdOGILL5Qvec(v);
	T1_.arr[1] = y_41MVP0fO9c9cWxIKdOGILL5Q_2vec(v);
	T1_.arr[2] = z_41MVP0fO9c9cWxIKdOGILL5Q_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_ES6I31oR4faQe9cMM9cUzEYQvec)(NIM_BOOL x, Vec_3egAWLIGVBOuRqLSHvHuUA v) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(641, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_41MVP0fO9c9cWxIKdOGILL5Qvec(v);
	T1_.arr[2] = y_41MVP0fO9c9cWxIKdOGILL5Q_2vec(v);
	T1_.arr[3] = z_41MVP0fO9c9cWxIKdOGILL5Q_3vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, x_DGogPNLU3nmf1QondUB6oQvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v) {
	NIM_BOOL result;
	nimfr_("x", "vec.nim")
	result = (NIM_BOOL)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, y_DGogPNLU3nmf1QondUB6oQ_2vec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v) {
	NIM_BOOL result;
	nimfr_("y", "vec.nim")
	result = (NIM_BOOL)0;
	nimln_(259, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_eGkH2fTmDAteSNeKx3roTAvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA a, Vec_3DDkv6KTVqOpdZoQMMqqgA b) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(642, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_DGogPNLU3nmf1QondUB6oQvec(a);
	T1_.arr[1] = y_DGogPNLU3nmf1QondUB6oQ_2vec(a);
	T1_.arr[2] = x_DGogPNLU3nmf1QondUB6oQvec(b);
	T1_.arr[3] = y_DGogPNLU3nmf1QondUB6oQ_2vec(b);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_YXff29b74XNZ7xgcVlVzTSwvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL z, NIM_BOOL w) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(643, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_DGogPNLU3nmf1QondUB6oQvec(v);
	T1_.arr[1] = y_DGogPNLU3nmf1QondUB6oQ_2vec(v);
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_26jyt8ZEdgYhV9bt1gWUr9cAvec)(NIM_BOOL x, Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL w) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(644, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_DGogPNLU3nmf1QondUB6oQvec(v);
	T1_.arr[2] = y_DGogPNLU3nmf1QondUB6oQ_2vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_29ciMA0W8ns3OfsvITEVOfwvec)(NIM_BOOL x, NIM_BOOL y, Vec_3DDkv6KTVqOpdZoQMMqqgA v) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(645, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = x_DGogPNLU3nmf1QondUB6oQvec(v);
	T1_.arr[3] = y_DGogPNLU3nmf1QondUB6oQ_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_CVo9crZhQOqNimy9bR89c7x9cQvec)(NIM_BOOL x) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(646, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	T1_.arr[3] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_ZhZCszT9bF21pQlyMf0Tqvwvec)(NIM_BOOL x, NIM_BOOL y, NIM_BOOL z) {
	Vec_3egAWLIGVBOuRqLSHvHuUA result;
	Vec_3egAWLIGVBOuRqLSHvHuUA T1_;
	nimfr_("vec3b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(648, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_Cy3jVB9bxAozg1SCUB8gAyAvec)(Vec_3DDkv6KTVqOpdZoQMMqqgA v, NIM_BOOL z) {
	Vec_3egAWLIGVBOuRqLSHvHuUA result;
	Vec_3egAWLIGVBOuRqLSHvHuUA T1_;
	nimfr_("vec3b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(649, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_DGogPNLU3nmf1QondUB6oQvec(v);
	T1_.arr[1] = y_DGogPNLU3nmf1QondUB6oQ_2vec(v);
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_Y4oob9bbvZNzA2RI4R6wqVwvec)(NIM_BOOL x, Vec_3DDkv6KTVqOpdZoQMMqqgA v) {
	Vec_3egAWLIGVBOuRqLSHvHuUA result;
	Vec_3egAWLIGVBOuRqLSHvHuUA T1_;
	nimfr_("vec3b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(650, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x_DGogPNLU3nmf1QondUB6oQvec(v);
	T1_.arr[2] = y_DGogPNLU3nmf1QondUB6oQ_2vec(v);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_y16emBQXy745iX68kLDN3wvec)(NIM_BOOL x) {
	Vec_3egAWLIGVBOuRqLSHvHuUA result;
	Vec_3egAWLIGVBOuRqLSHvHuUA T1_;
	nimfr_("vec3b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(651, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	T1_.arr[2] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_qbTGINqGkVnMoWxivPhACwvec)(NIM_BOOL x, NIM_BOOL y) {
	Vec_3DDkv6KTVqOpdZoQMMqqgA result;
	Vec_3DDkv6KTVqOpdZoQMMqqgA T1_;
	nimfr_("vec2b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(653, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_aUfhOHDLQxUNs2uFLhJiIQvec)(NIM_BOOL x) {
	Vec_3DDkv6KTVqOpdZoQMMqqgA result;
	Vec_3DDkv6KTVqOpdZoQMMqqgA T1_;
	nimfr_("vec2b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(654, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = x;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_WQ9bEBJLif1zK31OfAoIxvg, vec4b_tNHH7LoJ6s19bPtRHT8PNDQvec)(TY_XyV9b4LviDmOhnxKqnZG2Rg a) {
	Vec_WQ9bEBJLif1zK31OfAoIxvg result;
	Vec_WQ9bEBJLif1zK31OfAoIxvg T1_;
	nimfr_("vec4b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(656, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	T1_.arr[3] = a[(((NI) 3))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3egAWLIGVBOuRqLSHvHuUA, vec3b_E0uD7V1geqlZLPQeJ8NJdgvec)(TY_xSxqoPo7Fj4uIDcWiYyWDg a) {
	Vec_3egAWLIGVBOuRqLSHvHuUA result;
	Vec_3egAWLIGVBOuRqLSHvHuUA T1_;
	nimfr_("vec3b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(657, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	T1_.arr[2] = a[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_3DDkv6KTVqOpdZoQMMqqgA, vec2b_AYUGljxyJsuioieqcIi3IAvec)(TY_Gl9aAKPegYDOYkxLtedgz8w a) {
	Vec_3DDkv6KTVqOpdZoQMMqqgA result;
	Vec_3DDkv6KTVqOpdZoQMMqqgA T1_;
	nimfr_("vec2b", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(658, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = a[(((NI) 0))- 0];
	T1_.arr[1] = a[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("-", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3772, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_9;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3774, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(111, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) - (NF32)(u.arr[(ii)- 0]));
				nimln_(3775, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_9 = addInt(i, ((NI) 1));
				i = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_9);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__J7vWjOv59bjwwYcDHMIUtEg_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("*", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3772, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_10;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3774, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(111, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) * (NF32)(u.arr[(ii)- 0]));
				nimln_(3775, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_10 = addInt(i, ((NI) 1));
				i = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_10);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, yzx_QNKRCIoL02fVO14FHlc10Qvec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("yzx", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(220, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = v.arr[(((NI) 1))- 0];
	T1_.arr[1] = v.arr[(((NI) 2))- 0];
	T1_.arr[2] = v.arr[(((NI) 0))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, zxy_QNKRCIoL02fVO14FHlc10Q_2vec)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("zxy", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(220, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = v.arr[(((NI) 2))- 0];
	T1_.arr[1] = v.arr[(((NI) 0))- 0];
	T1_.arr[2] = v.arr[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(Vec_8lp09c9aJ6sSqRDc8uUVfyuA, cross_u30ZqBLCPuracR4Z1FBPOQ)(Vec_8lp09c9aJ6sSqRDc8uUVfyuA v1, Vec_8lp09c9aJ6sSqRDc8uUVfyuA v2) {
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T2_;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T3_;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T4_;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T5_;
	Vec_8lp09c9aJ6sSqRDc8uUVfyuA T6_;
	nimfr_("cross", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(486, "vec.nim");
	T1_ = yzx_QNKRCIoL02fVO14FHlc10Qvec(v1);
	T2_ = zxy_QNKRCIoL02fVO14FHlc10Q_2vec(v2);
	T3_ = star__J7vWjOv59bjwwYcDHMIUtEg_2vec(T1_, T2_);
	T4_ = zxy_QNKRCIoL02fVO14FHlc10Q_2vec(v1);
	T5_ = yzx_QNKRCIoL02fVO14FHlc10Qvec(v2);
	T6_ = star__J7vWjOv59bjwwYcDHMIUtEg_2vec(T4_, T5_);
	result = minus__J7vWjOv59bjwwYcDHMIUtEgvec(T3_, T6_);
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, minus__btEXTJnnMEuPmjWOn1TWIAvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, Vec_S5njPDIR1N39afJ9a6EQzdbA* u) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	nimfr_("-", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3772, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_11;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3774, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(111, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF)((*v).arr[(ii)- 0]) - (NF)((*u).arr[(ii)- 0]));
				nimln_(3775, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_11 = addInt(i, ((NI) 1));
				i = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_11);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, star__btEXTJnnMEuPmjWOn1TWIA_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v, Vec_S5njPDIR1N39afJ9a6EQzdbA* u) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	nimfr_("*", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3772, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3773, "system.nim");
			while (1) {
				NI TM_2eASAg1PfVZtHyF9c9buDWsg_12;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3774, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(111, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF)((*v).arr[(ii)- 0]) * (NF)((*u).arr[(ii)- 0]));
				nimln_(3775, "system.nim");
				TM_2eASAg1PfVZtHyF9c9buDWsg_12 = addInt(i, ((NI) 1));
				i = (NI)(TM_2eASAg1PfVZtHyF9c9buDWsg_12);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("yzx", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(220, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = (*v).arr[(((NI) 1))- 0];
	T1_.arr[1] = (*v).arr[(((NI) 2))- 0];
	T1_.arr[2] = (*v).arr[(((NI) 0))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(Vec_S5njPDIR1N39afJ9a6EQzdbA, zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("zxy", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(220, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = (*v).arr[(((NI) 2))- 0];
	T1_.arr[1] = (*v).arr[(((NI) 0))- 0];
	T1_.arr[2] = (*v).arr[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(Vec_S5njPDIR1N39afJ9a6EQzdbA, cross_xqD7SU75nzFLAQWqOYjycQ)(Vec_S5njPDIR1N39afJ9a6EQzdbA* v1, Vec_S5njPDIR1N39afJ9a6EQzdbA* v2) {
	Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T2_;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T3_;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T4_;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T5_;
	Vec_S5njPDIR1N39afJ9a6EQzdbA T6_;
	nimfr_("cross", "vec.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(486, "vec.nim");
	T1_ = yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec(v1);
	T2_ = zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec(v2);
	T3_ = star__btEXTJnnMEuPmjWOn1TWIA_2vec((&T1_), (&T2_));
	T4_ = zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec(v1);
	T5_ = yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec(v2);
	T6_ = star__btEXTJnnMEuPmjWOn1TWIA_2vec((&T4_), (&T5_));
	result = minus__btEXTJnnMEuPmjWOn1TWIAvec((&T3_), (&T6_));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void) {
	nimfr_("vec", "vec.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void) {
}

