/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_audio.o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_audio.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct AudioSpec_kRPU72qydVzwj5Wb8nEa6g AudioSpec_kRPU72qydVzwj5Wb8nEa6g;
typedef struct RWops_CLIyzMHHcrhaNlCqUuM1OA RWops_CLIyzMHHcrhaNlCqUuM1OA;
typedef struct AudioCVT_bwmPJAhcLqi20ykukqyVvw AudioCVT_bwmPJAhcLqi20ykukqyVvw;
typedef struct Mem_Y7I9bNHWVNgY3LblplAgArw Mem_Y7I9bNHWVNgY3LblplAgArw;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(NCSTRING, TY_6jJGBhZP5UsQBecZAlW9bUg) (int index);
typedef N_CDECL_PTR(int, TY_CoY7S9c9cTuw3ul9bVAHYxNQQ) (NCSTRING driver_name);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(int, TY_CIjd1Zs5Ejq9cxMz9agdm09bw) (AudioSpec_kRPU72qydVzwj5Wb8nEa6g* desired, AudioSpec_kRPU72qydVzwj5Wb8nEa6g* obtained);
typedef N_CDECL_PTR(int, TY_4hSZquf3VZZvlELaYshEWg) (int iscapture);
typedef N_CDECL_PTR(NCSTRING, TY_pgahiFyX9bJParYvZC8Zuew) (int index, int iscapture);
typedef N_CDECL_PTR(NU32, TY_Y9cPAsan5mTDlKFAlCTiquw) (NCSTRING device, int iscapture, AudioSpec_kRPU72qydVzwj5Wb8nEa6g* desired, AudioSpec_kRPU72qydVzwj5Wb8nEa6g* obtained, int allowed_changes);
typedef NI32 AudioStatus_ZJwdnsdGWIcTsbrTr0JxEA;
typedef N_CDECL_PTR(AudioStatus_ZJwdnsdGWIcTsbrTr0JxEA, TY_lPUg9cZ9cplmjf68zcOmPq4g) (void);
typedef N_CDECL_PTR(AudioStatus_ZJwdnsdGWIcTsbrTr0JxEA, TY_yJVmExmx9cll14WEiAf0Llg) (NU32 dev);
typedef N_CDECL_PTR(void, TY_NuisSWKwsQg36a0Egqo6Qw) (int pause_on);
typedef N_CDECL_PTR(void, TY_7nb0aeFM5rFssKcR6aelvA) (NU32 dev, int pause_on);
typedef N_CDECL_PTR(AudioSpec_kRPU72qydVzwj5Wb8nEa6g*, TY_m3ldEn7JS8qdTek4TE3bXw) (RWops_CLIyzMHHcrhaNlCqUuM1OA* src, int freesrc, AudioSpec_kRPU72qydVzwj5Wb8nEa6g* spec, NU8** audio_buf, NU32* audio_len);
typedef N_CDECL_PTR(void, TY_Y4Fc9bQJ2tSyYDAqZj9bIfqA) (NU8* audio_buf);
typedef N_CDECL_PTR(int, TY_NS4MnDHz6H1Jbf2efIUPQA) (AudioCVT_bwmPJAhcLqi20ykukqyVvw* cvt, NU16 src_format, NU8 src_channels, int src_rate, NU16 dst_format, NU8 dst_channels, int dst_rate);
typedef N_CDECL_PTR(int, TY_ywaKZwruEwq0NGjqwegKTA) (AudioCVT_bwmPJAhcLqi20ykukqyVvw* cvt);
typedef N_CDECL_PTR(void, TY_0ItxDyTd2EtywvKIrsa4dQ) (NU8* dst, NU8* src, NU32 len, int volume);
typedef N_CDECL_PTR(void, TY_h5sk0QQ3zY9awYovOpO1FIQ) (NU8* dst, NU8* src, NU16 format, NU32 len, int volume);
typedef N_CDECL_PTR(void, TY_CGFSM2Hc7U0HyNmEEh3xng) (NU32 dev);
typedef N_CDECL_PTR(void, TY_NLfu9c4YrA06CQ3WJJthGdg) (void* userdata, NU8* stream, int len);
struct  AudioSpec_kRPU72qydVzwj5Wb8nEa6g  {
int freq;
NU16 format;
NU8 channels;
NU8 silence;
NU16 samples;
NU16 padding;
NU32 size;
TY_NLfu9c4YrA06CQ3WJJthGdg callback;
void* userdata;
};
typedef N_CDECL_PTR(NI64, TY_pv8LHGd6Yei89cd2Rd8hv8g) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context);
typedef N_CDECL_PTR(NI64, TY_0zChuivuFV72gZwz2rUkHA) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, TY_i5pcx3FBdKHMUS2uvRgvYw) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context, void* destination, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, TY_LaZp89cSat1m2LqumdMScDw) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context);
struct  Mem_Y7I9bNHWVNgY3LblplAgArw  {
NU8* base;
NU8* here;
NU8* stop;
};
struct  RWops_CLIyzMHHcrhaNlCqUuM1OA  {
TY_pv8LHGd6Yei89cd2Rd8hv8g size;
TY_0zChuivuFV72gZwz2rUkHA seek;
TY_i5pcx3FBdKHMUS2uvRgvYw read;
TY_i5pcx3FBdKHMUS2uvRgvYw write;
TY_LaZp89cSat1m2LqumdMScDw close;
int kind;
Mem_Y7I9bNHWVNgY3LblplAgArw mem;
};
typedef N_CDECL_PTR(void, TY_tNLgpMAVTmmNeaBpIPywHw) (AudioCVT_bwmPJAhcLqi20ykukqyVvw* cvt, NU16 format);
typedef TY_tNLgpMAVTmmNeaBpIPywHw TY_3go1OB39a6FIc30iPK1gEig[10];
struct __attribute__((__packed__)) AudioCVT_bwmPJAhcLqi20ykukqyVvw  {
int needed;
NU16 src_format;
NU16 dst_format;
double rate_incr;
NU8* buf;
int len;
int len_cvt;
int len_mult;
double len_ratio;
TY_3go1OB39a6FIc30iPK1gEig filters;
int filter_index;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_RJT2VgKp1LfnYTSSKraSOw_2;
TY_cez8YhJI0vaCUcjGg6z4zA Dl_404201_;
TY_6jJGBhZP5UsQBecZAlW9bUg Dl_404203_;
TY_CoY7S9c9cTuw3ul9bVAHYxNQQ Dl_404206_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_404209_;
TY_09bvyvHFtWbkzL5AHgf0bKw Dl_404211_;
TY_CIjd1Zs5Ejq9cxMz9agdm09bw Dl_404213_;
TY_4hSZquf3VZZvlELaYshEWg Dl_404219_;
TY_pgahiFyX9bJParYvZC8Zuew Dl_404222_;
TY_Y9cPAsan5mTDlKFAlCTiquw Dl_404226_;
TY_lPUg9cZ9cplmjf68zcOmPq4g Dl_404235_;
TY_yJVmExmx9cll14WEiAf0Llg Dl_404237_;
TY_NuisSWKwsQg36a0Egqo6Qw Dl_404240_;
TY_7nb0aeFM5rFssKcR6aelvA Dl_404243_;
TY_m3ldEn7JS8qdTek4TE3bXw Dl_404247_;
TY_Y4Fc9bQJ2tSyYDAqZj9bIfqA Dl_404271_;
TY_NS4MnDHz6H1Jbf2efIUPQA Dl_404275_;
TY_ywaKZwruEwq0NGjqwegKTA Dl_404285_;
TY_0ItxDyTd2EtywvKIrsa4dQ Dl_404289_;
TY_h5sk0QQ3zY9awYovOpO1FIQ Dl_404297_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_404306_;
TY_CGFSM2Hc7U0HyNmEEh3xng Dl_404308_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_404311_;
TY_CGFSM2Hc7U0HyNmEEh3xng Dl_404313_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_404316_;
TY_CGFSM2Hc7U0HyNmEEh3xng Dl_404318_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_RJT2VgKp1LfnYTSSKraSOw_4, "libSDL2.dylib", 13);
STRING_LITERAL(TM_RJT2VgKp1LfnYTSSKraSOw_5, "libSDL2.dylib", 13);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_audioInit000)(void) {
	nimfr_("audio", "audio.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_audioDatInit000)(void) {
if (!((TM_RJT2VgKp1LfnYTSSKraSOw_2 = nimLoadLibrary((NimStringDesc*) &TM_RJT2VgKp1LfnYTSSKraSOw_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_RJT2VgKp1LfnYTSSKraSOw_5);
	Dl_404201_ = (TY_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetNumAudioDrivers");
	Dl_404203_ = (TY_6jJGBhZP5UsQBecZAlW9bUg) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetAudioDriver");
	Dl_404206_ = (TY_CoY7S9c9cTuw3ul9bVAHYxNQQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_AudioInit");
	Dl_404209_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_AudioQuit");
	Dl_404211_ = (TY_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetCurrentAudioDriver");
	Dl_404213_ = (TY_CIjd1Zs5Ejq9cxMz9agdm09bw) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_OpenAudio");
	Dl_404219_ = (TY_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetNumAudioDevices");
	Dl_404222_ = (TY_pgahiFyX9bJParYvZC8Zuew) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetAudioDeviceName");
	Dl_404226_ = (TY_Y9cPAsan5mTDlKFAlCTiquw) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_OpenAudioDevice");
	Dl_404235_ = (TY_lPUg9cZ9cplmjf68zcOmPq4g) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetAudioStatus");
	Dl_404237_ = (TY_yJVmExmx9cll14WEiAf0Llg) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_GetAudioDeviceStatus");
	Dl_404240_ = (TY_NuisSWKwsQg36a0Egqo6Qw) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_PauseAudio");
	Dl_404243_ = (TY_7nb0aeFM5rFssKcR6aelvA) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_PauseAudioDevice");
	Dl_404247_ = (TY_m3ldEn7JS8qdTek4TE3bXw) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_LoadWAV_RW");
	Dl_404271_ = (TY_Y4Fc9bQJ2tSyYDAqZj9bIfqA) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_FreeWAV");
	Dl_404275_ = (TY_NS4MnDHz6H1Jbf2efIUPQA) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_BuildAudioCVT");
	Dl_404285_ = (TY_ywaKZwruEwq0NGjqwegKTA) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_ConvertAudio");
	Dl_404289_ = (TY_0ItxDyTd2EtywvKIrsa4dQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_MixAudio");
	Dl_404297_ = (TY_h5sk0QQ3zY9awYovOpO1FIQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_MixAudioFormat");
	Dl_404306_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_LockAudio");
	Dl_404308_ = (TY_CGFSM2Hc7U0HyNmEEh3xng) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_LockAudioDevice");
	Dl_404311_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_UnlockAudio");
	Dl_404313_ = (TY_CGFSM2Hc7U0HyNmEEh3xng) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_UnlockAudioDevice");
	Dl_404316_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_CloseAudio");
	Dl_404318_ = (TY_CGFSM2Hc7U0HyNmEEh3xng) nimGetProcAddr(TM_RJT2VgKp1LfnYTSSKraSOw_2, "SDL_CloseAudioDevice");
}

