/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_gamecontroller.o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_gamecontroller.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg;
typedef struct GameController_KRdxeqFDO2z3WbJLpR7qIg GameController_KRdxeqFDO2z3WbJLpR7qIg;
typedef struct Joystick_0GdOO9cfz9c9cAij9atLn707GA Joystick_0GdOO9cfz9c9cAij9atLn707GA;
typedef struct GameControllerButtonBind_KhbX09c9bQPJkBIBr9cXmZfCw GameControllerButtonBind_KhbX09c9bQPJkBIBr9cXmZfCw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY_CoY7S9c9cTuw3ul9bVAHYxNQQ) (NCSTRING mappingString);
typedef N_CDECL_PTR(NCSTRING, TY_m79cL9b5lgk7DadoGCLkuAbQ) (JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg guid);
typedef N_CDECL_PTR(NCSTRING, TY_rIwlhvvOXczOrwIzXd1KnA) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController);
typedef NI32 Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_EDVhmi5jrU9awyWZwYAuSsg) (int joystickIndex);
typedef N_CDECL_PTR(NCSTRING, TY_6jJGBhZP5UsQBecZAlW9bUg) (int joystickIndex);
typedef N_CDECL_PTR(GameController_KRdxeqFDO2z3WbJLpR7qIg*, TY_IHNFlIJDV37XriNmIWB1nw) (int joystickIndex);
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_Lm1VJdGp9c9bAe0zhM7JQI4A) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController);
typedef N_CDECL_PTR(Joystick_0GdOO9cfz9c9cAij9atLn707GA*, TY_LNGrHlOFnX9aZit1y59cdxFQ) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController);
typedef N_CDECL_PTR(int, TY_4hSZquf3VZZvlELaYshEWg) (int state);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef NI32 GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew;
typedef N_CDECL_PTR(GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew, TY_nvJcN69axlthBl2IDo4xgkA) (NCSTRING pchString);
typedef N_CDECL_PTR(NCSTRING, TY_fRz5LbWo9coDqHBUlGNdSAA) (GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew axis);
typedef NI32 GameControllerBindType_fqvMrPuIWIzRk6oaP9cJ7ZQ;
struct  GameControllerButtonBind_KhbX09c9bQPJkBIBr9cXmZfCw  {
GameControllerBindType_fqvMrPuIWIzRk6oaP9cJ7ZQ bindType;
union{
struct {int button;
} S2;
struct {int axis;
} S3;
struct {int hat;
int hatMask;
} S4;
} bindTypeU;
};
typedef N_CDECL_PTR(GameControllerButtonBind_KhbX09c9bQPJkBIBr9cXmZfCw, TY_EnGhJGbJ9c6gfc4VFgIL4Ew) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController, GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew axis);
typedef N_CDECL_PTR(NI16, TY_rDdiOiX9c62vtH9a4qgnIAlw) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController, GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew axis);
typedef NI32 GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ;
typedef N_CDECL_PTR(GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ, TY_8OKBo0a56AYq0Q8kLaCfug) (NCSTRING pchString);
typedef N_CDECL_PTR(NCSTRING, TY_9bzIY9b8aC8QfPj9aSL3tBmdg) (GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ button);
typedef N_CDECL_PTR(GameControllerButtonBind_KhbX09c9bQPJkBIBr9cXmZfCw, TY_2V2QZIpX9boZSFYDS2IwOsg) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController, GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ button);
typedef N_CDECL_PTR(NU8, TY_oemoiwpATE9bNiuaZcxnPTg) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController, GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ button);
typedef N_CDECL_PTR(void, TY_PsWnMFaMhwv70wZT9aWE3fw) (GameController_KRdxeqFDO2z3WbJLpR7qIg* gameController);
struct  GameController_KRdxeqFDO2z3WbJLpR7qIg  {
char dummy;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY_qtqsWM5aXmcpMIVmvq3kAA[16];
struct  JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg  {
TY_qtqsWM5aXmcpMIVmvq3kAA data;
};
struct  Joystick_0GdOO9cfz9c9cAij9atLn707GA  {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_CDECL(NU8, toInt_iEy9bzGvUoe9a7lrp9anYrD8w)(GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew some);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_CDECL(NU8, toInt_fKyHy3tvL9al4VGG0NrYNiQ)(GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ some);
static void* TM_1CxscsZ4yEzsLi9aO5niN1Q_2;
TY_CoY7S9c9cTuw3ul9bVAHYxNQQ Dl_322201_;
TY_m79cL9b5lgk7DadoGCLkuAbQ Dl_322204_;
TY_rIwlhvvOXczOrwIzXd1KnA Dl_322207_;
TY_EDVhmi5jrU9awyWZwYAuSsg Dl_322210_;
TY_6jJGBhZP5UsQBecZAlW9bUg Dl_322213_;
TY_IHNFlIJDV37XriNmIWB1nw Dl_322216_;
TY_rIwlhvvOXczOrwIzXd1KnA Dl_322219_;
TY_Lm1VJdGp9c9bAe0zhM7JQI4A Dl_322222_;
TY_LNGrHlOFnX9aZit1y59cdxFQ Dl_322225_;
TY_4hSZquf3VZZvlELaYshEWg Dl_322228_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_322231_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_nvJcN69axlthBl2IDo4xgkA Dl_322248_;
TY_fRz5LbWo9coDqHBUlGNdSAA Dl_322251_;
TY_EnGhJGbJ9c6gfc4VFgIL4Ew Dl_322254_;
TY_rDdiOiX9c62vtH9a4qgnIAlw Dl_322258_;
TY_8OKBo0a56AYq0Q8kLaCfug Dl_322286_;
TY_9bzIY9b8aC8QfPj9aSL3tBmdg Dl_322289_;
TY_2V2QZIpX9boZSFYDS2IwOsg Dl_322292_;
TY_oemoiwpATE9bNiuaZcxnPTg Dl_322296_;
TY_PsWnMFaMhwv70wZT9aWE3fw Dl_322300_;
TNimType NTI_KRdxeqFDO2z3WbJLpR7qIg_;
TNimType NTI_2qAhgUCQIMGHXUQkjxokFQ_;
STRING_LITERAL(TM_1CxscsZ4yEzsLi9aO5niN1Q_4, "libSDL2.dylib", 13);
STRING_LITERAL(TM_1CxscsZ4yEzsLi9aO5niN1Q_5, "libSDL2.dylib", 13);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_CDECL(NU8, toInt_iEy9bzGvUoe9a7lrp9anYrD8w)(GameControllerAxis_rTBuql1d5Ao8zfcCG6X4Ew some) {
	NU8 result;
	nimfr_("toInt", "gamecontroller.nim")
	result = (NU8)0;
	nimln_(205, "gamecontroller.nim");
	result = ((NU8) (some));
	popFrame();
	return result;
}

N_CDECL(NU8, toInt_fKyHy3tvL9al4VGG0NrYNiQ)(GameControllerButton_xdY5Gw1ONFXLhNkg9bxQCnQ some) {
	NU8 result;
	nimfr_("toInt", "gamecontroller.nim")
	result = (NU8)0;
	nimln_(258, "gamecontroller.nim");
	result = ((NU8) (some));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_gamecontrollerInit000)(void) {
	nimfr_("gamecontroller", "gamecontroller.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_gamecontrollerDatInit000)(void) {
static TNimNode TM_1CxscsZ4yEzsLi9aO5niN1Q_0[1];
NTI_KRdxeqFDO2z3WbJLpR7qIg_.size = sizeof(GameController_KRdxeqFDO2z3WbJLpR7qIg);
NTI_KRdxeqFDO2z3WbJLpR7qIg_.kind = 18;
NTI_KRdxeqFDO2z3WbJLpR7qIg_.base = 0;
NTI_KRdxeqFDO2z3WbJLpR7qIg_.flags = 3;
TM_1CxscsZ4yEzsLi9aO5niN1Q_0[0].len = 0; TM_1CxscsZ4yEzsLi9aO5niN1Q_0[0].kind = 2;
NTI_KRdxeqFDO2z3WbJLpR7qIg_.node = &TM_1CxscsZ4yEzsLi9aO5niN1Q_0[0];
NTI_2qAhgUCQIMGHXUQkjxokFQ_.size = sizeof(GameController_KRdxeqFDO2z3WbJLpR7qIg*);
NTI_2qAhgUCQIMGHXUQkjxokFQ_.kind = 21;
NTI_2qAhgUCQIMGHXUQkjxokFQ_.base = (&NTI_KRdxeqFDO2z3WbJLpR7qIg_);
NTI_2qAhgUCQIMGHXUQkjxokFQ_.flags = 3;
if (!((TM_1CxscsZ4yEzsLi9aO5niN1Q_2 = nimLoadLibrary((NimStringDesc*) &TM_1CxscsZ4yEzsLi9aO5niN1Q_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_1CxscsZ4yEzsLi9aO5niN1Q_5);
	Dl_322201_ = (TY_CoY7S9c9cTuw3ul9bVAHYxNQQ) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerAddMapping");
	Dl_322204_ = (TY_m79cL9b5lgk7DadoGCLkuAbQ) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerMappingForGUID");
	Dl_322207_ = (TY_rIwlhvvOXczOrwIzXd1KnA) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerMapping");
	Dl_322210_ = (TY_EDVhmi5jrU9awyWZwYAuSsg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_IsGameController");
	Dl_322213_ = (TY_6jJGBhZP5UsQBecZAlW9bUg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerNameForIndex");
	Dl_322216_ = (TY_IHNFlIJDV37XriNmIWB1nw) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerOpen");
	Dl_322219_ = (TY_rIwlhvvOXczOrwIzXd1KnA) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerName");
	Dl_322222_ = (TY_Lm1VJdGp9c9bAe0zhM7JQI4A) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetAttached");
	Dl_322225_ = (TY_LNGrHlOFnX9aZit1y59cdxFQ) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetJoystick");
	Dl_322228_ = (TY_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerEventState");
	Dl_322231_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerUpdate");
	Dl_322248_ = (TY_nvJcN69axlthBl2IDo4xgkA) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetAxisFromString");
	Dl_322251_ = (TY_fRz5LbWo9coDqHBUlGNdSAA) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetStringForAxis");
	Dl_322254_ = (TY_EnGhJGbJ9c6gfc4VFgIL4Ew) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetBindForAxis");
	Dl_322258_ = (TY_rDdiOiX9c62vtH9a4qgnIAlw) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetAxis");
	Dl_322286_ = (TY_8OKBo0a56AYq0Q8kLaCfug) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetButtonFromString");
	Dl_322289_ = (TY_9bzIY9b8aC8QfPj9aSL3tBmdg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetStringForButton");
	Dl_322292_ = (TY_2V2QZIpX9boZSFYDS2IwOsg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetBindForButton");
	Dl_322296_ = (TY_oemoiwpATE9bNiuaZcxnPTg) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerGetButton");
	Dl_322300_ = (TY_PsWnMFaMhwv70wZT9aWE3fw) nimGetProcAddr(TM_1CxscsZ4yEzsLi9aO5niN1Q_2, "SDL_GameControllerClose");
}

