/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_joystick.o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_joystick.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Joystick_0GdOO9cfz9c9cAij9atLn707GA Joystick_0GdOO9cfz9c9cAij9atLn707GA;
typedef struct JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(NCSTRING, TY_6jJGBhZP5UsQBecZAlW9bUg) (int device_index);
typedef N_CDECL_PTR(Joystick_0GdOO9cfz9c9cAij9atLn707GA*, TY_zyAJPWRXi7Sg9c3SPDYNzUA) (int device_index);
typedef N_CDECL_PTR(NCSTRING, TY_7dUZLO9cb1dpadSbbVOg3Sw) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
typedef NU8 TY_qtqsWM5aXmcpMIVmvq3kAA[16];
struct  JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg  {
TY_qtqsWM5aXmcpMIVmvq3kAA data;
};
typedef N_CDECL_PTR(JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg, TY_qLdgG619aGTMFiGuEYt9a9aJA) (int device_index);
typedef N_CDECL_PTR(JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg, TY_QIUEzjm3z8Ke6Q32TKeclQ) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
typedef N_CDECL_PTR(void, TY_7X34Te5VfLoVStw8V2aehw) (JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg guid, NCSTRING pszGUID, int cbGUID);
typedef N_CDECL_PTR(JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg, TY_BQkuf3rAPpvdsQz8W9bz45A) (NCSTRING pchGUID);
typedef NI32 Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_Kf3HsNnTu4lImlaRxPTM9aQ) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
typedef N_CDECL_PTR(NI32, TY_3S9a3ZwmMEfF9a4IEuLPI0lA) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
typedef N_CDECL_PTR(int, TY_e9ccJUKQzF0NmQWGVkb1uKA) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, TY_4hSZquf3VZZvlELaYshEWg) (int state);
typedef N_CDECL_PTR(NI16, TY_3hqLKTZZ1apt1O2ehXnrjg) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int axis);
typedef N_CDECL_PTR(NU8, TY_Y0y2pmfh5OLChHpfp9cQv9bA) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int hat);
typedef N_CDECL_PTR(int, TY_fkgZRxX8HuCzjFjtxtgDGw) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int ball, int* dx, int* dy);
typedef N_CDECL_PTR(void, TY_WVuUos0kKv9cN259cAsT2ujQ) (Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
struct  Joystick_0GdOO9cfz9c9cAij9atLn707GA  {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(NCSTRING, name_9a0t2FzroGiUm8h0PvUOoSQjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg, getGUID_kx4RQIjj7TGxEe7O4uuTgwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(Bool32_lrv4aZgVTmBUYdrYUkLMlg, getAttached_IZ9bRK9aaM9bmH0osaGtEvcUgjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(NI32, instanceID_gTDzKyJOxfImP3F5BnLUlAjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(int, numAxes_EaDGoogejJ0aRWu4479bn7gjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(int, numBalls_EaDGoogejJ0aRWu4479bn7g_2joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(int, numHats_EaDGoogejJ0aRWu4479bn7g_3joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(int, numButtons_EaDGoogejJ0aRWu4479bn7g_4joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static N_INLINE(NI16, getAxis_42wAQgdsTgTmh3v9bCATOAwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int axis);
static N_INLINE(NU8, getHat_610HZAZWROAKcLHhetzbpwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int hat);
static N_INLINE(int, getBall_RsdxkQGUT9bfVvuzxzYpBYQjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int ball, int* dx, int* dy);
static N_INLINE(NU8, getButton_fiPhfn6SVFlySV7a4TpjFwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int button);
static N_INLINE(void, close_e2M3cBNKGPE9c54iBKOaJAwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick);
static void* TM_8XA1cZhEm8eED8V6D4CXYg_2;
TY_cez8YhJI0vaCUcjGg6z4zA Dl_321201_;
TY_6jJGBhZP5UsQBecZAlW9bUg Dl_321203_;
TY_zyAJPWRXi7Sg9c3SPDYNzUA Dl_321206_;
TY_7dUZLO9cb1dpadSbbVOg3Sw Dl_321209_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_qLdgG619aGTMFiGuEYt9a9aJA Dl_321218_;
TY_QIUEzjm3z8Ke6Q32TKeclQ Dl_321221_;
TY_7X34Te5VfLoVStw8V2aehw Dl_321228_;
TY_BQkuf3rAPpvdsQz8W9bz45A Dl_321233_;
TY_Kf3HsNnTu4lImlaRxPTM9aQ Dl_321236_;
TY_3S9a3ZwmMEfF9a4IEuLPI0lA Dl_321243_;
TY_e9ccJUKQzF0NmQWGVkb1uKA Dl_321250_;
TY_e9ccJUKQzF0NmQWGVkb1uKA Dl_321257_;
TY_e9ccJUKQzF0NmQWGVkb1uKA Dl_321264_;
TY_e9ccJUKQzF0NmQWGVkb1uKA Dl_321271_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_321278_;
TY_4hSZquf3VZZvlELaYshEWg Dl_321280_;
TY_3hqLKTZZ1apt1O2ehXnrjg Dl_321283_;
TY_Y0y2pmfh5OLChHpfp9cQv9bA Dl_321301_;
TY_fkgZRxX8HuCzjFjtxtgDGw Dl_321310_;
TY_Y0y2pmfh5OLChHpfp9cQv9bA Dl_321327_;
TY_WVuUos0kKv9cN259cAsT2ujQ Dl_321336_;
STRING_LITERAL(TM_8XA1cZhEm8eED8V6D4CXYg_4, "libSDL2.dylib", 13);
STRING_LITERAL(TM_8XA1cZhEm8eED8V6D4CXYg_5, "libSDL2.dylib", 13);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NCSTRING, name_9a0t2FzroGiUm8h0PvUOoSQjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	NCSTRING result;
	nimfr_("name", "joystick.nim")
	result = (NCSTRING)0;
	nimln_(99, "joystick.nim");
	result = Dl_321209_(joystick);
	popFrame();
	return result;
}

static N_INLINE(JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg, getGUID_kx4RQIjj7TGxEe7O4uuTgwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	JoystickGuid_mycKxPOPVUZ9cVqyH079aP9cg result;
	nimfr_("getGUID", "joystick.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(112, "joystick.nim");
	result = Dl_321221_(joystick);
	popFrame();
	return result;
}

static N_INLINE(Bool32_lrv4aZgVTmBUYdrYUkLMlg, getAttached_IZ9bRK9aaM9bmH0osaGtEvcUgjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	Bool32_lrv4aZgVTmBUYdrYUkLMlg result;
	nimfr_("getAttached", "joystick.nim")
	result = (Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
	nimln_(132, "joystick.nim");
	result = Dl_321236_(joystick);
	popFrame();
	return result;
}

static N_INLINE(NI32, instanceID_gTDzKyJOxfImP3F5BnLUlAjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	NI32 result;
	nimfr_("instanceID", "joystick.nim")
	result = (NI32)0;
	nimln_(139, "joystick.nim");
	result = Dl_321243_(joystick);
	popFrame();
	return result;
}

static N_INLINE(int, numAxes_EaDGoogejJ0aRWu4479bn7gjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	int result;
	nimfr_("numAxes", "joystick.nim")
	result = (int)0;
	nimln_(146, "joystick.nim");
	result = Dl_321250_(joystick);
	popFrame();
	return result;
}

static N_INLINE(int, numBalls_EaDGoogejJ0aRWu4479bn7g_2joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	int result;
	nimfr_("numBalls", "joystick.nim")
	result = (int)0;
	nimln_(157, "joystick.nim");
	result = Dl_321257_(joystick);
	popFrame();
	return result;
}

static N_INLINE(int, numHats_EaDGoogejJ0aRWu4479bn7g_3joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	int result;
	nimfr_("numHats", "joystick.nim")
	result = (int)0;
	nimln_(164, "joystick.nim");
	result = Dl_321264_(joystick);
	popFrame();
	return result;
}

static N_INLINE(int, numButtons_EaDGoogejJ0aRWu4479bn7g_4joystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	int result;
	nimfr_("numButtons", "joystick.nim")
	result = (int)0;
	nimln_(171, "joystick.nim");
	result = Dl_321271_(joystick);
	popFrame();
	return result;
}

static N_INLINE(NI16, getAxis_42wAQgdsTgTmh3v9bCATOAwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int axis) {
	NI16 result;
	nimfr_("getAxis", "joystick.nim")
	result = (NI16)0;
	nimln_(202, "joystick.nim");
	result = Dl_321283_(joystick, axis);
	popFrame();
	return result;
}

static N_INLINE(NU8, getHat_610HZAZWROAKcLHhetzbpwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int hat) {
	NU8 result;
	nimfr_("getHat", "joystick.nim")
	result = (NU8)0;
	nimln_(238, "joystick.nim");
	result = Dl_321301_(joystick, hat);
	popFrame();
	return result;
}

static N_INLINE(int, getBall_RsdxkQGUT9bfVvuzxzYpBYQjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int ball, int* dx, int* dy) {
	int result;
	nimfr_("getBall", "joystick.nim")
	result = (int)0;
	nimln_(249, "joystick.nim");
	result = Dl_321310_(joystick, ball, dx, dy);
	popFrame();
	return result;
}

static N_INLINE(NU8, getButton_fiPhfn6SVFlySV7a4TpjFwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick, int button) {
	NU8 result;
	nimfr_("getButton", "joystick.nim")
	result = (NU8)0;
	nimln_(258, "joystick.nim");
	result = Dl_321327_(joystick, button);
	popFrame();
	return result;
}

static N_INLINE(void, close_e2M3cBNKGPE9c54iBKOaJAwjoystick)(Joystick_0GdOO9cfz9c9cAij9atLn707GA* joystick) {
	nimfr_("close", "joystick.nim")
	nimln_(265, "joystick.nim");
	Dl_321336_(joystick);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, sdl2_joystickInit000)(void) {
	nimfr_("joystick", "joystick.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_joystickDatInit000)(void) {
if (!((TM_8XA1cZhEm8eED8V6D4CXYg_2 = nimLoadLibrary((NimStringDesc*) &TM_8XA1cZhEm8eED8V6D4CXYg_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_8XA1cZhEm8eED8V6D4CXYg_5);
	Dl_321201_ = (TY_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_NumJoysticks");
	Dl_321203_ = (TY_6jJGBhZP5UsQBecZAlW9bUg) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickNameForIndex");
	Dl_321206_ = (TY_zyAJPWRXi7Sg9c3SPDYNzUA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickOpen");
	Dl_321209_ = (TY_7dUZLO9cb1dpadSbbVOg3Sw) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickName");
	Dl_321218_ = (TY_qLdgG619aGTMFiGuEYt9a9aJA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetDeviceGUID");
	Dl_321221_ = (TY_QIUEzjm3z8Ke6Q32TKeclQ) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetGUID");
	Dl_321228_ = (TY_7X34Te5VfLoVStw8V2aehw) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetGUIDString");
	Dl_321233_ = (TY_BQkuf3rAPpvdsQz8W9bz45A) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetGUIDFromString");
	Dl_321236_ = (TY_Kf3HsNnTu4lImlaRxPTM9aQ) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetAttached");
	Dl_321243_ = (TY_3S9a3ZwmMEfF9a4IEuLPI0lA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickInstanceID");
	Dl_321250_ = (TY_e9ccJUKQzF0NmQWGVkb1uKA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickNumAxes");
	Dl_321257_ = (TY_e9ccJUKQzF0NmQWGVkb1uKA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickNumBalls");
	Dl_321264_ = (TY_e9ccJUKQzF0NmQWGVkb1uKA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickNumHats");
	Dl_321271_ = (TY_e9ccJUKQzF0NmQWGVkb1uKA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickNumButtons");
	Dl_321278_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickUpdate");
	Dl_321280_ = (TY_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickEventState");
	Dl_321283_ = (TY_3hqLKTZZ1apt1O2ehXnrjg) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetAxis");
	Dl_321301_ = (TY_Y0y2pmfh5OLChHpfp9cQv9bA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetHat");
	Dl_321310_ = (TY_fkgZRxX8HuCzjFjtxtgDGw) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetBall");
	Dl_321327_ = (TY_Y0y2pmfh5OLChHpfp9cQv9bA) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickGetButton");
	Dl_321336_ = (TY_WVuUos0kKv9cN259cAsT2ujQ) nimGetProcAddr(TM_8XA1cZhEm8eED8V6D4CXYg_2, "SDL_JoystickClose");
}

