/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_sdl2.o /Users/pakchoi/Workspace/campfire/src/nimcache/sdl2_sdl2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct Event_Uzh9aP43ffUpM9aa6vZvNEug Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct TY_Ye8PLO8qqXk1tek2VP9c0UQ TY_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Surface_sOGmuBWrSv9c4mZ0oaW1R1w Surface_sOGmuBWrSv9c4mZ0oaW1R1w;
typedef struct PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg;
typedef struct BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g;
typedef struct Palette_D3H7z9cPmFr0tk2z8jKdcYg Palette_D3H7z9cPmFr0tk2z8jKdcYg;
typedef struct TY_Xo4YhcsfLAmbGDNu1Obfcw TY_Xo4YhcsfLAmbGDNu1Obfcw;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg;
typedef struct MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw;
typedef struct ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg;
typedef struct ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg;
typedef struct ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw;
typedef struct WindowEventObj_d6XCemaEKzK59bxf1YxrwlA WindowEventObj_d6XCemaEKzK59bxf1YxrwlA;
typedef struct KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ;
typedef struct RWops_CLIyzMHHcrhaNlCqUuM1OA RWops_CLIyzMHHcrhaNlCqUuM1OA;
typedef struct KeySym_y3t7PyKCT9aYLDh9bLHT3UPw KeySym_y3t7PyKCT9aYLDh9bLHT3UPw;
typedef struct Mem_Y7I9bNHWVNgY3LblplAgArw Mem_Y7I9bNHWVNgY3LblplAgArw;
typedef NI32 EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 TY_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct  Event_Uzh9aP43ffUpM9aa6vZvNEug  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
TY_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
struct TY_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Surface_sOGmuBWrSv9c4mZ0oaW1R1w  {
NU32 flags;
PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lock_data;
TY_Ye8PLO8qqXk1tek2VP9c0UQ clip_rect;
BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g* map;
int refcount;
};
typedef NU8 TY_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct  PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg  {
NU32 format;
Palette_D3H7z9cPmFr0tk2z8jKdcYg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
TY_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* next;
};
struct  Palette_D3H7z9cPmFr0tk2z8jKdcYg  {
int ncolors;
TY_Xo4YhcsfLAmbGDNu1Obfcw* colors;
NU32 version;
int refcount;
};
struct TY_Xo4YhcsfLAmbGDNu1Obfcw {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct  BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g  {
char dummy;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, TY_9br0blXFlJAjbk9cGDwi8EgA) (void* pixels, int width, int height, int depth, int pitch, NU32 Rmask, NU32 Gmask, NU32 Bmask, NU32 Amask);
typedef N_CDECL_PTR(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, TY_OlsILfsIzW9b2h6RP9cRx1pQ) (Surface_sOGmuBWrSv9c4mZ0oaW1R1w* src, PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* fmt, int flags);
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(NU32, TY_ZBJ5GRli6YRWUmwPMxvXiw) (void);
typedef NI32 Scancode_ZC4j1APU9aAJPXuZfLFUG0w;
typedef N_CDECL_PTR(Scancode_ZC4j1APU9aAJPXuZfLFUG0w, TY_8bKtXZcxYnKUJLFwBU2xmw) (NCSTRING name);
typedef N_CDECL_PTR(NCSTRING, TY_6jJGBhZP5UsQBecZAlW9bUg) (int key);
typedef N_CDECL_PTR(int, TY_24AcZiuGxj9aAIKC1Z9aBKgw) (Scancode_ZC4j1APU9aAJPXuZfLFUG0w scancode);
typedef N_CDECL_PTR(NU8*, TY_J1PDbNq7uKOgh20mdTxcDg) (NI* numkeys);
typedef NI32 SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_vfBise28cLJJujY6ZnHPIw) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_EH6q2UEpsQbudAOirVaRhQ) (TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, TY_Ye8PLO8qqXk1tek2VP9c0UQ* rect, void* pixels, int pitch);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_BzAZji9bzvN1k9ae25rIlb8A) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY_zHpDbFN4o9bvP9cAphXAUHXg) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_wbFMpEnGfJo5HTFBx413GA) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, TY_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, TY_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect);
typedef N_CDECL_PTR(void, TY_9a8AalbnAaIxTUMpzQQqpjw) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, TY_CGFSM2Hc7U0HyNmEEh3xng) (NU32 ms);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_gk5XfBB59a479c3sEPSMZUOg) (Surface_sOGmuBWrSv9c4mZ0oaW1R1w* dst, TY_Ye8PLO8qqXk1tek2VP9c0UQ* rect, NU32 color);
typedef N_CDECL_PTR(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, TY_jhdVmRFWTpNd1iR9aS9c5hQQ) (int flags, int width, int height, int depth, NU32 Rmask, NU32 Gmask, NU32 BMask, NU32 Amask);
typedef N_CDECL_PTR(int, TY_zQuulNED1MWFt3geigWzvg) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TY_Ye8PLO8qqXk1tek2VP9c0UQ* rect, int format, void* pixels, int pitch);
typedef N_CDECL_PTR(void, TY_qBZJbpNSUKmN7D9cXKfuoeg) (Surface_sOGmuBWrSv9c4mZ0oaW1R1w* surface);
typedef N_CDECL_PTR(NU8, TY_yLg9aKhE9aoiOkMB0pzXMlyg) (int* x, int* y);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_V9bZBkxVuJzbGuMjLg1FVUw) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, NU32 fullscreen);
typedef N_CDECL_PTR(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, TY_3xgAKCPZlTDmyFCl87eZgg) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU32 format, int access, int w, int h);
typedef NI32 TextureAccess_lHfWejC67dkj9bzL3rlYUdw;
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_kIyA9c9bffk59bCZDzZS0sc8g) (Palette_D3H7z9cPmFr0tk2z8jKdcYg* palette, TY_Xo4YhcsfLAmbGDNu1Obfcw* colors, int first, int numColors);
typedef N_CDECL_PTR(int, TY_FdNQc14l0KrdlpQKlTQjEA) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, int w, int h);
typedef N_CDECL_PTR(void, TY_qINgM1UYlIsWdn51nn0qrQ) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int w, int h);
typedef NI32 Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_gHZVvnv6jeg9cI9brLoWECJw) (Bool32_lrv4aZgVTmBUYdrYUkLMlg enabled);
typedef NI32 Keymod_Ezy2rGsnAFwkomNIvFNZ1A;
typedef N_CDECL_PTR(NU32, TY_m9cok4JvX7n8tIbkphyvkhw) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_b9aXpKFbsyZ0PIk3aYRVCAA) (Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef N_CDECL_PTR(void, TY_wFKHMJeFuSq6GTOGu9c9ayaw) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, NCSTRING title);
typedef N_CDECL_PTR(NU32, TY_J5qn9cllF8g9bqRSS9bVM9avbw) (PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* format, NU8 r, NU8 g, NU8 b);
typedef N_CDECL_PTR(RWops_CLIyzMHHcrhaNlCqUuM1OA*, TY_WLF2LPFZnB469bJx7k0rQDg) (NCSTRING file, NCSTRING mode);
typedef N_CDECL_PTR(NIM_BOOL, TY_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(NCSTRING, TY_LR0DuTVmiHsWUuG5hbpBOQ) (NCSTRING org, NCSTRING app);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, TY_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, TY_eGPD9aEHv9b8sVQMCQaPsYkg) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_CWVVjvObnKbXecMOP3ypVQ) (NIM_BOOL toggle);
struct  RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg  {
char dummy;
};
struct  TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw  {
char dummy;
};
struct  WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w  {
char dummy;
};
typedef NI32 MouseWheelDirection_ndQsZIBTF1N2Cb9c7mV9b2VQ;
struct  MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
int x;
int y;
MouseWheelDirection_ndQsZIBTF1N2Cb9c7mV9b2VQ direction;
};
struct  MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU8 button;
NU8 state;
NU8 clicks;
NU8 pad2;
int x;
int y;
};
struct  ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NI32 which;
};
struct  ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NI32 which;
NU8 button;
NU8 state;
};
struct  ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NI32 which;
NU8 axis;
NU8 pad1;
NU8 pad2;
NU8 pad3;
NI16 value;
};
typedef NU8 WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw;
struct  WindowEventObj_d6XCemaEKzK59bxf1YxrwlA  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw event;
NU8 pad1;
NU8 pad2;
NU8 pad3;
int data1;
int data2;
};
struct  KeySym_y3t7PyKCT9aYLDh9bLHT3UPw  {
Scancode_ZC4j1APU9aAJPXuZfLFUG0w scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
KeySym_y3t7PyKCT9aYLDh9bLHT3UPw keysym;
};
typedef N_CDECL_PTR(NI64, TY_pv8LHGd6Yei89cd2Rd8hv8g) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context);
typedef N_CDECL_PTR(NI64, TY_0zChuivuFV72gZwz2rUkHA) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, TY_i5pcx3FBdKHMUS2uvRgvYw) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context, void* destination, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, TY_LaZp89cSat1m2LqumdMScDw) (RWops_CLIyzMHHcrhaNlCqUuM1OA* context);
struct  Mem_Y7I9bNHWVNgY3LblplAgArw  {
NU8* base;
NU8* here;
NU8* stop;
};
struct  RWops_CLIyzMHHcrhaNlCqUuM1OA  {
TY_pv8LHGd6Yei89cd2Rd8hv8g size;
TY_0zChuivuFV72gZwz2rUkHA seek;
TY_i5pcx3FBdKHMUS2uvRgvYw read;
TY_i5pcx3FBdKHMUS2uvRgvYw write;
TY_LaZp89cSat1m2LqumdMScDw close;
int kind;
Mem_Y7I9bNHWVNgY3LblplAgArw mem;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
TNimType NTI_Ye8PLO8qqXk1tek2VP9c0UQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
TNimType NTI_sOGmuBWrSv9c4mZ0oaW1R1w_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
TNimType NTI_xqbq9cabb4AcV4cRzuGg5Dg_;
TNimType NTI_D3H7z9cPmFr0tk2z8jKdcYg_;
TNimType NTI_Xo4YhcsfLAmbGDNu1Obfcw_;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_2ihZLdKnsQnDxl4WrWVtuw_;
TNimType NTI_OuNVER9cCktaUFzN15X6J2g_;
TNimType NTI_bN9bddWn8oiNSHn2MqEJSZQ_;
TNimType NTI_FxvFcOeClDHFdw9bGhJCSdg_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_uPOUAQyskDVXmxvDq3Wk3g_;
TNimType NTI_b9aNkg9b2aue9bOhT1uu43DYg_;
TNimType NTI_RHOlqbW8lSkSefXk1XWVIw_;
static void* TM_ZcjcXgoBjElsmUGY1Ljosg_7;
TY_9br0blXFlJAjbk9cGDwi8EgA Dl_319058_;
TY_OlsILfsIzW9b2h6RP9cRx1pQ Dl_319168_;
TY_09bvyvHFtWbkzL5AHgf0bKw Dl_319654_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_ZBJ5GRli6YRWUmwPMxvXiw Dl_319397_;
TY_8bKtXZcxYnKUJLFwBU2xmw Dl_319485_;
TY_6jJGBhZP5UsQBecZAlW9bUg Dl_319488_;
TY_24AcZiuGxj9aAIKC1Z9aBKgw Dl_319476_;
TY_J1PDbNq7uKOgh20mdTxcDg Dl_319464_;
TY_vfBise28cLJJujY6ZnHPIw Dl_318904_;
TY_EH6q2UEpsQbudAOirVaRhQ Dl_318882_;
TY_BzAZji9bzvN1k9ae25rIlb8A Dl_318617_;
TY_zHpDbFN4o9bvP9cAphXAUHXg Dl_319017_;
TY_wbFMpEnGfJo5HTFBx413GA Dl_318988_;
TY_9a8AalbnAaIxTUMpzQQqpjw Dl_319036_;
TY_CGFSM2Hc7U0HyNmEEh3xng Dl_319403_;
TY_gk5XfBB59a479c3sEPSMZUOg Dl_319189_;
TY_jhdVmRFWTpNd1iR9aS9c5hQQ Dl_319048_;
TY_zQuulNED1MWFt3geigWzvg Dl_319028_;
TY_qBZJbpNSUKmN7D9cXKfuoeg Dl_319069_;
TY_yLg9aKhE9aoiOkMB0pzXMlyg Dl_319516_;
TY_V9bZBkxVuJzbGuMjLg1FVUw Dl_318719_;
TY_3xgAKCPZlTDmyFCl87eZgg Dl_318826_;
TY_kIyA9c9bffk59bCZDzZS0sc8g Dl_319696_;
TY_FdNQc14l0KrdlpQKlTQjEA Dl_318606_;
TY_qINgM1UYlIsWdn51nn0qrQ Dl_318704_;
TY_gHZVvnv6jeg9cI9brLoWECJw Dl_319534_;
TY_m9cok4JvX7n8tIbkphyvkhw Dl_318670_;
TY_b9aXpKFbsyZ0PIk3aYRVCAA Dl_319605_;
TY_wFKHMJeFuSq6GTOGu9c9ayaw Dl_318673_;
TY_J5qn9cllF8g9bqRSS9bVM9avbw Dl_319708_;
TY_WLF2LPFZnB469bJx7k0rQDg Dl_319087_;
TY_CS9bxA1KE4RHFQ1vMCkCBmg Dl_320006_;
TY_fvOXafK39cW5YZA9b9bzinu9cw Dl_318765_;
TY_09bvyvHFtWbkzL5AHgf0bKw Dl_318789_;
TY_LR0DuTVmiHsWUuG5hbpBOQ Dl_318791_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_318777_;
TY_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_319356_;
TY_eGPD9aEHv9b8sVQMCQaPsYkg Dl_318811_;
TY_CWVVjvObnKbXecMOP3ypVQ Dl_319578_;
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_9, "libSDL2.dylib", 13);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_10, "libSDL2.dylib", 13);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_61, "contains({MouseWheel}, event312407.kind) ", 41);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_64, "contains({MouseButtonDown, MouseButtonUp}, event312007.kind) ", 61);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_65, "contains({ControllerDeviceAdded, ControllerDeviceRemoved}, even"
"t315607.kind) ", 77);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_66, "contains({ControllerButtonDown, ControllerButtonUp}, event31520"
"7.kind) ", 71);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_67, "contains({ControllerAxisMotion}, event314807.kind) ", 51);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_68, "contains({WindowEvent}, event310086.kind) ", 42);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_69, "contains({KeyDown, KeyUp}, event310407.kind) ", 45);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_CDECL(TY_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h) {
	TY_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("rect", "sdl2.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(1766, "sdl2.nim");
	result.Field0 = x;
	nimln_(1767, "sdl2.nim");
	result.Field1 = y;
	nimln_(1768, "sdl2.nim");
	result.Field2 = w;
	nimln_(1769, "sdl2.nim");
	result.Field3 = h;
	popFrame();
	return result;
}

N_NIMCALL(int, toCint_HzAk6ilB5r7Uod8u4Tk9bdA)(TextureAccess_lHfWejC67dkj9bzL3rlYUdw some) {
	int result;
	nimfr_("toCint", "sdl2.nim")
	result = (int)0;
	nimln_(332, "sdl2.nim");
	result = ((int) (some));
	popFrame();
	return result;
}

N_NIMCALL(MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg*, wheel_yMsteBccSbJ6JRFkjgZ9c4g)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg* result;
	nimfr_("wheel", "sdl2.nim")
{	result = (MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1027)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_61));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw*, button_PDS8usS8SPsAbtV7QDFnVQ)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw* result;
	nimfr_("button", "sdl2.nim")
{	result = (MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1025) || (*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1026)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_64));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((MouseButtonEventObj_ahKE9c3Zfqc3CPLu4G61DYw*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg*, cdevice_3m9aAR1Sx5O3229bognx7NQQ)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg* result;
	nimfr_("cdevice", "sdl2.nim")
{	result = (ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1619) || (*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1620)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_65));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((ControllerDeviceEventObj_bJ8BUI9cpm49brtlN8sw6C9cg*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg*, cbutton_3ZbzWxKNDIWOAVSYxE6n1Q)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg* result;
	nimfr_("cbutton", "sdl2.nim")
{	result = (ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1617) || (*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1618)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_66));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((ControllerButtonEventObj_iK49bb6NrW4W2tmwGPEnoEg*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw*, caxis_RK85I44RdqiHvaxwpFbCmQ)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw* result;
	nimfr_("caxis", "sdl2.nim")
{	result = (ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1616)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_67));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((ControllerAxisEventObj_9cAGKChsgWcmSe2jRpXieaw*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*, window_nUyoCwcDawc7wu1noDcQag)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	WindowEventObj_d6XCemaEKzK59bxf1YxrwlA* result;
	nimfr_("window", "sdl2.nim")
{	result = (WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 512)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_68));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*, key_Sy9cYLza36NW1QN9asfW9a0LA)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* result;
	nimfr_("key", "sdl2.nim")
{	result = (KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 768) || (*event).kind == ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 769)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_69));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(int, toInt_9c19cb3na8BCUkuR8QEzk7wA)(Keymod_Ezy2rGsnAFwkomNIvFNZ1A some) {
	int result;
	nimfr_("toInt", "keycodes.nim")
	result = (int)0;
	nimln_(391, "keycodes.nim");
	result = ((int) (some));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(Bool32_lrv4aZgVTmBUYdrYUkLMlg some) {
	NIM_BOOL result;
	nimfr_("toBool", "sdl2.nim")
	result = (NIM_BOOL)0;
	nimln_(330, "sdl2.nim");
	result = ((NIM_BOOL) (some));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void) {
	Event_Uzh9aP43ffUpM9aa6vZvNEug T1_;
	nimfr_("sdl2", "sdl2.nim")
	nimln_(1800, "sdl2.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.kind = ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256);
	defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ = T1_;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void) {
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_2[4];
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_3[12];
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_4[19];
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_5[4];
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_6[4];
static TNimNode TM_ZcjcXgoBjElsmUGY1Ljosg_0[49];
NTI_Ye8PLO8qqXk1tek2VP9c0UQ_.size = sizeof(TY_Ye8PLO8qqXk1tek2VP9c0UQ);
NTI_Ye8PLO8qqXk1tek2VP9c0UQ_.kind = 18;
NTI_Ye8PLO8qqXk1tek2VP9c0UQ_.base = 0;
NTI_Ye8PLO8qqXk1tek2VP9c0UQ_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_2[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[1];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].offset = offsetof(TY_Ye8PLO8qqXk1tek2VP9c0UQ, Field0);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].name = "Field0";
TM_ZcjcXgoBjElsmUGY1Ljosg_2[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[2];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[2].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[2].offset = offsetof(TY_Ye8PLO8qqXk1tek2VP9c0UQ, Field1);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[2].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[2].name = "Field1";
TM_ZcjcXgoBjElsmUGY1Ljosg_2[2] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[3];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[3].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[3].offset = offsetof(TY_Ye8PLO8qqXk1tek2VP9c0UQ, Field2);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[3].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[3].name = "Field2";
TM_ZcjcXgoBjElsmUGY1Ljosg_2[3] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[4];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[4].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[4].offset = offsetof(TY_Ye8PLO8qqXk1tek2VP9c0UQ, Field3);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[4].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[4].name = "Field3";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].len = 4; TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_2[0];
NTI_Ye8PLO8qqXk1tek2VP9c0UQ_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[0];
NTI_sOGmuBWrSv9c4mZ0oaW1R1w_.size = sizeof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w);
NTI_sOGmuBWrSv9c4mZ0oaW1R1w_.kind = 18;
NTI_sOGmuBWrSv9c4mZ0oaW1R1w_.base = 0;
NTI_sOGmuBWrSv9c4mZ0oaW1R1w_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_3[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[6];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[6].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[6].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, flags);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[6].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[6].name = "flags";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[7];
NTI_xqbq9cabb4AcV4cRzuGg5Dg_.size = sizeof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg);
NTI_xqbq9cabb4AcV4cRzuGg5Dg_.kind = 18;
NTI_xqbq9cabb4AcV4cRzuGg5Dg_.base = 0;
NTI_xqbq9cabb4AcV4cRzuGg5Dg_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_4[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[9];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[9].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[9].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, format);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[9].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[9].name = "format";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[10];
NTI_D3H7z9cPmFr0tk2z8jKdcYg_.size = sizeof(Palette_D3H7z9cPmFr0tk2z8jKdcYg);
NTI_D3H7z9cPmFr0tk2z8jKdcYg_.kind = 18;
NTI_D3H7z9cPmFr0tk2z8jKdcYg_.base = 0;
NTI_D3H7z9cPmFr0tk2z8jKdcYg_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_5[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[12];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[12].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[12].offset = offsetof(Palette_D3H7z9cPmFr0tk2z8jKdcYg, ncolors);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[12].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[12].name = "ncolors";
TM_ZcjcXgoBjElsmUGY1Ljosg_5[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[13];
NTI_Xo4YhcsfLAmbGDNu1Obfcw_.size = sizeof(TY_Xo4YhcsfLAmbGDNu1Obfcw);
NTI_Xo4YhcsfLAmbGDNu1Obfcw_.kind = 18;
NTI_Xo4YhcsfLAmbGDNu1Obfcw_.base = 0;
NTI_Xo4YhcsfLAmbGDNu1Obfcw_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_6[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[15];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[15].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[15].offset = offsetof(TY_Xo4YhcsfLAmbGDNu1Obfcw, Field0);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[15].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[15].name = "Field0";
TM_ZcjcXgoBjElsmUGY1Ljosg_6[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[16];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[16].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[16].offset = offsetof(TY_Xo4YhcsfLAmbGDNu1Obfcw, Field1);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[16].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[16].name = "Field1";
TM_ZcjcXgoBjElsmUGY1Ljosg_6[2] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[17];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[17].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[17].offset = offsetof(TY_Xo4YhcsfLAmbGDNu1Obfcw, Field2);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[17].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[17].name = "Field2";
TM_ZcjcXgoBjElsmUGY1Ljosg_6[3] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[18];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[18].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[18].offset = offsetof(TY_Xo4YhcsfLAmbGDNu1Obfcw, Field3);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[18].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[18].name = "Field3";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[14].len = 4; TM_ZcjcXgoBjElsmUGY1Ljosg_0[14].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[14].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_6[0];
NTI_Xo4YhcsfLAmbGDNu1Obfcw_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[14];
NTI_2ihZLdKnsQnDxl4WrWVtuw_.size = sizeof(TY_Xo4YhcsfLAmbGDNu1Obfcw*);
NTI_2ihZLdKnsQnDxl4WrWVtuw_.kind = 21;
NTI_2ihZLdKnsQnDxl4WrWVtuw_.base = (&NTI_Xo4YhcsfLAmbGDNu1Obfcw_);
NTI_2ihZLdKnsQnDxl4WrWVtuw_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[13].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[13].offset = offsetof(Palette_D3H7z9cPmFr0tk2z8jKdcYg, colors);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[13].typ = (&NTI_2ihZLdKnsQnDxl4WrWVtuw_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[13].name = "colors";
TM_ZcjcXgoBjElsmUGY1Ljosg_5[2] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[19];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[19].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[19].offset = offsetof(Palette_D3H7z9cPmFr0tk2z8jKdcYg, version);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[19].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[19].name = "version";
TM_ZcjcXgoBjElsmUGY1Ljosg_5[3] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[20];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[20].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[20].offset = offsetof(Palette_D3H7z9cPmFr0tk2z8jKdcYg, refcount);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[20].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[20].name = "refcount";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[11].len = 4; TM_ZcjcXgoBjElsmUGY1Ljosg_0[11].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[11].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_5[0];
NTI_D3H7z9cPmFr0tk2z8jKdcYg_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[11];
NTI_OuNVER9cCktaUFzN15X6J2g_.size = sizeof(Palette_D3H7z9cPmFr0tk2z8jKdcYg*);
NTI_OuNVER9cCktaUFzN15X6J2g_.kind = 21;
NTI_OuNVER9cCktaUFzN15X6J2g_.base = (&NTI_D3H7z9cPmFr0tk2z8jKdcYg_);
NTI_OuNVER9cCktaUFzN15X6J2g_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[10].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[10].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, palette);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[10].typ = (&NTI_OuNVER9cCktaUFzN15X6J2g_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[10].name = "palette";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[2] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[21];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[21].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[21].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, BitsPerPixel);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[21].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[21].name = "BitsPerPixel";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[3] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[22];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[22].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[22].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, BytesPerPixel);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[22].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[22].name = "BytesPerPixel";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[4] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[23];
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.size = sizeof(TY_bN9bddWn8oiNSHn2MqEJSZQ);
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.kind = 16;
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[23].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[23].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, padding);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[23].typ = (&NTI_bN9bddWn8oiNSHn2MqEJSZQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[23].name = "padding";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[5] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[24];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[24].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[24].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Rmask);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[24].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[24].name = "Rmask";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[6] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[25];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[25].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[25].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Gmask);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[25].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[25].name = "Gmask";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[7] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[26];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[26].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[26].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Bmask);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[26].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[26].name = "Bmask";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[8] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[27];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[27].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[27].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Amask);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[27].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[27].name = "Amask";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[9] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[28];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[28].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[28].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Rloss);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[28].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[28].name = "Rloss";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[10] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[29];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[29].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[29].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Gloss);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[29].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[29].name = "Gloss";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[11] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[30];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[30].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[30].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Bloss);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[30].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[30].name = "Bloss";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[12] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[31];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[31].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[31].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Aloss);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[31].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[31].name = "Aloss";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[13] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[32];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[32].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[32].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Rshift);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[32].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[32].name = "Rshift";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[14] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[33];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[33].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[33].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Gshift);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[33].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[33].name = "Gshift";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[15] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[34];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[34].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[34].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Bshift);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[34].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[34].name = "Bshift";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[16] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[35];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[35].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[35].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, Ashift);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[35].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[35].name = "Ashift";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[17] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[36];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[36].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[36].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, refcount);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[36].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[36].name = "refcount";
TM_ZcjcXgoBjElsmUGY1Ljosg_4[18] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[37];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[37].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[37].offset = offsetof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg, next);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[37].typ = (&NTI_FxvFcOeClDHFdw9bGhJCSdg_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[37].name = "next";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[8].len = 19; TM_ZcjcXgoBjElsmUGY1Ljosg_0[8].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[8].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_4[0];
NTI_xqbq9cabb4AcV4cRzuGg5Dg_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[8];
NTI_FxvFcOeClDHFdw9bGhJCSdg_.size = sizeof(PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg*);
NTI_FxvFcOeClDHFdw9bGhJCSdg_.kind = 21;
NTI_FxvFcOeClDHFdw9bGhJCSdg_.base = (&NTI_xqbq9cabb4AcV4cRzuGg5Dg_);
NTI_FxvFcOeClDHFdw9bGhJCSdg_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[7].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[7].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, format);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[7].typ = (&NTI_FxvFcOeClDHFdw9bGhJCSdg_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[7].name = "format";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[2] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[38];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[38].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[38].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, w);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[38].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[38].name = "w";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[3] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[39];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[39].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[39].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, h);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[39].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[39].name = "h";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[4] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[40];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[40].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[40].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, pitch);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[40].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[40].name = "pitch";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[5] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[41];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[41].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[41].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, pixels);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[41].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[41].name = "pixels";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[6] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[42];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[42].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[42].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, userdata);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[42].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[42].name = "userdata";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[7] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[43];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[43].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[43].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, locked);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[43].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[43].name = "locked";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[8] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[44];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[44].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[44].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, lock_data);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[44].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[44].name = "lock_data";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[9] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[45];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[45].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[45].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, clip_rect);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[45].typ = (&NTI_Ye8PLO8qqXk1tek2VP9c0UQ_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[45].name = "clip_rect";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[10] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[46];
NTI_uPOUAQyskDVXmxvDq3Wk3g_.size = sizeof(BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g);
NTI_uPOUAQyskDVXmxvDq3Wk3g_.kind = 18;
NTI_uPOUAQyskDVXmxvDq3Wk3g_.base = 0;
NTI_uPOUAQyskDVXmxvDq3Wk3g_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].len = 0; TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].kind = 2;
NTI_uPOUAQyskDVXmxvDq3Wk3g_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[47];
NTI_b9aNkg9b2aue9bOhT1uu43DYg_.size = sizeof(BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g*);
NTI_b9aNkg9b2aue9bOhT1uu43DYg_.kind = 21;
NTI_b9aNkg9b2aue9bOhT1uu43DYg_.base = (&NTI_uPOUAQyskDVXmxvDq3Wk3g_);
NTI_b9aNkg9b2aue9bOhT1uu43DYg_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, map);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].typ = (&NTI_b9aNkg9b2aue9bOhT1uu43DYg_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].name = "map";
TM_ZcjcXgoBjElsmUGY1Ljosg_3[11] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[48];
TM_ZcjcXgoBjElsmUGY1Ljosg_0[48].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[48].offset = offsetof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w, refcount);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[48].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[48].name = "refcount";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[5].len = 12; TM_ZcjcXgoBjElsmUGY1Ljosg_0[5].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[5].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_3[0];
NTI_sOGmuBWrSv9c4mZ0oaW1R1w_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[5];
NTI_RHOlqbW8lSkSefXk1XWVIw_.size = sizeof(Surface_sOGmuBWrSv9c4mZ0oaW1R1w*);
NTI_RHOlqbW8lSkSefXk1XWVIw_.kind = 21;
NTI_RHOlqbW8lSkSefXk1XWVIw_.base = (&NTI_sOGmuBWrSv9c4mZ0oaW1R1w_);
NTI_RHOlqbW8lSkSefXk1XWVIw_.flags = 3;
if (!((TM_ZcjcXgoBjElsmUGY1Ljosg_7 = nimLoadLibrary((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_9))
)) nimLoadLibraryError((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_10);
	Dl_319058_ = (TY_9br0blXFlJAjbk9cGDwi8EgA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CreateRGBSurfaceFrom");
	Dl_319168_ = (TY_OlsILfsIzW9b2h6RP9cRx1pQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_ConvertSurface");
	Dl_319654_ = (TY_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetError");
	Dl_319397_ = (TY_ZBJ5GRli6YRWUmwPMxvXiw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetTicks");
	Dl_319485_ = (TY_8bKtXZcxYnKUJLFwBU2xmw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetScancodeFromName");
	Dl_319488_ = (TY_6jJGBhZP5UsQBecZAlW9bUg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetKeyName");
	Dl_319476_ = (TY_24AcZiuGxj9aAIKC1Z9aBKgw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetKeyFromScancode");
	Dl_319464_ = (TY_J1PDbNq7uKOgh20mdTxcDg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetKeyboardState");
	Dl_318904_ = (TY_vfBise28cLJJujY6ZnHPIw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetRenderTarget");
	Dl_318882_ = (TY_EH6q2UEpsQbudAOirVaRhQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_UpdateTexture");
	Dl_318617_ = (TY_BzAZji9bzvN1k9ae25rIlb8A) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetRenderDrawColor");
	Dl_319017_ = (TY_zHpDbFN4o9bvP9cAphXAUHXg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RenderClear");
	Dl_318988_ = (TY_wbFMpEnGfJo5HTFBx413GA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RenderCopy");
	Dl_319036_ = (TY_9a8AalbnAaIxTUMpzQQqpjw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RenderPresent");
	Dl_319403_ = (TY_CGFSM2Hc7U0HyNmEEh3xng) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_Delay");
	Dl_319189_ = (TY_gk5XfBB59a479c3sEPSMZUOg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_FillRect");
	Dl_319048_ = (TY_jhdVmRFWTpNd1iR9aS9c5hQQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CreateRGBSurface");
	Dl_319028_ = (TY_zQuulNED1MWFt3geigWzvg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RenderReadPixels");
	Dl_319069_ = (TY_qBZJbpNSUKmN7D9cXKfuoeg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_FreeSurface");
	Dl_319516_ = (TY_yLg9aKhE9aoiOkMB0pzXMlyg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetMouseState");
	Dl_318719_ = (TY_V9bZBkxVuJzbGuMjLg1FVUw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetWindowFullscreen");
	Dl_318826_ = (TY_3xgAKCPZlTDmyFCl87eZgg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CreateTexture");
	Dl_319696_ = (TY_kIyA9c9bffk59bCZDzZS0sc8g) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetPaletteColors");
	Dl_318606_ = (TY_FdNQc14l0KrdlpQKlTQjEA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RenderSetLogicalSize");
	Dl_318704_ = (TY_qINgM1UYlIsWdn51nn0qrQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetWindowSize");
	Dl_319534_ = (TY_gHZVvnv6jeg9cI9brLoWECJw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CaptureMouse");
	Dl_318670_ = (TY_m9cok4JvX7n8tIbkphyvkhw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetWindowFlags");
	Dl_319605_ = (TY_b9aXpKFbsyZ0PIk3aYRVCAA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_PollEvent");
	Dl_318673_ = (TY_wFKHMJeFuSq6GTOGu9c9ayaw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetWindowTitle");
	Dl_319708_ = (TY_J5qn9cllF8g9bqRSS9bVM9avbw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_MapRGB");
	Dl_319087_ = (TY_WLF2LPFZnB469bJx7k0rQDg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_RWFromFile");
	Dl_320006_ = (TY_CS9bxA1KE4RHFQ1vMCkCBmg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_SetHint");
	Dl_318765_ = (TY_fvOXafK39cW5YZA9b9bzinu9cw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_Init");
	Dl_318789_ = (TY_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetBasePath");
	Dl_318791_ = (TY_LR0DuTVmiHsWUuG5hbpBOQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_GetPrefPath");
	Dl_318777_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_Quit");
	Dl_319356_ = (TY_1K9aSViCbSUpZMtRI9aw9a2Rg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CreateWindow");
	Dl_318811_ = (TY_eGPD9aEHv9b8sVQMCQaPsYkg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_CreateRenderer");
	Dl_319578_ = (TY_CWVVjvObnKbXecMOP3ypVQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_7, "SDL_ShowCursor");
}

