/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.0/nim/lib -o /Users/pakchoi/Workspace/campfire/src/nimcache/stdlib_parsecfg.o /Users/pakchoi/Workspace/campfire/src/nimcache/stdlib_parsecfg.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef linux
#undef near
typedef struct CfgParser_w8XFEe9aT1CBajTOt4fsMRA CfgParser_w8XFEe9aT1CBajTOt4fsMRA;
typedef struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct BaseLexer_B6cGbTPhMsqMovc9cOcIHRw BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Token_yWkcM1ijvGYnxTAxtl3FPw Token_yWkcM1ijvGYnxTAxtl3FPw;
typedef struct CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q;
typedef struct OrderedTable_mjwQ71q4DGaXE1Pub8TBoA OrderedTable_mjwQ71q4DGaXE1Pub8TBoA;
typedef struct TY_mHGoHNAjK33ocalUlelYmw TY_mHGoHNAjK33ocalUlelYmw;
typedef struct OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ;
typedef struct TY_bqJLe37YxdsvktE2rRmBQQ TY_bqJLe37YxdsvktE2rRmBQQ;
typedef struct TY_nhfI9cIYWItR5J3b9bMc2PFA TY_nhfI9cIYWItR5J3b9bMc2PFA;
typedef struct TY_UV3llMMYFckfui8YMBuUZA TY_UV3llMMYFckfui8YMBuUZA;
typedef struct TY_dl1tcid0VwP1mpWNDzitYw TY_dl1tcid0VwP1mpWNDzitYw;
typedef struct TY_pmSRO1HvsVFWcLoeG9bs4Yg TY_pmSRO1HvsVFWcLoeG9bs4Yg;
typedef struct FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Slice_qL3WGViqT0p5sVr4YFHsLg Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ;
typedef NU8 TY_nmiMWKVIe46vacnhAFrQvw_Set[32];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  BaseLexer_B6cGbTPhMsqMovc9cOcIHRw  {
  TNimObject Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
TY_nmiMWKVIe46vacnhAFrQvw_Set refillChars;
};
typedef NU8 TokKind_PvpTf9b5cBhdKx1DK5Ed3dg;
struct  Token_yWkcM1ijvGYnxTAxtl3FPw  {
TokKind_PvpTf9b5cBhdKx1DK5Ed3dg kind;
NimStringDesc* literal;
};
struct  CfgParser_w8XFEe9aT1CBajTOt4fsMRA  {
  BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
Token_yWkcM1ijvGYnxTAxtl3FPw tok;
NimStringDesc* filename;
};
typedef NimStringDesc* TY_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NU8 CfgEventKind_f0xwqI11H3rviaTXvjDJug;
struct  CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q  {
  TNimObject Sup;
CfgEventKind_f0xwqI11H3rviaTXvjDJug kind;
union{
struct {NimStringDesc* section;
} S2;
struct {NimStringDesc* key;
NimStringDesc* value;
} S3;
struct {NimStringDesc* msg;
} S4;
} kindU;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  OrderedTable_mjwQ71q4DGaXE1Pub8TBoA  {
TY_bqJLe37YxdsvktE2rRmBQQ* data;
NI counter;
NI first;
NI last;
};
struct TY_nhfI9cIYWItR5J3b9bMc2PFA {
NI Field0;
NI Field1;
NimStringDesc* Field2;
OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* Field3;
};
struct  OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ  {
TY_dl1tcid0VwP1mpWNDzitYw* data;
NI counter;
NI first;
NI last;
};
struct TY_pmSRO1HvsVFWcLoeG9bs4Yg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
typedef NU8 FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* TY_nHXaesL0DJZHyVS07ARPRA[1];
struct  Slice_qL3WGViqT0p5sVr4YFHsLg  {
NI a;
NI b;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct  StreamObj_RShkcoDOPnoCVhtpN1hDPQ  {
  TNimObject Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
TY_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
TY_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct  StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ  {
  StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
NimStringDesc* data;
NI pos;
};
struct TY_mHGoHNAjK33ocalUlelYmw {
NimStringDesc* Field0;
OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* Field1;
};
struct TY_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw  {
  StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct TY_bqJLe37YxdsvktE2rRmBQQ {
  TGenericSeq Sup;
  TY_nhfI9cIYWItR5J3b9bMc2PFA data[SEQ_DECL_SIZE];
};
struct TY_dl1tcid0VwP1mpWNDzitYw {
  TGenericSeq Sup;
  TY_pmSRO1HvsVFWcLoeG9bs4Yg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, npcopen)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NI lineOffset);
N_NIMCALL(void, open_xmgaYJZNnO6QcDtac9bs3Vg)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NI bufLen, TY_nmiMWKVIe46vacnhAFrQvw_Set refillChars);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, npcclose)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c);
N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_NIMCALL(NI, npcgetColumn)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c);
N_NIMCALL(NI, getColNumber_9cj186ckGjLqyndkoW7bBdg)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(NI, npcgetLine)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c);
N_NIMCALL(NimStringDesc*, npcgetFilename)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c);
N_NIMCALL(void, handleHexChar_3y12hqri4JTyxotOKMYUTw)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI* xi);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, handleDecChars_3y12hqri4JTyxotOKMYUTw_2)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI* xi);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, getEscapedChar_oP5V5zBaqBvjlLHmM9aR5HQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, handleCRLF_aTSjoKixs63H4oDAFX9bRHQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI pos);
N_NIMCALL(NI, handleCR_IwUEvMBOLRY9cqyar6XKEaw_2)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(NI, handleLF_IwUEvMBOLRY9cqyar6XKEaw_3)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(void, getString_kPdxas01T9chtV9cOXL7akew)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode);
N_NIMCALL(void, getSymbol_oP5V5zBaqBvjlLHmM9aR5HQ_2)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok);
N_NIMCALL(void, skip_AhN1A1FuhHZh69aN9cg2Os9cA)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c);
N_NIMCALL(void, rawGetTok_O0TCNNdqmVst7YIKcVHcOQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NimStringDesc*, npcerrorStr)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, npcwarningStr)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, npcignoreMsg)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* e);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, getKeyValPair_wU9bLoPwmfHqL352Lwkk0kA)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEventKind_f0xwqI11H3rviaTXvjDJug kind, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* Result);
N_NIMCALL(void, FieldDiscriminantCheck)(NI oldDiscVal, NI newDiscVal, TNimNode** a, NI L);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, npcnext)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, newOrderedTable_kI9avJX0pn2OsRj3l0p70QQ)(NI initialSize);
N_NIMCALL(void, initOrderedTable_mqGqfe6l2Ot4l1B0bpBJ0g)(NI initialSize, OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* Result);
N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, newOrderedTable_bms2N7c66GSbeZlIJl6usg)(TY_mHGoHNAjK33ocalUlelYmw* pairs, NI pairsLen_0);
N_NIMCALL(void, add_vY5zyZwuf0SpXyorOkqQCg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* val);
N_NIMCALL(void, add_fLJ5dBr0pzanNkDI2ENDRw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* val);
N_NIMCALL(void, enlarge_z5btJgUO9aHsUG0Z4eOyFlQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t);
N_NIMCALL(NI, rawGetKnownHC_zn11WU7fHzI9b6InMU39cnYw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawInsert_C9b79aDO8rmMthUei7fmcr3w)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, TY_bqJLe37YxdsvktE2rRmBQQ** data, NimStringDesc* key, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_KEl4Q0aIVF3m8CuRfASJVAtables)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, newConfig_Afv7qS60mn8mdc3HRBrzHA)(void);
N_NIMCALL(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ*, newOrderedTable_8wX2B22l1w9bbsrSuaZolwQ)(NI initialSize);
N_NIMCALL(void, initOrderedTable_LCfZONX7VeYWP9bqPVWEyDA)(NI initialSize, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* Result);
N_NIMCALL(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ*, newOrderedTable_RftIyflwGh9bjSvWxUdtXxQ)(TY_UV3llMMYFckfui8YMBuUZA* pairs, NI pairsLen_0);
N_NIMCALL(void, add_X7zbF3UXb9beC6mdDvbm7yQ)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, add_3aEsc7Jl9bCBkDaKtTKXACQ)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, enlarge_u7J6P9c70hku6hy84T6UD3A)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t);
N_NIMCALL(NI, rawGetKnownHC_gvbfG8kUnZ9bMmEhxoEjPQA)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawInsert_o0G2OgABY9aRusuyDRuTP0w)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, TY_dl1tcid0VwP1mpWNDzitYw** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_uYmQ5SD89aRmmSv3V1LJIewtables)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI* hc);
N_NIMCALL(NIM_BOOL, hasKey_QXMvqDynw9acW1siAbeTY1g)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key);
N_NIMCALL(NIM_BOOL, hasKey_QaBV6JIBgr6OKNTCEzmYnQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key);
N_NIMCALL(NI, rawGet_sYLElk2bQ5gQh3D9aLNmNKw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI* hc);
N_NIMCALL(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**, X5BX5D__6wUGmv25FDZ9c5o48wpNMyg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key);
N_NIMCALL(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**, X5BX5D__vU9budBTAe4Um5Hw9c3JNGMw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key);
static N_INLINE(NI, rawGet_KEl4Q0aIVF3m8CuRfASJVA_2tables)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI* hc);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, X5BX5Deq__X7zbF3UXb9beC6mdDvbm7yQ_2)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, X5BX5Deq__3aEsc7Jl9bCBkDaKtTKXACQ_2)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NI, rawGet_K0D4LHTrXdUWS5pFcPolVg)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI* hc);
N_NIMCALL(void, X5BX5Deq__vY5zyZwuf0SpXyorOkqQCg_2)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* val);
N_NIMCALL(void, X5BX5Deq__fLJ5dBr0pzanNkDI2ENDRw_2)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* val);
N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, loadConfig_P9biP5fyx9bLJK29aESwkIRBA)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream, NimStringDesc* filename);
N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, loadConfig_sAs1zICpXe0t2WsYDGJLHA)(NimStringDesc* filename);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_j9aOzR9a9bXMSUnTXiGmXXGqQ)(FILE* f);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, replace_YSAU1uzU2PmXN4yWDJB9a1Q)(NimStringDesc* s);
N_NIMCALL(void, writeConfig_fwJshzcWuYNR7DAGOpxrvQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream);
N_NIMCALL(NIM_BOOL, allCharsInSet_wVfr4F6j4mVzI8ggLoMVdw)(NimStringDesc* s, TY_nmiMWKVIe46vacnhAFrQvw_Set theSet);
N_NIMCALL(void, writeLine_G1TKFmud9akiH9bzSHWMshag_2)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc** args, NI argsLen_0);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
N_NIMCALL(NimStringDesc*, dollar__Jw6uJyteAGBUfezZp9aQY1w)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict);
N_NIMCALL(StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ*, newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ)(NimStringDesc* s);
N_NIMCALL(void, writeConfig_AVb38iG6BzScmMQ65OXTHQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, NimStringDesc* filename);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(NIM_BOOL, hasKey_iW9aP1lP6iKnI2P9aTldk9a0w)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key);
N_NIMCALL(NIM_BOOL, hasKey_rI68G328cu8RYWWb6HNz2Q)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc**, X5BX5D__Wk7VKmSqT9bZiMZK9aBX5qtA)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc**, X5BX5D__mZmJ6JSMWw6Hjn0s2Bqb2Q)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key);
static N_INLINE(NI, rawGet_uYmQ5SD89aRmmSv3V1LJIew_2tables)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI* hc);
N_NIMCALL(NimStringDesc*, getSectionValue_eZ9bxHq9ckUeG07mAVDw3Gxg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, NimStringDesc* section, NimStringDesc* key);
N_NIMCALL(void, setSectionKey_XIb40Iom9bg27l7JWaBAxzw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section, NimStringDesc* key, NimStringDesc* value);
N_NIMCALL(void, del_9cIgyzt9cdEVWVfyq09cZpR9bg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** t, NimStringDesc* key);
N_NIMCALL(void, del_bykJuDHTgRzNF425K0Kg9aw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key);
N_NIMCALL(void, delSection_7eGHbl1hh7Q06GxLuf8JFg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section);
static N_INLINE(NI, len_3w9b2vhzm6CE22tViP9bI9bIAparsecfg)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t);
N_NIMCALL(void, del_W69atDwFX0MX1ZCHAtMBCfw)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** t, NimStringDesc* key);
N_NIMCALL(void, del_SGvMrR9bG1RqEZiZ8DSLiHg)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key);
N_NIMCALL(void, delSectionKey_Pth9bkRuImc22OwfXlMtLsg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section, NimStringDesc* key);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_;
TNimType NTI_f0xwqI11H3rviaTXvjDJug_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimNode* NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[6];
extern TNimType NTI_B6cGbTPhMsqMovc9cOcIHRw_;
TNimType NTI_w8XFEe9aT1CBajTOt4fsMRA_;
TNimType NTI_yWkcM1ijvGYnxTAxtl3FPw_;
TNimType NTI_PvpTf9b5cBhdKx1DK5Ed3dg_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set SymChars_ITh742d7l9cVdtyHGyLiq5A = {
0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x97, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
static NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_2 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3, "", 0);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_18, "\012", 1);
static NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_42 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x97, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_46, "=", 1);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_49, "--", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_51, ":", 1);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_55, "]", 1);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_57, "[EOF]", 5);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_58, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_59, "$1($2, $3) Warning: $4", 22);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_60, "section ignored: ", 17);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_61, "section", 7);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_62, "key ignored: ", 13);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63, "key", 3);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_64, "command ignored: ", 17);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_65, ": ", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66, "value", 5);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67, "msg", 3);
TNimNode* NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[6];
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_72, "symbol expected, but found: ", 28);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_73, "\']\' expected, but found: ", 25);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_74, "invalid token: ", 15);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_83, "\\\\", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_85, "\\n", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_88, "[\"", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_89, "\"]", 2);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_90, "[", 1);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_92, "--\"", 3);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_94, "\"", 1);
STRING_LITERAL(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_95, "\"\"\"", 3);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, npcopen)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NI lineOffset) {
	BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_4;
	nimfr_("open", "parsecfg.nim")
	nimln_(143, "parsecfg.nim");
	T1_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &c->Sup;
	open_xmgaYJZNnO6QcDtac9bs3Vg(T1_, input, ((NI) 8192), TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_2);
	nimln_(144, "parsecfg.nim");
	unsureAsgnRef((void**) (&(*c).filename), copyString(filename));
	nimln_(145, "parsecfg.nim");
	(*c).tok.kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	nimln_(146, "parsecfg.nim");
	unsureAsgnRef((void**) (&(*c).tok.literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3)));
	nimln_(147, "parsecfg.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_4 = addInt((*c).Sup.lineNumber, lineOffset);
	(*c).Sup.lineNumber = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_4);
	nimln_(148, "parsecfg.nim");
	rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
	popFrame();
}

N_NIMCALL(void, npcclose)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c) {
	BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsecfg.nim")
	nimln_(152, "parsecfg.nim");
	T1_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &c->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

N_NIMCALL(NI, npcgetColumn)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c) {
	NI result;
	nimfr_("getColumn", "parsecfg.nim")
	result = (NI)0;
	nimln_(156, "parsecfg.nim");
	result = getColNumber_9cj186ckGjLqyndkoW7bBdg((&(*c).Sup), (*c).Sup.bufpos);
	popFrame();
	return result;
}

N_NIMCALL(NI, npcgetLine)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c) {
	NI result;
	nimfr_("getLine", "parsecfg.nim")
	result = (NI)0;
	nimln_(160, "parsecfg.nim");
	result = (*c).Sup.lineNumber;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, npcgetFilename)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c) {
	NimStringDesc* result;
	nimfr_("getFilename", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(164, "parsecfg.nim");
	result = copyString((*c).filename);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, handleHexChar_3y12hqri4JTyxotOKMYUTw)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI* xi) {
	nimfr_("handleHexChar", "parsecfg.nim")
	nimln_(167, "parsecfg.nim");
	switch (((NU8)((*c).Sup.buf[(*c).Sup.bufpos]))) {
	case 48 ... 57:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_5;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_6;
		nimln_(169, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_5 = subInt(((NI) (((NU8)((*c).Sup.buf[(*c).Sup.bufpos])))), ((NI) 48));
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_5))));
		nimln_(170, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_6 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_6);
	}
	break;
	case 97 ... 102:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_7;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_8;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_9;
		nimln_(172, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_7 = subInt(((NI) (((NU8)((*c).Sup.buf[(*c).Sup.bufpos])))), ((NI) 97));
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_8 = addInt(((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_7))), ((NI) 10));
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_8))));
		nimln_(173, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_9 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_9);
	}
	break;
	case 65 ... 70:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_10;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_11;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_12;
		nimln_(175, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_10 = subInt(((NI) (((NU8)((*c).Sup.buf[(*c).Sup.bufpos])))), ((NI) 65));
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_11 = addInt(((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_10))), ((NI) 10));
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_11))));
		nimln_(176, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_12 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_12);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, handleDecChars_3y12hqri4JTyxotOKMYUTw_2)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI* xi) {
	nimfr_("handleDecChars", "parsecfg.nim")
	{
		nimln_(181, "parsecfg.nim");
		while (1) {
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_13;
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_14;
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_15;
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_16;
			if (!(((NU8)((*c).Sup.buf[(*c).Sup.bufpos])) >= ((NU8)(48)) && ((NU8)((*c).Sup.buf[(*c).Sup.bufpos])) <= ((NU8)(57)))) goto LA2;
			nimln_(182, "parsecfg.nim");
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_13 = mulInt((*xi), ((NI) 10));
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_14 = subInt(((NI) (((NU8)((*c).Sup.buf[(*c).Sup.bufpos])))), ((NI) 48));
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_15 = addInt((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_13), ((NI) ((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_14))));
			(*xi) = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_15);
			nimln_(183, "parsecfg.nim");
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_16 = addInt((*c).Sup.bufpos, ((NI) 1));
			(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_16);
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, getEscapedChar_oP5V5zBaqBvjlLHmM9aR5HQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok) {
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_17;
	nimfr_("getEscapedChar", "parsecfg.nim")
	nimln_(186, "parsecfg.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_17 = addInt((*c).Sup.bufpos, ((NI) 1));
	(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_17);
	nimln_(187, "parsecfg.nim");
	switch (((NU8)((*c).Sup.buf[(*c).Sup.bufpos]))) {
	case 110:
	case 78:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_19;
		nimln_(189, "parsecfg.nim");
		(*tok).literal = resizeString((*tok).literal, 1);
appendString((*tok).literal, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_18));
		nimln_(190, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_19 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_19);
	}
	break;
	case 114:
	case 82:
	case 99:
	case 67:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_20;
		nimln_(192, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 13);
		nimln_(193, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_20 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_20);
	}
	break;
	case 108:
	case 76:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_21;
		nimln_(195, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 10);
		nimln_(196, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_21 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_21);
	}
	break;
	case 102:
	case 70:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_22;
		nimln_(198, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 12);
		nimln_(199, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_22 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_22);
	}
	break;
	case 101:
	case 69:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_23;
		nimln_(201, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 27);
		nimln_(202, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_23 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_23);
	}
	break;
	case 97:
	case 65:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_24;
		nimln_(204, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 7);
		nimln_(205, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_24 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_24);
	}
	break;
	case 98:
	case 66:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_25;
		nimln_(207, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 8);
		nimln_(208, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_25 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_25);
	}
	break;
	case 118:
	case 86:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_26;
		nimln_(210, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 11);
		nimln_(211, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_26 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_26);
	}
	break;
	case 116:
	case 84:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_27;
		nimln_(213, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 9);
		nimln_(214, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_27 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_27);
	}
	break;
	case 39:
	case 34:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_28;
		nimln_(216, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, (*c).Sup.buf[(*c).Sup.bufpos]);
		nimln_(217, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_28 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_28);
	}
	break;
	case 92:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_29;
		nimln_(219, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, 92);
		nimln_(220, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_29 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_29);
	}
	break;
	case 120:
	case 88:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_30;
		NI xi;
		nimln_(222, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_30 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_30);
		nimln_(223, "parsecfg.nim");
		xi = ((NI) 0);
		nimln_(224, "parsecfg.nim");
		handleHexChar_3y12hqri4JTyxotOKMYUTw(c, (&xi));
		nimln_(225, "parsecfg.nim");
		handleHexChar_3y12hqri4JTyxotOKMYUTw(c, (&xi));
		nimln_(226, "parsecfg.nim");
		(*tok).literal = addChar((*tok).literal, ((NIM_CHAR) (((NI)chckRange(xi, ((NI) 0), ((NI) 255))))));
	}
	break;
	case 48 ... 57:
	{
		NI xi_2;
		nimln_(228, "parsecfg.nim");
		xi_2 = ((NI) 0);
		nimln_(229, "parsecfg.nim");
		handleDecChars_3y12hqri4JTyxotOKMYUTw_2(c, (&xi_2));
		nimln_(230, "parsecfg.nim");
		{
			if (!(xi_2 <= ((NI) 255))) goto LA16_;
			(*tok).literal = addChar((*tok).literal, ((NIM_CHAR) (((NI)chckRange(xi_2, ((NI) 0), ((NI) 255))))));
		}
		goto LA14_;
		LA16_: ;
		{
			nimln_(231, "parsecfg.nim");
			(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
		}
		LA14_: ;
	}
	break;
	default:
	{
		nimln_(232, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, handleCRLF_aTSjoKixs63H4oDAFX9bRHQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NI pos) {
	NI result;
	nimfr_("handleCRLF", "parsecfg.nim")
	result = (NI)0;
	nimln_(235, "parsecfg.nim");
	switch (((NU8)((*c).Sup.buf[pos]))) {
	case 13:
	{
		BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T2_;
		nimln_(236, "parsecfg.nim");
		T2_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
		T2_ = &c->Sup;
		result = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T2_, pos);
	}
	break;
	case 10:
	{
		BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T4_;
		nimln_(237, "parsecfg.nim");
		T4_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
		T4_ = &c->Sup;
		result = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T4_, pos);
	}
	break;
	default:
	{
		nimln_(238, "parsecfg.nim");
		result = pos;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, getString_kPdxas01T9chtV9cOXL7akew)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode) {
	NI pos;
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_31;
	NCSTRING buf;
	nimfr_("getString", "parsecfg.nim")
	nimln_(241, "parsecfg.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_31 = addInt((*c).Sup.bufpos, ((NI) 1));
	pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_31);
	nimln_(242, "parsecfg.nim");
	buf = (*c).Sup.buf;
	nimln_(243, "parsecfg.nim");
	(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2);
	nimln_(244, "parsecfg.nim");
	{
		NIM_BOOL T3_;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_32;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_33;
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_38;
		T3_ = (NIM_BOOL)0;
		T3_ = ((NU8)(buf[pos]) == (NU8)(34));
		if (!(T3_)) goto LA4_;
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_32 = addInt(pos, ((NI) 1));
		T3_ = ((NU8)(buf[(NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_32)]) == (NU8)(34));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(246, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_33 = addInt(pos, ((NI) 2));
		pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_33);
		nimln_(248, "parsecfg.nim");
		pos = handleCRLF_aTSjoKixs63H4oDAFX9bRHQ(c, pos);
		nimln_(249, "parsecfg.nim");
		buf = (*c).Sup.buf;
		{
			nimln_(250, "parsecfg.nim");
			while (1) {
				nimln_(251, "parsecfg.nim");
				switch (((NU8)(buf[pos]))) {
				case 34:
				{
					NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_36;
					nimln_(253, "parsecfg.nim");
					{
						NIM_BOOL T12_;
						NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_34;
						NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_35;
						T12_ = (NIM_BOOL)0;
						TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_34 = addInt(pos, ((NI) 1));
						T12_ = ((NU8)(buf[(NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_34)]) == (NU8)(34));
						if (!(T12_)) goto LA13_;
						TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_35 = addInt(pos, ((NI) 2));
						T12_ = ((NU8)(buf[(NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_35)]) == (NU8)(34));
						LA13_: ;
						if (!T12_) goto LA14_;
						goto LA7;
					}
					LA14_: ;
					nimln_(254, "parsecfg.nim");
					(*tok).literal = addChar((*tok).literal, 34);
					nimln_(255, "parsecfg.nim");
					TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_36 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_36);
				}
				break;
				case 13:
				case 10:
				{
					nimln_(257, "parsecfg.nim");
					pos = handleCRLF_aTSjoKixs63H4oDAFX9bRHQ(c, pos);
					nimln_(258, "parsecfg.nim");
					buf = (*c).Sup.buf;
					nimln_(259, "parsecfg.nim");
					(*tok).literal = resizeString((*tok).literal, 1);
appendString((*tok).literal, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_18));
				}
				break;
				case 0:
				{
					nimln_(261, "parsecfg.nim");
					(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					nimln_(262, "parsecfg.nim");
					goto LA7;
				}
				break;
				default:
				{
					NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_37;
					nimln_(264, "parsecfg.nim");
					(*tok).literal = addChar((*tok).literal, buf[pos]);
					nimln_(265, "parsecfg.nim");
					TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_37 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_37);
				}
				break;
				}
			}
		} LA7: ;
		nimln_(266, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_38 = addInt(pos, ((NI) 3));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_38);
	}
	goto LA1_;
	LA5_: ;
	{
		{
			nimln_(269, "parsecfg.nim");
			while (1) {
				NIM_CHAR ch;
				nimln_(270, "parsecfg.nim");
				ch = buf[pos];
				nimln_(271, "parsecfg.nim");
				{
					NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_39;
					if (!((NU8)(ch) == (NU8)(34))) goto LA24_;
					nimln_(272, "parsecfg.nim");
					TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_39 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_39);
					nimln_(273, "parsecfg.nim");
					goto LA20;
				}
				LA24_: ;
				nimln_(274, "parsecfg.nim");
				{
					if (!(((NU8)(ch)) == ((NU8)(13)) || ((NU8)(ch)) == ((NU8)(10)) || ((NU8)(ch)) == ((NU8)(0)))) goto LA28_;
					nimln_(275, "parsecfg.nim");
					(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					nimln_(276, "parsecfg.nim");
					goto LA20;
				}
				LA28_: ;
				nimln_(277, "parsecfg.nim");
				{
					NIM_BOOL T32_;
					T32_ = (NIM_BOOL)0;
					T32_ = ((NU8)(ch) == (NU8)(92));
					if (!(T32_)) goto LA33_;
					T32_ = !(rawMode);
					LA33_: ;
					if (!T32_) goto LA34_;
					nimln_(278, "parsecfg.nim");
					(*c).Sup.bufpos = pos;
					nimln_(279, "parsecfg.nim");
					getEscapedChar_oP5V5zBaqBvjlLHmM9aR5HQ(c, tok);
					nimln_(280, "parsecfg.nim");
					pos = (*c).Sup.bufpos;
				}
				goto LA30_;
				LA34_: ;
				{
					NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_40;
					nimln_(282, "parsecfg.nim");
					(*tok).literal = addChar((*tok).literal, ch);
					nimln_(283, "parsecfg.nim");
					TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_40 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_40);
				}
				LA30_: ;
			}
		} LA20: ;
		nimln_(284, "parsecfg.nim");
		(*c).Sup.bufpos = pos;
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, getSymbol_oP5V5zBaqBvjlLHmM9aR5HQ_2)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok) {
	NI pos;
	NCSTRING buf;
	nimfr_("getSymbol", "parsecfg.nim")
	nimln_(287, "parsecfg.nim");
	pos = (*c).Sup.bufpos;
	nimln_(288, "parsecfg.nim");
	buf = (*c).Sup.buf;
	{
		nimln_(289, "parsecfg.nim");
		while (1) {
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_41;
			nimln_(290, "parsecfg.nim");
			(*tok).literal = addChar((*tok).literal, buf[pos]);
			nimln_(291, "parsecfg.nim");
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_41 = addInt(pos, ((NI) 1));
			pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_41);
			nimln_(292, "parsecfg.nim");
			{
				if (!!(((TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_42[(NU)(((NU8)(buf[pos])))>>3] &(1U<<((NU)(((NU8)(buf[pos])))&7U)))!=0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
		}
	} LA1: ;
	nimln_(293, "parsecfg.nim");
	(*c).Sup.bufpos = pos;
	nimln_(294, "parsecfg.nim");
	(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2);
	popFrame();
}

N_NIMCALL(void, skip_AhN1A1FuhHZh69aN9cg2Os9cA)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c) {
	NI pos;
	NCSTRING buf;
	nimfr_("skip", "parsecfg.nim")
	nimln_(297, "parsecfg.nim");
	pos = (*c).Sup.bufpos;
	nimln_(298, "parsecfg.nim");
	buf = (*c).Sup.buf;
	{
		nimln_(299, "parsecfg.nim");
		while (1) {
			nimln_(300, "parsecfg.nim");
			switch (((NU8)(buf[pos]))) {
			case 32:
			case 9:
			{
				NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_43;
				nimln_(302, "parsecfg.nim");
				TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_43 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_43);
			}
			break;
			case 35:
			case 59:
			{
				{
					nimln_(304, "parsecfg.nim");
					while (1) {
						NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_44;
						if (!!((((NU8)(buf[pos])) == ((NU8)(13)) || ((NU8)(buf[pos])) == ((NU8)(10)) || ((NU8)(buf[pos])) == ((NU8)(0))))) goto LA6;
						TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_44 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_44);
					} LA6: ;
				}
			}
			break;
			case 13:
			case 10:
			{
				nimln_(306, "parsecfg.nim");
				pos = handleCRLF_aTSjoKixs63H4oDAFX9bRHQ(c, pos);
				nimln_(307, "parsecfg.nim");
				buf = (*c).Sup.buf;
			}
			break;
			default:
			{
				nimln_(309, "parsecfg.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	nimln_(310, "parsecfg.nim");
	(*c).Sup.bufpos = pos;
	popFrame();
}

N_NIMCALL(void, rawGetTok_O0TCNNdqmVst7YIKcVHcOQ)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, Token_yWkcM1ijvGYnxTAxtl3FPw* tok) {
	nimfr_("rawGetTok", "parsecfg.nim")
	nimln_(313, "parsecfg.nim");
	(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	nimln_(314, "parsecfg.nim");
	(*tok).literal = setLengthStr((*tok).literal, ((NI) 0));
	nimln_(315, "parsecfg.nim");
	skip_AhN1A1FuhHZh69aN9cg2Os9cA(c);
	nimln_(316, "parsecfg.nim");
	switch (((NU8)((*c).Sup.buf[(*c).Sup.bufpos]))) {
	case 61:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_45;
		nimln_(318, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 3);
		nimln_(319, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_45 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_45);
		nimln_(320, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_46)));
	}
	break;
	case 45:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_47;
		nimln_(322, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_47 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_47);
		nimln_(323, "parsecfg.nim");
		{
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_48;
			if (!((NU8)((*c).Sup.buf[(*c).Sup.bufpos]) == (NU8)(45))) goto LA5_;
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_48 = addInt((*c).Sup.bufpos, ((NI) 1));
			(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_48);
		}
		LA5_: ;
		nimln_(324, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 7);
		nimln_(325, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_49)));
	}
	break;
	case 58:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_50;
		nimln_(327, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 4);
		nimln_(328, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_50 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_50);
		nimln_(329, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_51)));
	}
	break;
	case 114:
	case 82:
	{
		nimln_(331, "parsecfg.nim");
		{
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_52;
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_53;
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_52 = addInt((*c).Sup.bufpos, ((NI) 1));
			if (!((NU8)((*c).Sup.buf[(NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_52)]) == (NU8)(34))) goto LA11_;
			nimln_(332, "parsecfg.nim");
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_53 = addInt((*c).Sup.bufpos, ((NI) 1));
			(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_53);
			nimln_(333, "parsecfg.nim");
			getString_kPdxas01T9chtV9cOXL7akew(c, tok, NIM_TRUE);
		}
		goto LA9_;
		LA11_: ;
		{
			nimln_(335, "parsecfg.nim");
			getSymbol_oP5V5zBaqBvjlLHmM9aR5HQ_2(c, tok);
		}
		LA9_: ;
	}
	break;
	case 91:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_54;
		nimln_(337, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 5);
		nimln_(338, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_54 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_54);
		nimln_(339, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_55)));
	}
	break;
	case 93:
	{
		NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_56;
		nimln_(341, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 6);
		nimln_(342, "parsecfg.nim");
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_56 = addInt((*c).Sup.bufpos, ((NI) 1));
		(*c).Sup.bufpos = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_56);
		nimln_(343, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_55)));
	}
	break;
	case 34:
	{
		nimln_(345, "parsecfg.nim");
		getString_kPdxas01T9chtV9cOXL7akew(c, tok, NIM_FALSE);
	}
	break;
	case 0:
	{
		nimln_(347, "parsecfg.nim");
		(*tok).kind = ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 1);
		nimln_(348, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_57)));
	}
	break;
	default:
	{
		nimln_(349, "parsecfg.nim");
		getSymbol_oP5V5zBaqBvjlLHmM9aR5HQ_2(c, tok);
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, npcerrorStr)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NimStringDesc* msg) {
	NimStringDesc* result;
	TY_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	nimfr_("errorStr", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(354, "parsecfg.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString((*c).filename);
	nimln_(355, "parsecfg.nim");
	T2_ = (NI)0;
	T2_ = npcgetLine(c);
	T1_[1] = nimIntToStr(T2_);
	T3_ = (NI)0;
	T3_ = npcgetColumn(c);
	T1_[2] = nimIntToStr(T3_);
	T1_[3] = copyString(msg);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_58), T1_, 4);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, npcwarningStr)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, NimStringDesc* msg) {
	NimStringDesc* result;
	TY_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	nimfr_("warningStr", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(360, "parsecfg.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString((*c).filename);
	nimln_(361, "parsecfg.nim");
	T2_ = (NI)0;
	T2_ = npcgetLine(c);
	T1_[1] = nimIntToStr(T2_);
	T3_ = (NI)0;
	T3_ = npcgetColumn(c);
	T1_[2] = nimIntToStr(T3_);
	T1_[3] = copyString(msg);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_59), T1_, 4);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, npcignoreMsg)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* e) {
	NimStringDesc* result;
	nimfr_("ignoreMsg", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(366, "parsecfg.nim");
	switch ((*e).kind) {
	case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 1):
	{
		NimStringDesc* T2_;
		nimln_(367, "parsecfg.nim");
		T2_ = (NimStringDesc*)0;
		if (!(((2 &(1U<<((NU)((*e).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_61));
		T2_ = rawNewString((*e).kindU.S2.section->Sup.len + 17);
appendString(T2_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_60));
appendString(T2_, (*e).kindU.S2.section);
		result = npcwarningStr(c, T2_);
	}
	break;
	case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 2):
	{
		NimStringDesc* T4_;
		nimln_(368, "parsecfg.nim");
		T4_ = (NimStringDesc*)0;
		if (!(((12 &(1U<<((NU)((*e).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63));
		T4_ = rawNewString((*e).kindU.S3.key->Sup.len + 13);
appendString(T4_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_62));
appendString(T4_, (*e).kindU.S3.key);
		result = npcwarningStr(c, T4_);
	}
	break;
	case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 3):
	{
		NimStringDesc* T6_;
		nimln_(370, "parsecfg.nim");
		T6_ = (NimStringDesc*)0;
		if (!(((12 &(1U<<((NU)((*e).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63));
		if (!(((12 &(1U<<((NU)((*e).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66));
		T6_ = rawNewString((*e).kindU.S3.key->Sup.len + (*e).kindU.S3.value->Sup.len + 19);
appendString(T6_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_64));
appendString(T6_, (*e).kindU.S3.key);
appendString(T6_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_65));
appendString(T6_, (*e).kindU.S3.value);
		result = npcwarningStr(c, T6_);
	}
	break;
	case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4):
	{
		nimln_(371, "parsecfg.nim");
		if (!(((16 &(1U<<((NU)((*e).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
		result = copyString((*e).kindU.S4.msg);
	}
	break;
	case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 0):
	{
		nimln_(372, "parsecfg.nim");
		result = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, getKeyValPair_wU9bLoPwmfHqL352Lwkk0kA)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEventKind_f0xwqI11H3rviaTXvjDJug kind, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* Result) {
	nimfr_("getKeyValPair", "parsecfg.nim")
	nimln_(375, "parsecfg.nim");
	{
		CfgEventKind_f0xwqI11H3rviaTXvjDJug T5_;
		if (!((*c).tok.kind == ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA3_;
		nimln_(376, "parsecfg.nim");
		T5_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
		T5_ = kind;
		FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T5_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
		(*Result).kind = T5_;
		if (!(((12 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63));
		nimln_(377, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*Result).kindU.S3.key), copyString((*c).tok.literal));
		if (!(((12 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66));
		nimln_(378, "parsecfg.nim");
		unsureAsgnRef((void**) (&(*Result).kindU.S3.value), copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3)));
		nimln_(379, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		nimln_(380, "parsecfg.nim");
		{
			if (!((24 &(1U<<((NU)((*c).tok.kind)&7U)))!=0)) goto LA8_;
			nimln_(381, "parsecfg.nim");
			rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
			nimln_(382, "parsecfg.nim");
			{
				if (!((*c).tok.kind == ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA12_;
				if (!(((12 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66));
				nimln_(383, "parsecfg.nim");
				unsureAsgnRef((void**) (&(*Result).kindU.S3.value), copyString((*c).tok.literal));
			}
			goto LA10_;
			LA12_: ;
			{
				CfgEventKind_f0xwqI11H3rviaTXvjDJug T15_;
				NimStringDesc* T16_;
				nimln_(385, "parsecfg.nim");
				genericReset((void*)Result, (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_));
				nimln_(386, "parsecfg.nim");
				T15_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
				T15_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4);
				FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T15_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
				(*Result).kind = T15_;
				if (!(((16 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
				nimln_(387, "parsecfg.nim");
				T16_ = (NimStringDesc*)0;
				T16_ = rawNewString((*c).tok.literal->Sup.len + 28);
appendString(T16_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_72));
appendString(T16_, (*c).tok.literal);
				unsureAsgnRef((void**) (&(*Result).kindU.S4.msg), npcerrorStr((&(*c)), T16_));
			}
			LA10_: ;
			nimln_(388, "parsecfg.nim");
			rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		}
		LA8_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		CfgEventKind_f0xwqI11H3rviaTXvjDJug T18_;
		NimStringDesc* T19_;
		nimln_(390, "parsecfg.nim");
		T18_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
		T18_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4);
		FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T18_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
		(*Result).kind = T18_;
		if (!(((16 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
		nimln_(391, "parsecfg.nim");
		T19_ = (NimStringDesc*)0;
		T19_ = rawNewString((*c).tok.literal->Sup.len + 28);
appendString(T19_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_72));
appendString(T19_, (*c).tok.literal);
		unsureAsgnRef((void**) (&(*Result).kindU.S4.msg), npcerrorStr((&(*c)), T19_));
		nimln_(392, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, npcnext)(CfgParser_w8XFEe9aT1CBajTOt4fsMRA* c, CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q* Result) {
	nimfr_("next", "parsecfg.nim")
	nimln_(396, "parsecfg.nim");
	switch ((*c).tok.kind) {
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 1):
	{
		CfgEventKind_f0xwqI11H3rviaTXvjDJug T2_;
		nimln_(398, "parsecfg.nim");
		T2_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
		T2_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 0);
		FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T2_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
		(*Result).kind = T2_;
	}
	break;
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 7):
	{
		nimln_(400, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		nimln_(401, "parsecfg.nim");
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_));
		(*Result).Sup.m_type = (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_);
		getKeyValPair_wU9bLoPwmfHqL352Lwkk0kA(c, ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 3), Result);
	}
	break;
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2):
	{
		nimln_(403, "parsecfg.nim");
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_));
		(*Result).Sup.m_type = (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_);
		getKeyValPair_wU9bLoPwmfHqL352Lwkk0kA(c, ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 2), Result);
	}
	break;
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 5):
	{
		nimln_(405, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		nimln_(406, "parsecfg.nim");
		{
			CfgEventKind_f0xwqI11H3rviaTXvjDJug T10_;
			if (!((*c).tok.kind == ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA8_;
			nimln_(407, "parsecfg.nim");
			T10_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
			T10_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 1);
			FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T10_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
			(*Result).kind = T10_;
			if (!(((2 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_61));
			nimln_(408, "parsecfg.nim");
			unsureAsgnRef((void**) (&(*Result).kindU.S2.section), copyString((*c).tok.literal));
		}
		goto LA6_;
		LA8_: ;
		{
			CfgEventKind_f0xwqI11H3rviaTXvjDJug T12_;
			NimStringDesc* T13_;
			nimln_(410, "parsecfg.nim");
			T12_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
			T12_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4);
			FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T12_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
			(*Result).kind = T12_;
			if (!(((16 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
			nimln_(411, "parsecfg.nim");
			T13_ = (NimStringDesc*)0;
			T13_ = rawNewString((*c).tok.literal->Sup.len + 28);
appendString(T13_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_72));
appendString(T13_, (*c).tok.literal);
			unsureAsgnRef((void**) (&(*Result).kindU.S4.msg), npcerrorStr((&(*c)), T13_));
		}
		LA6_: ;
		nimln_(412, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		nimln_(413, "parsecfg.nim");
		{
			if (!((*c).tok.kind == ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 6))) goto LA16_;
			nimln_(414, "parsecfg.nim");
			rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
		}
		goto LA14_;
		LA16_: ;
		{
			CfgEventKind_f0xwqI11H3rviaTXvjDJug T19_;
			NimStringDesc* T20_;
			nimln_(416, "parsecfg.nim");
			genericReset((void*)Result, (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_));
			nimln_(417, "parsecfg.nim");
			T19_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
			T19_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4);
			FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T19_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
			(*Result).kind = T19_;
			if (!(((16 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
			nimln_(418, "parsecfg.nim");
			T20_ = (NimStringDesc*)0;
			T20_ = rawNewString((*c).tok.literal->Sup.len + 25);
appendString(T20_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_73));
appendString(T20_, (*c).tok.literal);
			unsureAsgnRef((void**) (&(*Result).kindU.S4.msg), npcerrorStr((&(*c)), T20_));
		}
		LA14_: ;
	}
	break;
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 0):
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 3):
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 4):
	case ((TokKind_PvpTf9b5cBhdKx1DK5Ed3dg) 6):
	{
		CfgEventKind_f0xwqI11H3rviaTXvjDJug T22_;
		NimStringDesc* T23_;
		nimln_(420, "parsecfg.nim");
		T22_ = (CfgEventKind_f0xwqI11H3rviaTXvjDJug)0;
		T22_ = ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4);
		FieldDiscriminantCheck((NI)(NU)((*Result).kind), (NI)(NU)(T22_), NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind, 6);
		(*Result).kind = T22_;
		if (!(((16 &(1U<<((NU)((*Result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_67));
		nimln_(421, "parsecfg.nim");
		T23_ = (NimStringDesc*)0;
		T23_ = rawNewString((*c).tok.literal->Sup.len + 15);
appendString(T23_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_74));
appendString(T23_, (*c).tok.literal);
		unsureAsgnRef((void**) (&(*Result).kindU.S4.msg), npcerrorStr((&(*c)), T23_));
		nimln_(422, "parsecfg.nim");
		rawGetTok_O0TCNNdqmVst7YIKcVHcOQ(c, (&(*c).tok));
	}
	break;
	}
	popFrame();
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(363, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_75;
	nimfr_("nextTry", "tableimpl.nim")
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_75 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_75) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_KEl4Q0aIVF3m8CuRfASJVAtables)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	nimfr_("rawGetDeep", "tables.nim")
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}

N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, newConfig_Afv7qS60mn8mdc3HRBrzHA)(void) {
	OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* result;
	nimfr_("newConfig", "parsecfg.nim")
	result = (OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*)0;
	nimln_(772, "tables.nim");
	result = newOrderedTable_kI9avJX0pn2OsRj3l0p70QQ(((NI) 64));
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_uYmQ5SD89aRmmSv3V1LJIewtables)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	nimfr_("rawGetDeep", "tables.nim")
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_KEl4Q0aIVF3m8CuRfASJVA_2tables)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_76;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = ((*t).data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = eqStrings((*t).data->data[h].Field2, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_76 = subInt(((NI) -1), h);
	result = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_76);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, loadConfig_P9biP5fyx9bLJK29aESwkIRBA)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream, NimStringDesc* filename) {
	OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* result;
	OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict;
	NimStringDesc* curSection;
	CfgParser_w8XFEe9aT1CBajTOt4fsMRA p;
	nimfr_("loadConfig", "parsecfg.nim")
	result = (OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*)0;
	nimln_(436, "parsecfg.nim");
	dict = newOrderedTable_kI9avJX0pn2OsRj3l0p70QQ(((NI) 64));
	nimln_(437, "parsecfg.nim");
	curSection = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
	memset((void*)(&p), 0, sizeof(p));
	p.Sup.Sup.m_type = (&NTI_w8XFEe9aT1CBajTOt4fsMRA_);
	nimln_(441, "parsecfg.nim");
	npcopen((&p), stream, filename, ((NI) 0));
	{
		nimln_(442, "parsecfg.nim");
		while (1) {
			CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q e;
			memset((void*)(&e), 0, sizeof(e));
			e.Sup.m_type = (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_);
			nimln_(443, "parsecfg.nim");
			chckNil((void*)(&e));
			memset((void*)(&e), 0, sizeof(e));
			e.Sup.m_type = (&NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_);
			npcnext((&p), (&e));
			nimln_(444, "parsecfg.nim");
			switch (e.kind) {
			case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 0):
			{
				nimln_(446, "parsecfg.nim");
				goto LA1;
			}
			break;
			case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 1):
			{
				nimln_(448, "parsecfg.nim");
				if (!(((2 &(1U<<((NU)(e.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_61));
				curSection = copyString(e.kindU.S2.section);
			}
			break;
			case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 2):
			{
				OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t;
				nimln_(450, "parsecfg.nim");
				t = newOrderedTable_8wX2B22l1w9bbsrSuaZolwQ(((NI) 64));
				nimln_(451, "parsecfg.nim");
				{
					NIM_BOOL T8_;
					OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T11_;
					T8_ = (NIM_BOOL)0;
					T8_ = hasKey_QXMvqDynw9acW1siAbeTY1g(dict, curSection);
					if (!T8_) goto LA9_;
					nimln_(452, "parsecfg.nim");
					T11_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
					T11_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg(dict, curSection);
					t = (*T11_);
				}
				LA9_: ;
				nimln_(453, "parsecfg.nim");
				if (!(((12 &(1U<<((NU)(e.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63));
				if (!(((12 &(1U<<((NU)(e.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66));
				X5BX5Deq__X7zbF3UXb9beC6mdDvbm7yQ_2(t, e.kindU.S3.key, e.kindU.S3.value);
				nimln_(454, "parsecfg.nim");
				X5BX5Deq__vY5zyZwuf0SpXyorOkqQCg_2(dict, curSection, t);
			}
			break;
			case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 3):
			{
				OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* c;
				NimStringDesc* T19_;
				nimln_(456, "parsecfg.nim");
				c = newOrderedTable_8wX2B22l1w9bbsrSuaZolwQ(((NI) 64));
				nimln_(457, "parsecfg.nim");
				{
					NIM_BOOL T15_;
					OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T18_;
					T15_ = (NIM_BOOL)0;
					T15_ = hasKey_QXMvqDynw9acW1siAbeTY1g(dict, curSection);
					if (!T15_) goto LA16_;
					nimln_(458, "parsecfg.nim");
					T18_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
					T18_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg(dict, curSection);
					c = (*T18_);
				}
				LA16_: ;
				nimln_(459, "parsecfg.nim");
				T19_ = (NimStringDesc*)0;
				if (!(((12 &(1U<<((NU)(e.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_63));
				T19_ = rawNewString(e.kindU.S3.key->Sup.len + 2);
appendString(T19_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_49));
appendString(T19_, e.kindU.S3.key);
				if (!(((12 &(1U<<((NU)(e.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_66));
				X5BX5Deq__X7zbF3UXb9beC6mdDvbm7yQ_2(c, T19_, e.kindU.S3.value);
				nimln_(460, "parsecfg.nim");
				X5BX5Deq__vY5zyZwuf0SpXyorOkqQCg_2(dict, curSection, c);
			}
			break;
			case ((CfgEventKind_f0xwqI11H3rviaTXvjDJug) 4):
			{
				nimln_(462, "parsecfg.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	nimln_(463, "parsecfg.nim");
	npcclose((&p));
	nimln_(464, "parsecfg.nim");
	result = dict;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*, loadConfig_sAs1zICpXe0t2WsYDGJLHA)(NimStringDesc* filename) {
	OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* volatile result;
	FILE* file;
	FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* fileStream;
	TSafePoint TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82;
	nimfr_("loadConfig", "parsecfg.nim")
	result = (OrderedTable_mjwQ71q4DGaXE1Pub8TBoA*)0;
	nimln_(468, "parsecfg.nim");
	file = open_hqzpWQbdA2B8l9a6wwNoP4g(filename, ((FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	nimln_(469, "parsecfg.nim");
	fileStream = newFileStream_j9aOzR9a9bXMSUnTXiGmXXGqQ(file);
	nimln_(470, "parsecfg.nim");
	pushSafePoint(&TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82);
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82.status = _setjmp(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82.context);
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82.status == 0) {
		StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T2_;
		nimln_(471, "parsecfg.nim");
		T2_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
		T2_ = &fileStream->Sup;
		result = loadConfig_P9biP5fyx9bLJK29aESwkIRBA(T2_, filename);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T5_;
		nimln_(470, "parsecfg.nim");
		T5_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
		T5_ = &fileStream->Sup;
		close_4ed7IXme7lqtClFI7s2sTQ_2(T5_);
	}
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_82.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, replace_YSAU1uzU2PmXN4yWDJB9a1Q)(NimStringDesc* s) {
	NimStringDesc* result;
	NimStringDesc* d;
	NI i;
	nimfr_("replace", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(474, "parsecfg.nim");
	d = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
	nimln_(475, "parsecfg.nim");
	i = ((NI) 0);
	{
		nimln_(476, "parsecfg.nim");
		while (1) {
			NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_87;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(477, "parsecfg.nim");
			{
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(92))) goto LA5_;
				nimln_(478, "parsecfg.nim");
				d = resizeString(d, 2);
appendString(d, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_83));
			}
			goto LA3_;
			LA5_: ;
			{
				NIM_BOOL T8_;
				NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_84;
				NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_86;
				nimln_(479, "parsecfg.nim");
				T8_ = (NIM_BOOL)0;
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				T8_ = ((NU8)(s->data[i]) == (NU8)(13));
				if (!(T8_)) goto LA9_;
				TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_84 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_84)) > (NU)(s->Sup.len)) raiseIndexError();
				T8_ = ((NU8)(s->data[(NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_84)]) == (NU8)(10));
				LA9_: ;
				if (!T8_) goto LA10_;
				nimln_(480, "parsecfg.nim");
				d = resizeString(d, 2);
appendString(d, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_85));
				nimln_(481, "parsecfg.nim");
				TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_86 = addInt(i, ((NI) 1));
				i = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_86);
			}
			goto LA3_;
			LA10_: ;
			{
				nimln_(482, "parsecfg.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(13))) goto LA13_;
				nimln_(483, "parsecfg.nim");
				d = resizeString(d, 2);
appendString(d, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_85));
			}
			goto LA3_;
			LA13_: ;
			{
				nimln_(484, "parsecfg.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(10))) goto LA16_;
				nimln_(485, "parsecfg.nim");
				d = resizeString(d, 2);
appendString(d, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_85));
			}
			goto LA3_;
			LA16_: ;
			{
				nimln_(487, "parsecfg.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				d = addChar(d, s->data[i]);
			}
			LA3_: ;
			nimln_(488, "parsecfg.nim");
			TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_87 = addInt(i, ((NI) 1));
			i = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_87);
		} LA2: ;
	}
	nimln_(489, "parsecfg.nim");
	result = copyString(d);
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim")
	result = (NimStringDesc*)0;
	nimln_(3345, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(290, "system.nim");
	result.a = a;
	nimln_(291, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(void, writeConfig_fwJshzcWuYNR7DAGOpxrvQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream) {
	nimfr_("writeConfig", "parsecfg.nim")
	{
		NimStringDesc* section;
		OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* sectionData;
		NI h;
		section = (NimStringDesc*)0;
		sectionData = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ*)0;
		nimln_(502, "tables.nim");
		h = (*dict).first;
		{
			nimln_(707, "tables.nim");
			while (1) {
				NI nxt;
				nimln_(503, "tables.nim");
				if (!(((NI) 0) <= h)) goto LA3;
				nimln_(504, "tables.nim");
				if ((NU)(h) >= (NU)((*dict).data->Sup.len)) raiseIndexError();
				nxt = (*dict).data->data[h].Field1;
				nimln_(505, "tables.nim");
				{
					NIM_BOOL T6_;
					if ((NU)(h) >= (NU)((*dict).data->Sup.len)) raiseIndexError();
					T6_ = (NIM_BOOL)0;
					T6_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*dict).data->data[h].Field0);
					if (!T6_) goto LA7_;
					nimln_(708, "tables.nim");
					if ((NU)(h) >= (NU)((*dict).data->Sup.len)) raiseIndexError();
					section = (*dict).data->data[h].Field2;
					if ((NU)(h) >= (NU)((*dict).data->Sup.len)) raiseIndexError();
					sectionData = (*dict).data->data[h].Field3;
					nimln_(496, "parsecfg.nim");
					{
						nimln_(363, "system.nim");
						nimln_(496, "parsecfg.nim");
						if (!!(((section) && (section)->Sup.len == 0))) goto LA11_;
						nimln_(497, "parsecfg.nim");
						{
							NIM_BOOL T15_;
							TY_nHXaesL0DJZHyVS07ARPRA T18_;
							NimStringDesc* T19_;
							T15_ = (NIM_BOOL)0;
							T15_ = allCharsInSet_wVfr4F6j4mVzI8ggLoMVdw(section, TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_42);
							if (!!(T15_)) goto LA16_;
							nimln_(498, "parsecfg.nim");
							memset((void*)T18_, 0, sizeof(T18_));
							T19_ = (NimStringDesc*)0;
							T19_ = rawNewString(section->Sup.len + 4);
appendString(T19_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_88));
appendString(T19_, section);
appendString(T19_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_89));
							T18_[0] = T19_;
							writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, T18_, 1);
						}
						goto LA13_;
						LA16_: ;
						{
							TY_nHXaesL0DJZHyVS07ARPRA T21_;
							NimStringDesc* T22_;
							nimln_(500, "parsecfg.nim");
							memset((void*)T21_, 0, sizeof(T21_));
							T22_ = (NimStringDesc*)0;
							T22_ = rawNewString(section->Sup.len + 2);
appendString(T22_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_90));
appendString(T22_, section);
appendString(T22_, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_55));
							T21_[0] = T22_;
							writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, T21_, 1);
						}
						LA13_: ;
					}
					LA11_: ;
					{
						NimStringDesc* key;
						NimStringDesc* value;
						NI h_2;
						key = (NimStringDesc*)0;
						value = (NimStringDesc*)0;
						nimln_(502, "tables.nim");
						h_2 = (*sectionData).first;
						{
							nimln_(707, "tables.nim");
							while (1) {
								NI nxt_2;
								nimln_(503, "tables.nim");
								if (!(((NI) 0) <= h_2)) goto LA25;
								nimln_(504, "tables.nim");
								if ((NU)(h_2) >= (NU)((*sectionData).data->Sup.len)) raiseIndexError();
								nxt_2 = (*sectionData).data->data[h_2].Field1;
								nimln_(505, "tables.nim");
								{
									NIM_BOOL T28_;
									NimStringDesc* kv;
									NimStringDesc* segmentChar;
									TY_nHXaesL0DJZHyVS07ARPRA T68_;
									if ((NU)(h_2) >= (NU)((*sectionData).data->Sup.len)) raiseIndexError();
									T28_ = (NIM_BOOL)0;
									T28_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*sectionData).data->data[h_2].Field0);
									if (!T28_) goto LA29_;
									nimln_(708, "tables.nim");
									if ((NU)(h_2) >= (NU)((*sectionData).data->Sup.len)) raiseIndexError();
									key = (*sectionData).data->data[h_2].Field2;
									if ((NU)(h_2) >= (NU)((*sectionData).data->Sup.len)) raiseIndexError();
									value = (*sectionData).data->data[h_2].Field3;
									kv = (NimStringDesc*)0;
									segmentChar = (NimStringDesc*)0;
									nimln_(503, "parsecfg.nim");
									{
										NIM_BOOL T33_;
										NIM_BOOL T34_;
										T33_ = (NIM_BOOL)0;
										T34_ = (NIM_BOOL)0;
										T34_ = (((NI) 1) < (key ? key->Sup.len : 0));
										if (!(T34_)) goto LA35_;
										if ((NU)(((NI) 0)) > (NU)(key->Sup.len)) raiseIndexError();
										T34_ = ((NU8)(key->data[((NI) 0)]) == (NU8)(45));
										LA35_: ;
										T33_ = T34_;
										if (!(T33_)) goto LA36_;
										if ((NU)(((NI) 1)) > (NU)(key->Sup.len)) raiseIndexError();
										T33_ = ((NU8)(key->data[((NI) 1)]) == (NU8)(45));
										LA36_: ;
										if (!T33_) goto LA37_;
										nimln_(504, "parsecfg.nim");
										segmentChar = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_51));
										nimln_(505, "parsecfg.nim");
										{
											NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_91;
											Slice_qL3WGViqT0p5sVr4YFHsLg T41_;
											NimStringDesc* T42_;
											NIM_BOOL T43_;
											NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_93;
											Slice_qL3WGViqT0p5sVr4YFHsLg T46_;
											NimStringDesc* T47_;
											TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_91 = subInt((key ? key->Sup.len : 0), ((NI) 1));
											T41_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 2), (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_91));
											T42_ = (NimStringDesc*)0;
											T42_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(key, T41_);
											T43_ = (NIM_BOOL)0;
											T43_ = allCharsInSet_wVfr4F6j4mVzI8ggLoMVdw(T42_, TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_42);
											if (!!(T43_)) goto LA44_;
											nimln_(506, "parsecfg.nim");
											kv = resizeString(kv, 3);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_92));
											nimln_(507, "parsecfg.nim");
											TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_93 = subInt((key ? key->Sup.len : 0), ((NI) 1));
											T46_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 2), (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_93));
											T47_ = (NimStringDesc*)0;
											T47_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(key, T46_);
											kv = resizeString(kv, T47_->Sup.len + 0);
appendString(kv, T47_);
											nimln_(508, "parsecfg.nim");
											kv = resizeString(kv, 1);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_94));
										}
										goto LA39_;
										LA44_: ;
										{
											nimln_(510, "parsecfg.nim");
											kv = copyString(key);
										}
										LA39_: ;
									}
									goto LA31_;
									LA37_: ;
									{
										nimln_(512, "parsecfg.nim");
										segmentChar = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_46));
										nimln_(513, "parsecfg.nim");
										kv = copyString(key);
									}
									LA31_: ;
									nimln_(514, "parsecfg.nim");
									{
										nimln_(363, "system.nim");
										nimln_(514, "parsecfg.nim");
										if (!!(((value) && (value)->Sup.len == 0))) goto LA52_;
										nimln_(515, "parsecfg.nim");
										{
											NIM_BOOL T56_;
											T56_ = (NIM_BOOL)0;
											T56_ = allCharsInSet_wVfr4F6j4mVzI8ggLoMVdw(value, TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_42);
											if (!!(T56_)) goto LA57_;
											nimln_(516, "parsecfg.nim");
											{
												NI T61_;
												NimStringDesc* T64_;
												T61_ = (NI)0;
												T61_ = nsuFindChar(value, 34, ((NI) 0), ((NI) 0));
												if (!(T61_ == ((NI) -1))) goto LA62_;
												nimln_(517, "parsecfg.nim");
												kv = resizeString(kv, segmentChar->Sup.len + 0);
appendString(kv, segmentChar);
												nimln_(518, "parsecfg.nim");
												kv = resizeString(kv, 1);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_94));
												nimln_(519, "parsecfg.nim");
												T64_ = (NimStringDesc*)0;
												T64_ = replace_YSAU1uzU2PmXN4yWDJB9a1Q(value);
												kv = resizeString(kv, T64_->Sup.len + 0);
appendString(kv, T64_);
												nimln_(520, "parsecfg.nim");
												kv = resizeString(kv, 1);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_94));
											}
											goto LA59_;
											LA62_: ;
											{
												NimStringDesc* T66_;
												nimln_(522, "parsecfg.nim");
												kv = resizeString(kv, segmentChar->Sup.len + 0);
appendString(kv, segmentChar);
												nimln_(523, "parsecfg.nim");
												kv = resizeString(kv, 3);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_95));
												nimln_(524, "parsecfg.nim");
												T66_ = (NimStringDesc*)0;
												T66_ = replace_YSAU1uzU2PmXN4yWDJB9a1Q(value);
												kv = resizeString(kv, T66_->Sup.len + 0);
appendString(kv, T66_);
												nimln_(525, "parsecfg.nim");
												kv = resizeString(kv, 3);
appendString(kv, ((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_95));
											}
											LA59_: ;
										}
										goto LA54_;
										LA57_: ;
										{
											nimln_(527, "parsecfg.nim");
											kv = resizeString(kv, segmentChar->Sup.len + 0);
appendString(kv, segmentChar);
											nimln_(528, "parsecfg.nim");
											kv = resizeString(kv, value->Sup.len + 0);
appendString(kv, value);
										}
										LA54_: ;
									}
									LA52_: ;
									nimln_(529, "parsecfg.nim");
									memset((void*)T68_, 0, sizeof(T68_));
									T68_[0] = copyString(kv);
									writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, T68_, 1);
								}
								LA29_: ;
								nimln_(506, "tables.nim");
								h_2 = nxt_2;
							} LA25: ;
						}
					}
				}
				LA7_: ;
				h = nxt;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, dollar__Jw6uJyteAGBUfezZp9aQY1w)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict) {
	NimStringDesc* volatile result;
	StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ* stream;
	TSafePoint TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96;
	nimfr_("$", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(534, "parsecfg.nim");
	stream = newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
	nimln_(535, "parsecfg.nim");
	pushSafePoint(&TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96);
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96.status = _setjmp(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96.context);
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96.status == 0) {
		StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T2_;
		nimln_(536, "parsecfg.nim");
		T2_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
		T2_ = &stream->Sup;
		writeConfig_fwJshzcWuYNR7DAGOpxrvQ(dict, T2_);
		nimln_(537, "parsecfg.nim");
		result = copyString((*stream).data);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T5_;
		nimln_(535, "parsecfg.nim");
		T5_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
		T5_ = &stream->Sup;
		close_4ed7IXme7lqtClFI7s2sTQ_2(T5_);
	}
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_96.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, writeConfig_AVb38iG6BzScmMQ65OXTHQ)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, NimStringDesc* filename) {
	FILE* file;
	TSafePoint TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97;
	nimfr_("writeConfig", "parsecfg.nim")
	nimln_(542, "parsecfg.nim");
	file = open_hqzpWQbdA2B8l9a6wwNoP4g(filename, ((FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	nimln_(543, "parsecfg.nim");
	pushSafePoint(&TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97);
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97.status = _setjmp(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97.context);
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97.status == 0) {
		FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* fileStream;
		TSafePoint TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98;
		nimln_(544, "parsecfg.nim");
		fileStream = newFileStream_j9aOzR9a9bXMSUnTXiGmXXGqQ(file);
		nimln_(545, "parsecfg.nim");
		pushSafePoint(&TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98);
		TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98.status = _setjmp(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98.context);
		if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98.status == 0) {
			StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T3_;
			nimln_(546, "parsecfg.nim");
			T3_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
			T3_ = &fileStream->Sup;
			writeConfig_fwJshzcWuYNR7DAGOpxrvQ(dict, T3_);
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T6_;
			nimln_(545, "parsecfg.nim");
			T6_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
			T6_ = &fileStream->Sup;
			close_4ed7IXme7lqtClFI7s2sTQ_2(T6_);
		}
		if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_98.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(543, "parsecfg.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_2(file);
	}
	if (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_97.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(NI, rawGet_uYmQ5SD89aRmmSv3V1LJIew_2tables)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_99;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = ((*t).data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = eqStrings((*t).data->data[h].Field2, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_99 = subInt(((NI) -1), h);
	result = (NI)(TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_99);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getSectionValue_eZ9bxHq9ckUeG07mAVDw3Gxg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA* dict, NimStringDesc* section, NimStringDesc* key) {
	NimStringDesc* result;
	nimfr_("getSectionValue", "parsecfg.nim")
	result = (NimStringDesc*)0;
	nimln_(550, "parsecfg.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey_QXMvqDynw9acW1siAbeTY1g(dict, section);
		if (!T3_) goto LA4_;
		nimln_(551, "parsecfg.nim");
		{
			OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T8_;
			NIM_BOOL T9_;
			OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T12_;
			NimStringDesc** T13_;
			T8_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
			T8_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg(dict, section);
			T9_ = (NIM_BOOL)0;
			T9_ = hasKey_iW9aP1lP6iKnI2P9aTldk9a0w((*T8_), key);
			if (!T9_) goto LA10_;
			nimln_(552, "parsecfg.nim");
			T12_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
			T12_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg(dict, section);
			T13_ = (NimStringDesc**)0;
			T13_ = X5BX5D__Wk7VKmSqT9bZiMZK9aBX5qtA((*T12_), key);
			result = copyString((*T13_));
		}
		goto LA6_;
		LA10_: ;
		{
			nimln_(554, "parsecfg.nim");
			result = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
		}
		LA6_: ;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(556, "parsecfg.nim");
		result = copyString(((NimStringDesc*) &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_3));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, setSectionKey_XIb40Iom9bg27l7JWaBAxzw)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section, NimStringDesc* key, NimStringDesc* value) {
	OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t;
	nimfr_("setSectionKey", "parsecfg.nim")
	nimln_(560, "parsecfg.nim");
	t = newOrderedTable_8wX2B22l1w9bbsrSuaZolwQ(((NI) 64));
	nimln_(561, "parsecfg.nim");
	{
		NIM_BOOL T3_;
		OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey_QXMvqDynw9acW1siAbeTY1g((*dict), section);
		if (!T3_) goto LA4_;
		nimln_(562, "parsecfg.nim");
		T6_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
		T6_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg((*dict), section);
		t = (*T6_);
	}
	LA4_: ;
	nimln_(563, "parsecfg.nim");
	X5BX5Deq__X7zbF3UXb9beC6mdDvbm7yQ_2(t, key, value);
	nimln_(564, "parsecfg.nim");
	X5BX5Deq__vY5zyZwuf0SpXyorOkqQCg_2((*dict), section, t);
	popFrame();
}

N_NIMCALL(void, delSection_7eGHbl1hh7Q06GxLuf8JFg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section) {
	nimfr_("delSection", "parsecfg.nim")
	nimln_(568, "parsecfg.nim");
	del_9cIgyzt9cdEVWVfyq09cZpR9bg(dict, section);
	popFrame();
}

static N_INLINE(NI, len_3w9b2vhzm6CE22tViP9bI9bIAparsecfg)(OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ* t) {
	NI result;
	nimfr_("len", "tables.nim")
	result = (NI)0;
	nimln_(702, "tables.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

N_NIMCALL(void, delSectionKey_Pth9bkRuImc22OwfXlMtLsg)(OrderedTable_mjwQ71q4DGaXE1Pub8TBoA** dict, NimStringDesc* section, NimStringDesc* key) {
	nimfr_("delSectionKey", "parsecfg.nim")
	nimln_(572, "parsecfg.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey_QXMvqDynw9acW1siAbeTY1g((*dict), section);
		if (!T3_) goto LA4_;
		nimln_(573, "parsecfg.nim");
		{
			OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T8_;
			NIM_BOOL T9_;
			T8_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
			T8_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg((*dict), section);
			T9_ = (NIM_BOOL)0;
			T9_ = hasKey_iW9aP1lP6iKnI2P9aTldk9a0w((*T8_), key);
			if (!T9_) goto LA10_;
			nimln_(574, "parsecfg.nim");
			{
				OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T14_;
				NI T15_;
				T14_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
				T14_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg((*dict), section);
				T15_ = (NI)0;
				T15_ = len_3w9b2vhzm6CE22tViP9bI9bIAparsecfg((*T14_));
				if (!(T15_ == ((NI) 1))) goto LA16_;
				nimln_(575, "parsecfg.nim");
				del_9cIgyzt9cdEVWVfyq09cZpR9bg(dict, section);
			}
			goto LA12_;
			LA16_: ;
			{
				OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ** T19_;
				nimln_(577, "parsecfg.nim");
				T19_ = (OrderedTable_LfKAP6cLEdcUREzjv0N9bhQ**)0;
				T19_ = X5BX5D__6wUGmv25FDZ9c5o48wpNMyg((*dict), section);
				del_W69atDwFX0MX1ZCHAtMBCfw(T19_, key);
			}
			LA12_: ;
		}
		LA10_: ;
	}
	LA4_: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecfgInit000)(void) {
	nimfr_("parsecfg", "parsecfg.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parsecfgDatInit000)(void) {
static TNimNode* TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_68[5];
NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70;
static char* NIM_CONST TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_69[5] = {
"cfgEof", 
"cfgSectionStart", 
"cfgKeyValuePair", 
"cfgOption", 
"cfgError"};
static TNimNode* TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_71[2];
static TNimNode* TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_77[2];
static TNimNode* TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_78[2];
static TNimNode* TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_79[8];
NI TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81;
static char* NIM_CONST TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_80[8] = {
"tkInvalid", 
"tkEof", 
"tkSymbol", 
"tkEquals", 
"tkColon", 
"tkBracketLe", 
"tkBracketRi", 
"tkDashDash"};
static TNimNode TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[28];
NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_.size = sizeof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q);
NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_.kind = 17;
NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_f0xwqI11H3rviaTXvjDJug_.size = sizeof(CfgEventKind_f0xwqI11H3rviaTXvjDJug);
NTI_f0xwqI11H3rviaTXvjDJug_.kind = 14;
NTI_f0xwqI11H3rviaTXvjDJug_.base = 0;
NTI_f0xwqI11H3rviaTXvjDJug_.flags = 3;
for (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70 = 0; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70 < 5; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70++) {
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70+1].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70+1].offset = TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70+1].name = TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_69[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_68[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_70+1];
}
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].len = 5; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].kind = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].sons = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_68[0];
NTI_f0xwqI11H3rviaTXvjDJug_.node = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].kind = 3;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].offset = offsetof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q, kind);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].typ = (&NTI_f0xwqI11H3rviaTXvjDJug_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].name = "kind";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].sons = &NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[0];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].len = 5;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7].len = 0; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7].kind = 2;
NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[0] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].offset = offsetof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q, kindU.S2.section);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].name = "section";
NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[1] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_71[0] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].offset = offsetof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q, kindU.S3.key);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].name = "key";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_71[1] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].offset = offsetof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q, kindU.S3.value);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].name = "value";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].len = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].kind = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].sons = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_71[0];
NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[2] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9];
NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[3] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].offset = offsetof(CfgEvent_IQQt9ctNcwhKRKuCzK6Mm3Q, kindU.S4.msg);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].name = "msg";
NimDT__IQQt9ctNcwhKRKuCzK6Mm3Q_kind[4] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12];
NTI_IQQt9ctNcwhKRKuCzK6Mm3Q_.node = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0];
NTI_w8XFEe9aT1CBajTOt4fsMRA_.size = sizeof(CfgParser_w8XFEe9aT1CBajTOt4fsMRA);
NTI_w8XFEe9aT1CBajTOt4fsMRA_.kind = 17;
NTI_w8XFEe9aT1CBajTOt4fsMRA_.base = (&NTI_B6cGbTPhMsqMovc9cOcIHRw_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_77[0] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14];
NTI_yWkcM1ijvGYnxTAxtl3FPw_.size = sizeof(Token_yWkcM1ijvGYnxTAxtl3FPw);
NTI_yWkcM1ijvGYnxTAxtl3FPw_.kind = 18;
NTI_yWkcM1ijvGYnxTAxtl3FPw_.base = 0;
NTI_yWkcM1ijvGYnxTAxtl3FPw_.flags = 2;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_78[0] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16];
NTI_PvpTf9b5cBhdKx1DK5Ed3dg_.size = sizeof(TokKind_PvpTf9b5cBhdKx1DK5Ed3dg);
NTI_PvpTf9b5cBhdKx1DK5Ed3dg_.kind = 14;
NTI_PvpTf9b5cBhdKx1DK5Ed3dg_.base = 0;
NTI_PvpTf9b5cBhdKx1DK5Ed3dg_.flags = 3;
for (TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81 = 0; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81 < 8; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81++) {
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81+17].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81+17].offset = TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81+17].name = TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_80[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_79[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_81+17];
}
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[25].len = 8; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[25].kind = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[25].sons = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_79[0];
NTI_PvpTf9b5cBhdKx1DK5Ed3dg_.node = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[25];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].offset = offsetof(Token_yWkcM1ijvGYnxTAxtl3FPw, kind);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].typ = (&NTI_PvpTf9b5cBhdKx1DK5Ed3dg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].name = "kind";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_78[1] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[26];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[26].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[26].offset = offsetof(Token_yWkcM1ijvGYnxTAxtl3FPw, literal);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[26].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[26].name = "literal";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].len = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].kind = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].sons = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_78[0];
NTI_yWkcM1ijvGYnxTAxtl3FPw_.node = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].offset = offsetof(CfgParser_w8XFEe9aT1CBajTOt4fsMRA, tok);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].typ = (&NTI_yWkcM1ijvGYnxTAxtl3FPw_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].name = "tok";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_77[1] = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[27];
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[27].kind = 1;
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[27].offset = offsetof(CfgParser_w8XFEe9aT1CBajTOt4fsMRA, filename);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[27].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[27].name = "filename";
TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].len = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].kind = 2; TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].sons = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_77[0];
NTI_w8XFEe9aT1CBajTOt4fsMRA_.node = &TM_M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13];
}

